// All the original content belonged to the US Army

#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_liquid/em_bt_liquid.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"

Aem_bt_liquid::Aem_bt_liquid()
{
	USpriteEmitter* SpriteEmitter2 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter2->UseColorScale = true;
	SpriteEmitter2->FadeOut = true;
	SpriteEmitter2->ResetAfterChange = true;
	SpriteEmitter2->RespawnDeadParticles = false;
	SpriteEmitter2->UseSizeScale = true;
	SpriteEmitter2->UseRegularSizeScale = false;
	SpriteEmitter2->UniformSize = true;
	SpriteEmitter2->AutomaticInitialSpawning = false;
	SpriteEmitter2->Acceleration = FVector(0, 0, -900);
	//SpriteEmitter2->ColorScale[0]=FParticleColorScale({0,FColor(220, 150, 157, 100)});
	SpriteEmitter2->FadeOutStartTime = 0.3;
	SpriteEmitter2->MaxParticles = 1;
	//SpriteEmitter2->StartLocationRange=X=(Min=0, Max=0)|Y=(Min=0, Max=0)|Z=(Min=-25, Max=-25);
	//SpriteEmitter2->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter2->SizeScale[1]=FParticleTimeScale({1,4});
	//SpriteEmitter2->StartSizeRange=X=(Min=15, Max=18)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter2->InitialParticlesPerSecond = 2000;
	SpriteEmitter2->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter2->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/fx2_part_waterbits_Mat.fx2_part_waterbits_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter2->SecondsBeforeInactive = 0;
	SpriteEmitter2->LifetimeRange = FRange({ 0.6, 0.6 });
	//SpriteEmitter2->StartVelocityRange=X=(Min=0, Max=0)|Y=(Min=0, Max=0)|Z=(Min=260, Max=311);
	USpriteEmitter* SpriteEmitter3 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter3->UseColorScale = true;
	SpriteEmitter3->FadeOut = true;
	SpriteEmitter3->RespawnDeadParticles = false;
	SpriteEmitter3->UseSizeScale = true;
	SpriteEmitter3->UseRegularSizeScale = false;
	SpriteEmitter3->UniformSize = true;
	SpriteEmitter3->AutomaticInitialSpawning = false;
	SpriteEmitter3->Acceleration = FVector(0, 0, -20);
	//SpriteEmitter3->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 15)});
	//SpriteEmitter3->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 15)});
	SpriteEmitter3->FadeOutStartTime = 0.8;
	SpriteEmitter3->MaxParticles = 5;
	SpriteEmitter3->StartLocationOffset = FVector(-2, 0, 0);
	SpriteEmitter3->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter3->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter3->SizeScale[1]=FParticleTimeScale({1,3});
	//SpriteEmitter3->StartSizeRange=X=(Min=6, Max=8)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter3->InitialParticlesPerSecond = 1000;
	SpriteEmitter3->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter3->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter3->SecondsBeforeInactive = 0;
	SpriteEmitter3->LifetimeRange = FRange({ 1.5, 1.8 });
	//SpriteEmitter3->StartVelocityRange=X=(Min=-40, Max=40)|Y=(Min=-50, Max=55)|Z=(Min=0, Max=0);
	USpriteEmitter* SpriteEmitter4 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter4->UseColorScale = true;
	SpriteEmitter4->FadeOut = true;
	SpriteEmitter4->RespawnDeadParticles = false;
	SpriteEmitter4->SpinParticles = true;
	SpriteEmitter4->UseSizeScale = true;
	SpriteEmitter4->UseRegularSizeScale = false;
	SpriteEmitter4->UniformSize = true;
	SpriteEmitter4->AutomaticInitialSpawning = false;
	SpriteEmitter4->Acceleration = FVector(0, 0, -300);
	//SpriteEmitter4->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 95)});
	//SpriteEmitter4->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 105)});
	SpriteEmitter4->FadeOutStartTime = 0.5;
	SpriteEmitter4->MaxParticles = 2;
	//SpriteEmitter4->StartLocationRange=X=(Min=-36, Max=-38)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter4->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter4->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter4->SizeScale[1]=FParticleTimeScale({0.7,1.7});
	//SpriteEmitter4->StartSizeRange=X=(Min=16, Max=19)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter4->InitialParticlesPerSecond = 1111;
	SpriteEmitter4->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter4->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter4->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter4->StartVelocityRange=X=(Min=700, Max=800)|Y=(Min=-100, Max=100)|Z=(Min=-100, Max=100);
	//SpriteEmitter4->VelocityLossRange=X=(Min=13, Max=13)|Y=(Min=13, Max=13)|Z=(Min=13, Max=13);
	USpriteEmitter* SpriteEmitter5 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter5->UseColorScale = true;
	SpriteEmitter5->FadeOut = true;
	SpriteEmitter5->RespawnDeadParticles = false;
	SpriteEmitter5->SpinParticles = true;
	SpriteEmitter5->UseSizeScale = true;
	SpriteEmitter5->UseRegularSizeScale = false;
	SpriteEmitter5->UniformSize = true;
	SpriteEmitter5->AutomaticInitialSpawning = false;
	SpriteEmitter5->Acceleration = FVector(0, 0, -500);
	//SpriteEmitter5->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 70)});
	//SpriteEmitter5->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 85)});
	SpriteEmitter5->FadeOutStartTime = 0.5;
	SpriteEmitter5->MaxParticles = 2;
	//SpriteEmitter5->StartLocationRange=X=(Min=-32, Max=-28)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter5->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter5->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter5->SizeScale[1]=FParticleTimeScale({0.5,1.7});
	//SpriteEmitter5->StartSizeRange=X=(Min=12, Max=14)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter5->InitialParticlesPerSecond = 1111;
	SpriteEmitter5->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter5->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter5->LifetimeRange = FRange({ 1.3, 1.3 });
	//SpriteEmitter5->StartVelocityRange=X=(Min=950, Max=850)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->VelocityLossRange=X=(Min=11, Max=11)|Y=(Min=11, Max=11)|Z=(Min=11, Max=11);
	USpriteEmitter* SpriteEmitter6 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter6->UseColorScale = true;
	SpriteEmitter6->FadeOut = true;
	SpriteEmitter6->RespawnDeadParticles = false;
	SpriteEmitter6->SpinParticles = true;
	SpriteEmitter6->UseSizeScale = true;
	SpriteEmitter6->UseRegularSizeScale = false;
	SpriteEmitter6->UniformSize = true;
	SpriteEmitter6->AutomaticInitialSpawning = false;
	SpriteEmitter6->Acceleration = FVector(0, 0, -500);
	//SpriteEmitter6->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 50)});
	//SpriteEmitter6->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 55)});
	SpriteEmitter6->FadeOutStartTime = 0.5;
	SpriteEmitter6->MaxParticles = 1;
	//SpriteEmitter6->StartLocationRange=X=(Min=-30, Max=-26)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter6->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter6->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter6->SizeScale[1]=FParticleTimeScale({0.8,1.7});
	//SpriteEmitter6->StartSizeRange=X=(Min=8, Max=9)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter6->InitialParticlesPerSecond = 1111;
	SpriteEmitter6->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter6->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter6->LifetimeRange = FRange({ 1.5, 1.5 });
	//SpriteEmitter6->StartVelocityRange=X=(Min=1150, Max=1000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->VelocityLossRange=X=(Min=12, Max=12)|Y=(Min=12, Max=12)|Z=(Min=12, Max=12);
	USpriteEmitter* SpriteEmitter7 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter7->UseColorScale = true;
	SpriteEmitter7->FadeOut = true;
	SpriteEmitter7->RespawnDeadParticles = false;
	SpriteEmitter7->SpinParticles = true;
	SpriteEmitter7->UseSizeScale = true;
	SpriteEmitter7->UseRegularSizeScale = false;
	SpriteEmitter7->UniformSize = true;
	SpriteEmitter7->AutomaticInitialSpawning = false;
	SpriteEmitter7->Acceleration = FVector(0, 0, -700);
	//SpriteEmitter7->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 40)});
	//SpriteEmitter7->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 45)});
	SpriteEmitter7->FadeOutStartTime = 0.5;
	SpriteEmitter7->MaxParticles = 1;
	//SpriteEmitter7->StartLocationRange=X=(Min=-28, Max=-26)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter7->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter7->SpinsPerSecondRange=X=(Min=0.1, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter7->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter7->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter7->SizeScale[1]=FParticleTimeScale({0.4,1.7});
	//SpriteEmitter7->StartSizeRange=X=(Min=11, Max=10)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter7->InitialParticlesPerSecond = 1111;
	SpriteEmitter7->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter7->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter7->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter7->StartVelocityRange=X=(Min=1000, Max=1100)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter7->VelocityLossRange=X=(Min=10, Max=10)|Y=(Min=10, Max=10)|Z=(Min=10, Max=10);
	USpriteEmitter* SpriteEmitter8 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter8->UseColorScale = true;
	SpriteEmitter8->FadeOut = true;
	SpriteEmitter8->RespawnDeadParticles = false;
	SpriteEmitter8->SpinParticles = true;
	SpriteEmitter8->UseSizeScale = true;
	SpriteEmitter8->UseRegularSizeScale = false;
	SpriteEmitter8->UniformSize = true;
	SpriteEmitter8->AutomaticInitialSpawning = false;
	SpriteEmitter8->Acceleration = FVector(0, 0, -800);
	//SpriteEmitter8->ColorScale[0]=FParticleColorScale({0,FColor(220, 190, 175, 45)});
	//SpriteEmitter8->ColorScale[1]=FParticleColorScale({1,FColor(220, 190, 175, 50)});
	SpriteEmitter8->FadeOutStartTime = 0.5;
	SpriteEmitter8->MaxParticles = 1;
	//SpriteEmitter8->StartLocationRange=X=(Min=-28, Max=-26)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter8->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter8->SpinsPerSecondRange=X=(Min=0.1, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter8->SizeScale[1]=FParticleTimeScale({0.4,1.7});
	//SpriteEmitter8->StartSizeRange=X=(Min=10, Max=12)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter8->InitialParticlesPerSecond = 1111;
	SpriteEmitter8->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter8->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter8->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter8->StartVelocityRange=X=(Min=1100, Max=1250)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->VelocityLossRange=X=(Min=11, Max=11)|Y=(Min=11, Max=11)|Z=(Min=11, Max=11);
	USpriteEmitter* SpriteEmitter9 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter9->UseDirectionAs = EParticleDirectionUsage::PTDU_Normal;
	SpriteEmitter9->UseColorScale = true;
	SpriteEmitter9->FadeOut = true;
	SpriteEmitter9->ResetAfterChange = true;
	SpriteEmitter9->RespawnDeadParticles = false;
	SpriteEmitter9->UseSizeScale = true;
	SpriteEmitter9->UseRegularSizeScale = false;
	SpriteEmitter9->UniformSize = true;
	SpriteEmitter9->AutomaticInitialSpawning = false;
	//SpriteEmitter9->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 177)});
	//SpriteEmitter9->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 0)});
	SpriteEmitter9->FadeOutStartTime = 0.5;
	SpriteEmitter9->MaxParticles = 1;
	//SpriteEmitter9->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter9->SizeScale[1]=FParticleTimeScale({1,4});
	//SpriteEmitter9->StartSizeRange=X=(Min=9, Max=12)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter9->InitialParticlesPerSecond = 2000;
	SpriteEmitter9->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter9->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/fx2_part_waterring_Mat.fx2_part_waterring_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter9->SecondsBeforeInactive = 0;
	SpriteEmitter9->LifetimeRange = FRange({ 1, 0.9 });
	USpriteEmitter* SpriteEmitter10 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter10->UseDirectionAs = EParticleDirectionUsage::PTDU_Normal;
	SpriteEmitter10->UseColorScale = true;
	SpriteEmitter10->FadeOut = true;
	SpriteEmitter10->ResetAfterChange = true;
	SpriteEmitter10->RespawnDeadParticles = false;
	SpriteEmitter10->UseSizeScale = true;
	SpriteEmitter10->UseRegularSizeScale = false;
	SpriteEmitter10->UniformSize = true;
	SpriteEmitter10->AutomaticInitialSpawning = false;
	//SpriteEmitter10->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 177)});
	//SpriteEmitter10->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 0)});
	SpriteEmitter10->FadeOutStartTime = 0.5;
	SpriteEmitter10->MaxParticles = 1;
	//SpriteEmitter10->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter10->SizeScale[1]=FParticleTimeScale({1,4});
	//SpriteEmitter10->StartSizeRange=X=(Min=4, Max=6)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter10->InitialParticlesPerSecond = 2000;
	SpriteEmitter10->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter10->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/fx2_part_waterring_Mat.fx2_part_waterring_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter10->SecondsBeforeInactive = 0;
	SpriteEmitter10->LifetimeRange = FRange({ 1, 0.9 });
	USpriteEmitter* SpriteEmitter11 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter11->UseDirectionAs = EParticleDirectionUsage::PTDU_Normal;
	SpriteEmitter11->UseColorScale = true;
	SpriteEmitter11->FadeOut = true;
	SpriteEmitter11->ResetAfterChange = true;
	SpriteEmitter11->RespawnDeadParticles = false;
	SpriteEmitter11->UseSizeScale = true;
	SpriteEmitter11->UseRegularSizeScale = false;
	SpriteEmitter11->UniformSize = true;
	SpriteEmitter11->AutomaticInitialSpawning = false;
	//SpriteEmitter11->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 211)});
	//SpriteEmitter11->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 0)});
	SpriteEmitter11->FadeOutStartTime = 0.2;
	SpriteEmitter11->MaxParticles = 2;
	//SpriteEmitter11->StartLocationRange=X=(Min=-15, Max=15)|Y=(Min=-15, Max=15)|Z=(Min=0, Max=0);
	//SpriteEmitter11->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter11->SizeScale[1]=FParticleTimeScale({1,12});
	//SpriteEmitter11->StartSizeRange=X=(Min=0.3, Max=0.7)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter11->InitialParticlesPerSecond = 11;
	SpriteEmitter11->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter11->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/fx2_part_waterring_Mat.fx2_part_waterring_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter11->SecondsBeforeInactive = 0;
	SpriteEmitter11->LifetimeRange = FRange({ 0.3, 0.4 });
	SpriteEmitter11->InitialDelayRange = FRange({ 0.2, 0.05 });
	USpriteEmitter* SpriteEmitter12 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter12->FadeOut = true;
	SpriteEmitter12->ResetAfterChange = true;
	SpriteEmitter12->RespawnDeadParticles = false;
	SpriteEmitter12->SpinParticles = true;
	SpriteEmitter12->UniformSize = true;
	SpriteEmitter12->AutomaticInitialSpawning = false;
	SpriteEmitter12->Acceleration = FVector(0, 0, -999);
	//SpriteEmitter12->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 177)});
	//SpriteEmitter12->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 0)});
	SpriteEmitter12->FadeOutStartTime = 0.3;
	SpriteEmitter12->MaxParticles = 5;
	//SpriteEmitter12->SpinsPerSecondRange=X=(Min=0.1, Max=0.2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->StartSpinRange=X=(Min=0, Max=33000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->StartSizeRange=X=(Min=1, Max=2)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter12->InitialParticlesPerSecond = 1111;
	SpriteEmitter12->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter12->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_faint01_Mat.fx_smk_faint01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter12->SecondsBeforeInactive = 0;
	SpriteEmitter12->LifetimeRange = FRange({ 0.6, 0.6 });
	SpriteEmitter12->InitialDelayRange = FRange({ 0.2, 0.05 });
	//SpriteEmitter12->StartVelocityRange=X=(Min=-66, Max=66)|Y=(Min=-66, Max=66)|Z=(Min=111, Max=444);
	Emitters = { SpriteEmitter2,SpriteEmitter3,SpriteEmitter4,SpriteEmitter5,SpriteEmitter6,SpriteEmitter7,SpriteEmitter8,SpriteEmitter9,SpriteEmitter10,SpriteEmitter11,SpriteEmitter12 };
}