// All the original content belonged to the US Army

#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_flesh/em_bt_flesh.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"

Aem_bt_flesh::Aem_bt_flesh()
{
	USpriteEmitter* SpriteEmitter3 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter3->UseDirectionAs = EParticleDirectionUsage::PTDU_Up;
	SpriteEmitter3->UseColorScale = true;
	SpriteEmitter3->FadeOut = true;
	SpriteEmitter3->ResetAfterChange = true;
	SpriteEmitter3->RespawnDeadParticles = false;
	SpriteEmitter3->UseSizeScale = true;
	SpriteEmitter3->UseRegularSizeScale = false;
	SpriteEmitter3->AutomaticInitialSpawning = false;
	SpriteEmitter3->UseRandomSubdivision = true;
	SpriteEmitter3->Acceleration = FVector(0, 0, -950);
	//SpriteEmitter3->ColorScale[0]=FParticleColorScale({1,FColor(3, 3, 255, 0)});
	SpriteEmitter3->FadeOutStartTime = 0.5;
	SpriteEmitter3->MaxParticles = 5;
	SpriteEmitter3->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter3->SizeScale[0]=FParticleTimeScale({0,0.05});
	//SpriteEmitter3->SizeScale[1]=FParticleTimeScale({1,0.01});
	//SpriteEmitter3->StartSizeRange=X=(Min=5, Max=5)|Y=(Min=100, Max=100)|Z=(Min=150, Max=150);
	SpriteEmitter3->InitialParticlesPerSecond = 1000;
	SpriteEmitter3->DrawStyle = EParticleDrawStyle::PTDS_Modulated;
	SpriteEmitter3->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_threads_Mat.fx_part_threads_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter3->TextureUSubdivisions = 2;
	SpriteEmitter3->TextureVSubdivisions = 2;
	SpriteEmitter3->SecondsBeforeInactive = 0;
	SpriteEmitter3->LifetimeRange = FRange({ 0.1, 0.15 });
	//SpriteEmitter3->StartVelocityRange=X=(Min=100, Max=100)|Y=(Min=100, Max=-100)|Z=(Min=100, Max=-100);
	USpriteEmitter* SpriteEmitter1 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter1->FadeOut = true;
	SpriteEmitter1->FadeIn = true;
	SpriteEmitter1->RespawnDeadParticles = false;
	SpriteEmitter1->UseSizeScale = true;
	SpriteEmitter1->UseRegularSizeScale = false;
	SpriteEmitter1->UniformSize = true;
	SpriteEmitter1->AutomaticInitialSpawning = false;
	SpriteEmitter1->Acceleration = FVector(0, 0, -70);
	SpriteEmitter1->MaxParticles = 1;
	//SpriteEmitter1->SizeScale[0]=FParticleTimeScale({0.21,2});
	//SpriteEmitter1->StartSizeRange=X=(Min=5, Max=11)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter1->InitialParticlesPerSecond = 100;
	SpriteEmitter1->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter1->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_bloodmist_Mat.fx_part_bloodmist_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter1->SecondsBeforeInactive = 0;
	SpriteEmitter1->LifetimeRange = FRange({ 0.7, 0.7 });
	USpriteEmitter* SpriteEmitter9 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter9->UseColorScale = true;
	SpriteEmitter9->FadeOut = true;
	SpriteEmitter9->RespawnDeadParticles = false;
	SpriteEmitter9->SpinParticles = true;
	SpriteEmitter9->UseSizeScale = true;
	SpriteEmitter9->UseRegularSizeScale = false;
	SpriteEmitter9->UniformSize = true;
	SpriteEmitter9->AutomaticInitialSpawning = false;
	SpriteEmitter9->Acceleration = FVector(0, 0, -80);
	//SpriteEmitter9->ColorScale[0]=FParticleColorScale({0,FColor(160, 160, 160, 85)});
	//SpriteEmitter9->ColorScale[1]=FParticleColorScale({1,FColor(160, 160, 160, 80)});
	SpriteEmitter9->FadeOutStartTime = 0.1;
	SpriteEmitter9->MaxParticles = 1;
	//SpriteEmitter9->StartLocationRange=X=(Min=-3, Max=-2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter9->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter9->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter9->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter9->SizeScale[0]=FParticleTimeScale({0,0.6});
	//SpriteEmitter9->SizeScale[1]=FParticleTimeScale({0.6,1.7});
	//SpriteEmitter9->StartSizeRange=X=(Min=11, Max=13)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter9->InitialParticlesPerSecond = 1111;
	SpriteEmitter9->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter9->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball03_Mat.fx_smk_ball03_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter9->LifetimeRange = FRange({ 0.2, 0.2 });
	//SpriteEmitter9->StartVelocityRange=X=(Min=350, Max=450)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter9->VelocityLossRange=X=(Min=10, Max=10)|Y=(Min=10, Max=10)|Z=(Min=10, Max=10);
	USpriteEmitter* SpriteEmitter8 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter8->UseColorScale = true;
	SpriteEmitter8->FadeOut = true;
	SpriteEmitter8->RespawnDeadParticles = false;
	SpriteEmitter8->SpinParticles = true;
	SpriteEmitter8->UseSizeScale = true;
	SpriteEmitter8->UseRegularSizeScale = false;
	SpriteEmitter8->UniformSize = true;
	SpriteEmitter8->AutomaticInitialSpawning = false;
	SpriteEmitter8->Acceleration = FVector(0, 0, -100);
	//SpriteEmitter8->ColorScale[0]=FParticleColorScale({0,FColor(160, 160, 160, 60)});
	//SpriteEmitter8->ColorScale[1]=FParticleColorScale({1,FColor(160, 160, 160, 70)});
	SpriteEmitter8->FadeOutStartTime = 0.1;
	SpriteEmitter8->MaxParticles = 1;
	//SpriteEmitter8->StartLocationRange=X=(Min=-4, Max=-2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter8->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter8->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->SizeScale[0]=FParticleTimeScale({0,1.2});
	//SpriteEmitter8->SizeScale[1]=FParticleTimeScale({1.2,1.7});
	//SpriteEmitter8->StartSizeRange=X=(Min=11, Max=13)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter8->InitialParticlesPerSecond = 1111;
	SpriteEmitter8->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter8->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball03_Mat.fx_smk_ball03_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter8->LifetimeRange = FRange({ 0.5, 0.5 });
	//SpriteEmitter8->StartVelocityRange=X=(Min=550, Max=600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->VelocityLossRange=X=(Min=10, Max=10)|Y=(Min=10, Max=10)|Z=(Min=10, Max=10);
	USpriteEmitter* SpriteEmitter10 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter10->UseColorScale = true;
	SpriteEmitter10->FadeOut = true;
	SpriteEmitter10->RespawnDeadParticles = false;
	SpriteEmitter10->SpinParticles = true;
	SpriteEmitter10->UseSizeScale = true;
	SpriteEmitter10->UseRegularSizeScale = false;
	SpriteEmitter10->UniformSize = true;
	SpriteEmitter10->AutomaticInitialSpawning = false;
	SpriteEmitter10->Acceleration = FVector(0, 0, -200);
	//SpriteEmitter10->ColorScale[0]=FParticleColorScale({0,FColor(160, 160, 160, 25)});
	//SpriteEmitter10->ColorScale[1]=FParticleColorScale({1,FColor(160, 160, 160, 35)});
	SpriteEmitter10->FadeOutStartTime = 0.1;
	SpriteEmitter10->MaxParticles = 1;
	//SpriteEmitter10->StartLocationRange=X=(Min=-4, Max=-2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter10->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter10->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->SizeScale[0]=FParticleTimeScale({0,2});
	//SpriteEmitter10->SizeScale[1]=FParticleTimeScale({2,1.7});
	//SpriteEmitter10->StartSizeRange=X=(Min=9, Max=10)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter10->InitialParticlesPerSecond = 1111;
	SpriteEmitter10->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter10->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball03_Mat.fx_smk_ball03_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter10->LifetimeRange = FRange({ 0.7, 0.7 });
	//SpriteEmitter10->StartVelocityRange=X=(Min=600, Max=650)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->VelocityLossRange=X=(Min=10, Max=10)|Y=(Min=10, Max=10)|Z=(Min=10, Max=10);
	Emitters = { SpriteEmitter3,SpriteEmitter1,SpriteEmitter9,SpriteEmitter8,SpriteEmitter10 };

}