// All the original content belonged to the US Army

#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_cloth/em_bt_cloth.h"
#include "AA29/Object/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"

Aem_bt_cloth::Aem_bt_cloth()
{
	USpriteEmitter* SpriteEmitter2 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter2->UseColorScale = true;
	SpriteEmitter2->FadeOut = true;
	SpriteEmitter2->RespawnDeadParticles = false;
	SpriteEmitter2->UseSizeScale = true;
	SpriteEmitter2->UseRegularSizeScale = false;
	SpriteEmitter2->UniformSize = true;
	SpriteEmitter2->AutomaticInitialSpawning = false;
	SpriteEmitter2->BlendBetweenSubdivisions = true;
	//SpriteEmitter2->ColorScale[0]=FParticleColorScale({0,FColor(14, 15, 15, 0)});
	//SpriteEmitter2->ColorScale[1]=FParticleColorScale({1,FColor(0, 0, 0, 0)});
	SpriteEmitter2->FadeOutStartTime = 1.5;
	SpriteEmitter2->MaxParticles = 1;
	SpriteEmitter2->StartLocationOffset = FVector(15, 0, 0);
	SpriteEmitter2->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter2->SizeScale[0]=FParticleTimeScale({0,0.1});
	//SpriteEmitter2->SizeScale[1]=FParticleTimeScale({1,0.5});
	SpriteEmitter2->InitialParticlesPerSecond = 1000;
	SpriteEmitter2->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_smokeanim01_Mat.fx_part_smokeanim01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter2->TextureUSubdivisions = 4;
	SpriteEmitter2->TextureVSubdivisions = 2;
	SpriteEmitter2->SecondsBeforeInactive = 0;
	SpriteEmitter2->LifetimeRange = FRange({ 1.3, 2 });
	//SpriteEmitter2->StartVelocityRange=X=(Min=-25, Max=-25)|Y=(Min=-10, Max=10)|Z=(Min=-10, Max=10);
	USpriteEmitter* SpriteEmitter3 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter3->FadeOut = true;
	SpriteEmitter3->RespawnDeadParticles = false;
	SpriteEmitter3->AutoDestroy = true;
	SpriteEmitter3->SpinParticles = true;
	SpriteEmitter3->UseSizeScale = true;
	SpriteEmitter3->UniformSize = true;
	SpriteEmitter3->AutomaticInitialSpawning = false;
	SpriteEmitter3->BlendBetweenSubdivisions = true;
	SpriteEmitter3->Acceleration = FVector(0, 0, -100);
	SpriteEmitter3->FadeOutStartTime = 0.2;
	SpriteEmitter3->MaxParticles = 3;
	SpriteEmitter3->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter3->SpinsPerSecondRange=X=(Min=-2, Max=3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->StartSpinRange=X=(Min=0, Max=32000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter3->SizeScale[1]=FParticleTimeScale({0.5,1});
	//SpriteEmitter3->SizeScale[2]=FParticleTimeScale({1,0.1});
	//SpriteEmitter3->StartSizeRange=X=(Min=1, Max=2)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter3->InitialParticlesPerSecond = 5000;
	SpriteEmitter3->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter3->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_woodchip_Mat.fx_part_woodchip_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter3->TextureUSubdivisions = 4;
	SpriteEmitter3->TextureVSubdivisions = 4;
	SpriteEmitter3->SecondsBeforeInactive = 0;
	SpriteEmitter3->LifetimeRange = FRange({ 0.8, 0.5 });
	//SpriteEmitter3->StartVelocityRange=X=(Min=300, Max=200)|Y=(Min=-100, Max=150)|Z=(Min=-100, Max=150);
	//SpriteEmitter3->VelocityLossRange=X=(Min=5, Max=5)|Y=(Min=5, Max=5)|Z=(Min=5, Max=5);
	USpriteEmitter* SpriteEmitter4 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter4->UseColorScale = true;
	SpriteEmitter4->FadeOut = true;
	SpriteEmitter4->RespawnDeadParticles = false;
	SpriteEmitter4->SpinParticles = true;
	SpriteEmitter4->UseSizeScale = true;
	SpriteEmitter4->UseRegularSizeScale = false;
	SpriteEmitter4->UniformSize = true;
	SpriteEmitter4->AutomaticInitialSpawning = false;
	SpriteEmitter4->Acceleration = FVector(0, 0, -100);
	//SpriteEmitter4->ColorScale[0]=FParticleColorScale({0,FColor(71, 94, 103, 70)});
	//SpriteEmitter4->ColorScale[1]=FParticleColorScale({1,FColor(96, 134, 157, 65)});
	SpriteEmitter4->FadeOutStartTime = 0.5;
	SpriteEmitter4->MaxParticles = 1;
	//SpriteEmitter4->StartLocationRange=X=(Min=-3, Max=-3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter4->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter4->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter4->SizeScale[1]=FParticleTimeScale({1,1.7});
	//SpriteEmitter4->StartSizeRange=X=(Min=10, Max=12)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter4->InitialParticlesPerSecond = 1111;
	SpriteEmitter4->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter4->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter4->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter4->StartVelocityRange=X=(Min=350, Max=370)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->VelocityLossRange=X=(Min=15, Max=15)|Y=(Min=15, Max=15)|Z=(Min=15, Max=15);
	USpriteEmitter* SpriteEmitter5 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter5->UseColorScale = true;
	SpriteEmitter5->FadeOut = true;
	SpriteEmitter5->RespawnDeadParticles = false;
	SpriteEmitter5->SpinParticles = true;
	SpriteEmitter5->UseSizeScale = true;
	SpriteEmitter5->UseRegularSizeScale = false;
	SpriteEmitter5->UniformSize = true;
	SpriteEmitter5->AutomaticInitialSpawning = false;
	SpriteEmitter5->Acceleration = FVector(0, 0, -100);
	//SpriteEmitter5->ColorScale[0]=FParticleColorScale({0,FColor(142, 167, 181, 55)});
	//SpriteEmitter5->ColorScale[1]=FParticleColorScale({1,FColor(142, 167, 181, 45)});
	SpriteEmitter5->FadeOutStartTime = 0.7;
	SpriteEmitter5->MaxParticles = 1;
	//SpriteEmitter5->StartLocationRange=X=(Min=-4, Max=-2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter5->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter5->SpinsPerSecondRange=X=(Min=0.2, Max=0.3)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter5->SizeScale[1]=FParticleTimeScale({1,1.7});
	//SpriteEmitter5->StartSizeRange=X=(Min=13, Max=16)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter5->InitialParticlesPerSecond = 1111;
	SpriteEmitter5->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter5->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter5->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter5->StartVelocityRange=X=(Min=610, Max=630)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->VelocityLossRange=X=(Min=15, Max=15)|Y=(Min=15, Max=15)|Z=(Min=15, Max=15);
	USpriteEmitter* SpriteEmitter6 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter6->UseColorScale = true;
	SpriteEmitter6->FadeOut = true;
	SpriteEmitter6->RespawnDeadParticles = false;
	SpriteEmitter6->SpinParticles = true;
	SpriteEmitter6->UseSizeScale = true;
	SpriteEmitter6->UseRegularSizeScale = false;
	SpriteEmitter6->UniformSize = true;
	SpriteEmitter6->AutomaticInitialSpawning = false;
	SpriteEmitter6->Acceleration = FVector(0, 0, -100);
	//SpriteEmitter6->ColorScale[0]=FParticleColorScale({0,FColor(154, 163, 167, 30)});
	//SpriteEmitter6->ColorScale[1]=FParticleColorScale({1,FColor(154, 163, 167, 25)});
	SpriteEmitter6->FadeOutStartTime = 1;
	SpriteEmitter6->MaxParticles = 1;
	//SpriteEmitter6->StartLocationRange=X=(Min=-4, Max=-2)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter6->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter6->SpinsPerSecondRange=X=(Min=0.1, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter6->SizeScale[1]=FParticleTimeScale({1,1.7});
	//SpriteEmitter6->StartSizeRange=X=(Min=18, Max=22)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter6->InitialParticlesPerSecond = 1111;
	SpriteEmitter6->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter6->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter6->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter6->StartVelocityRange=X=(Min=670, Max=750)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->VelocityLossRange=X=(Min=15, Max=15)|Y=(Min=15, Max=15)|Z=(Min=15, Max=15);
	Emitters = { nullptr,SpriteEmitter2,SpriteEmitter3,SpriteEmitter4,SpriteEmitter5,SpriteEmitter6 };

}
