// All the original content belonged to the US Army


#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_BDMexplosion/em_bt_BDMexplosion.h"
#include "AA29/Object/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"
#include "AA29/Object/ParticleEmitter/MeshEmitter/MeshEmitter.h"

Aem_bt_BDMexplosion::Aem_bt_BDMexplosion()
{
	UMeshEmitter* MeshEmitter0 = NewObject<UMeshEmitter>(UMeshEmitter::StaticClass());
	MeshEmitter0->StaticMesh = LoadObject<UStaticMesh>(NULL, TEXT("StaticMesh'/Game/AmericasArmy/Meshes/M_AA2_FX/Particles/fx_part_con_chunk1.fx_part_con_chunk1'"), NULL, LOAD_None, NULL);
	MeshEmitter0->UseCollision = true;
	MeshEmitter0->UseMaxCollisions = true;
	MeshEmitter0->RespawnDeadParticles = false;
	MeshEmitter0->AutoDestroy = true;
	MeshEmitter0->AutomaticInitialSpawning = false;
	MeshEmitter0->Acceleration = FVector(0, 0, -700);
	//MeshEmitter0->DampingFactorRange=X=(Min=0.6, Max=0.6)|Y=(Min=0.6, Max=0.6)|Z=(Min=0.2, Max=0.2);
	MeshEmitter0->MaxCollisions = FRange({ 2, 2 });
	MeshEmitter0->MaxParticles = 5;
	MeshEmitter0->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//MeshEmitter0->StartSizeRange=X=(Min=0.25, Max=0.25)|Y=(Min=0.25, Max=0.25)|Z=(Min=0.25, Max=0.25);
	MeshEmitter0->InitialParticlesPerSecond = 500;
	MeshEmitter0->SecondsBeforeInactive = 0;
	MeshEmitter0->LifetimeRange = FRange({ 1.6, 2 });
	//MeshEmitter0->StartVelocityRange=X=(Min=-1000, Max=-1100)|Y=(Min=-800, Max=800)|Z=(Min=-800, Max=800);
	USpriteEmitter* SpriteEmitter1 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter1->UseColorScale = true;
	SpriteEmitter1->FadeOut = true;
	SpriteEmitter1->RespawnDeadParticles = false;
	SpriteEmitter1->SpinParticles = true;
	SpriteEmitter1->UseSizeScale = true;
	SpriteEmitter1->UseRegularSizeScale = false;
	SpriteEmitter1->UniformSize = true;
	SpriteEmitter1->AutomaticInitialSpawning = false;
	SpriteEmitter1->Acceleration = FVector(0, 0, -111);
	//SpriteEmitter1->ColorScale[0]=FParticleColorScale({0,FColor(56, 69, 80, 255)});
	//SpriteEmitter1->ColorScale[1]=FParticleColorScale({0.5,FColor(127, 127, 127, 177)});
	//SpriteEmitter1->ColorScale[2]=FParticleColorScale({1,FColor(200, 200, 200, 225)});
	SpriteEmitter1->MaxParticles = 150;
	SpriteEmitter1->AddLocationFromOtherEmitter = 0;
	//SpriteEmitter1->SpinsPerSecondRange=X=(Min=0.2, Max=0.4)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter1->StartSpinRange=X=(Min=300, Max=-300)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter1->SizeScale[0]=FParticleTimeScale({1,2.5});
	//SpriteEmitter1->StartSizeRange=X=(Min=20, Max=20)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter1->InitialParticlesPerSecond = 130;
	SpriteEmitter1->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter1->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball04_Mat.fx_smk_ball04_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter1->SecondsBeforeInactive = 0;
	SpriteEmitter1->LifetimeRange = FRange({ 1.3, 1 });
	SpriteEmitter1->InitialDelayRange = FRange({ 0.1, 0.1 });
	USpriteEmitter* SpriteEmitter2 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter2->UseColorScale = true;
	SpriteEmitter2->FadeOut = true;
	SpriteEmitter2->FadeIn = true;
	SpriteEmitter2->RespawnDeadParticles = false;
	SpriteEmitter2->SpinParticles = true;
	SpriteEmitter2->DampRotation = true;
	SpriteEmitter2->UseSizeScale = true;
	SpriteEmitter2->UseRegularSizeScale = false;
	SpriteEmitter2->UniformSize = true;
	SpriteEmitter2->AutomaticInitialSpawning = false;
	SpriteEmitter2->Acceleration = FVector(0, 0, -200);
	//SpriteEmitter2->ColorScale[0]=FParticleColorScale({0,FColor(35, 35, 35, 255)});
	//SpriteEmitter2->ColorScale[1]=FParticleColorScale({0.1,FColor(94, 158, 255, 255)});
	//SpriteEmitter2->ColorScale[2]=FParticleColorScale({0.3,FColor(190, 190, 190, 255)});
	//SpriteEmitter2->ColorScale[3]=FParticleColorScale({1,FColor(220, 220, 220, 255)});
	SpriteEmitter2->FadeOutStartTime = 0.5;
	SpriteEmitter2->FadeInEndTime = 0.5;
	//SpriteEmitter2->StartLocationRange=X=(Min=-10, Max=10)|Y=(Min=-10, Max=10)|Z=(Min=0, Max=0);
	SpriteEmitter2->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter2->SpinsPerSecondRange=X=(Min=0.2, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter2->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter2->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter2->SizeScale[1]=FParticleTimeScale({7,20});
	//SpriteEmitter2->StartSizeRange=X=(Min=100, Max=70)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter2->InitialParticlesPerSecond = 999;
	SpriteEmitter2->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter2->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_drt_cloud01_Mat.fx_drt_cloud01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter2->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter2->StartVelocityRange=X=(Min=-711, Max=-455)|Y=(Min=-1499, Max=1499)|Z=(Min=-1499, Max=1499);
	//SpriteEmitter2->VelocityLossRange=X=(Min=3, Max=3)|Y=(Min=13, Max=13)|Z=(Min=13, Max=13);
	USpriteEmitter* SpriteEmitter3 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter3->FadeOut = true;
	SpriteEmitter3->FadeIn = true;
	SpriteEmitter3->RespawnDeadParticles = false;
	SpriteEmitter3->SpinParticles = true;
	SpriteEmitter3->UseSizeScale = true;
	SpriteEmitter3->UseRegularSizeScale = false;
	SpriteEmitter3->UniformSize = true;
	SpriteEmitter3->AutomaticInitialSpawning = false;
	SpriteEmitter3->Acceleration = FVector(0, 0, -600);
	SpriteEmitter3->FadeOutStartTime = 0.5;
	SpriteEmitter3->FadeInEndTime = 0.3;
	SpriteEmitter3->MaxParticles = 4;
	//SpriteEmitter3->StartLocationRange=X=(Min=-30, Max=30)|Y=(Min=-30, Max=30)|Z=(Min=0, Max=0);
	SpriteEmitter3->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter3->SpinsPerSecondRange=X=(Min=0, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter3->SizeScale[1]=FParticleTimeScale({8,25});
	//SpriteEmitter3->StartSizeRange=X=(Min=50, Max=80)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter3->InitialParticlesPerSecond = 99;
	SpriteEmitter3->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter3->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/FX2_Parts_Dirtclumps_Large_Mat.FX2_Parts_Dirtclumps_Large_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter3->LifetimeRange = FRange({ 1, 2 });
	//SpriteEmitter3->StartVelocityRange=X=(Min=-950, Max=-1250)|Y=(Min=500, Max=-500)|Z=(Min=500, Max=-500);
	//SpriteEmitter3->VelocityLossRange=X=(Min=14, Max=14)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter4 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter4->FadeOut = true;
	SpriteEmitter4->RespawnDeadParticles = false;
	SpriteEmitter4->SpinParticles = true;
	SpriteEmitter4->UseSizeScale = true;
	SpriteEmitter4->UseRegularSizeScale = false;
	SpriteEmitter4->UniformSize = true;
	SpriteEmitter4->AutomaticInitialSpawning = false;
	SpriteEmitter4->BlendBetweenSubdivisions = true;
	SpriteEmitter4->FadeOutStartTime = 0.4;
	SpriteEmitter4->FadeInEndTime = 0.2;
	SpriteEmitter4->MaxParticles = 1;
	//SpriteEmitter4->StartLocationRange=X=(Min=-44, Max=-44)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter4->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter4->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter4->SizeScale[1]=FParticleTimeScale({0.3,1.7});
	//SpriteEmitter4->SizeScale[2]=FParticleTimeScale({1,1.5});
	//SpriteEmitter4->StartSizeRange=X=(Min=149, Max=169)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter4->InitialParticlesPerSecond = 55;
	SpriteEmitter4->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter4->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_explosion01_Mat.fx_part_explosion01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter4->TextureUSubdivisions = 4;
	SpriteEmitter4->TextureVSubdivisions = 2;
	SpriteEmitter4->LifetimeRange = FRange({ 0.6, 0.9 });
	//SpriteEmitter4->StartVelocityRange=X=(Min=-333, Max=-333)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->VelocityLossRange=X=(Min=2, Max=2)|Y=(Min=2, Max=2)|Z=(Min=2, Max=2);
	USpriteEmitter* SpriteEmitter5 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter5->FadeOut = true;
	SpriteEmitter5->RespawnDeadParticles = false;
	SpriteEmitter5->SpinParticles = true;
	SpriteEmitter5->UseSizeScale = true;
	SpriteEmitter5->UseRegularSizeScale = false;
	SpriteEmitter5->UniformSize = true;
	SpriteEmitter5->AutomaticInitialSpawning = false;
	SpriteEmitter5->BlendBetweenSubdivisions = true;
	SpriteEmitter5->FadeOutStartTime = 0.4;
	SpriteEmitter5->FadeInEndTime = 0.3;
	SpriteEmitter5->MaxParticles = 2;
	SpriteEmitter5->StartLocationOffset = FVector(0, 0, 100);
	//SpriteEmitter5->StartLocationRange=X=(Min=-44, Max=-44)|Y=(Min=-44, Max=44)|Z=(Min=-44, Max=44);
	SpriteEmitter5->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter5->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter5->SizeScale[1]=FParticleTimeScale({1,4.1});
	//SpriteEmitter5->StartSizeRange=X=(Min=80, Max=85)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter5->InitialParticlesPerSecond = 55;
	SpriteEmitter5->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter5->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_explosion01_Mat.fx_part_explosion01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter5->TextureUSubdivisions = 4;
	SpriteEmitter5->TextureVSubdivisions = 2;
	SpriteEmitter5->LifetimeRange = FRange({ 0.07, 0.1 });
	SpriteEmitter5->InitialDelayRange = FRange({ 0.5, 0.1 });
	USpriteEmitter* SpriteEmitter6 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter6->FadeOut = true;
	SpriteEmitter6->RespawnDeadParticles = false;
	SpriteEmitter6->SpinParticles = true;
	SpriteEmitter6->UseSizeScale = true;
	SpriteEmitter6->UseRegularSizeScale = false;
	SpriteEmitter6->UniformSize = true;
	SpriteEmitter6->AutomaticInitialSpawning = false;
	SpriteEmitter6->BlendBetweenSubdivisions = true;
	SpriteEmitter6->FadeOutStartTime = 0.4;
	SpriteEmitter6->FadeInEndTime = 0.3;
	SpriteEmitter6->MaxParticles = 2;
	SpriteEmitter6->StartLocationOffset = FVector(0, 0, -100);
	//SpriteEmitter6->StartLocationRange=X=(Min=44, Max=44)|Y=(Min=-44, Max=44)|Z=(Min=-44, Max=44);
	SpriteEmitter6->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter6->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter6->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter6->SizeScale[1]=FParticleTimeScale({1,2.1});
	//SpriteEmitter6->StartSizeRange=X=(Min=120, Max=135)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter6->InitialParticlesPerSecond = 55;
	SpriteEmitter6->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter6->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_explosion01_Mat.fx_part_explosion01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter6->TextureUSubdivisions = 4;
	SpriteEmitter6->TextureVSubdivisions = 2;
	SpriteEmitter6->LifetimeRange = FRange({ 0.5, 0.8 });
	SpriteEmitter6->InitialDelayRange = FRange({ 0.1, 0.1 });
	USpriteEmitter* SpriteEmitter7 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter7->UseCollision = true;
	SpriteEmitter7->UseMaxCollisions = true;
	SpriteEmitter7->UseColorScale = true;
	SpriteEmitter7->FadeOut = true;
	SpriteEmitter7->RespawnDeadParticles = false;
	SpriteEmitter7->UseSizeScale = true;
	SpriteEmitter7->UseRegularSizeScale = false;
	SpriteEmitter7->UniformSize = true;
	SpriteEmitter7->AutomaticInitialSpawning = false;
	SpriteEmitter7->Acceleration = FVector(0, 0, -1111);
	//SpriteEmitter7->DampingFactorRange=X=(Min=0.6, Max=0.6)|Y=(Min=0.6, Max=0.6)|Z=(Min=0.2, Max=0.2);
	SpriteEmitter7->MaxCollisions = FRange({ 1, 3 });
	//SpriteEmitter7->ColorScale[0]=FParticleColorScale({0,FColor(140, 194, 255, 0)});
	//SpriteEmitter7->ColorScale[1]=FParticleColorScale({1,FColor(38, 57, 89, 0)});
	SpriteEmitter7->FadeOutStartTime = 0.5;
	SpriteEmitter7->MaxParticles = 60;
	//SpriteEmitter7->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter7->SizeScale[1]=FParticleTimeScale({1,0.8});
	//SpriteEmitter7->StartSizeRange=X=(Min=5, Max=7)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter7->InitialParticlesPerSecond = 1111;
	SpriteEmitter7->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter7->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Corona/fx2_cor_05_Mat.fx2_cor_05_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter7->LifetimeRange = FRange({ 2.2, 2.7 });
	//SpriteEmitter7->StartVelocityRange=X=(Min=-2111, Max=1511)|Y=(Min=-1111, Max=1111)|Z=(Min=-222, Max=1111);
	//SpriteEmitter7->VelocityLossRange=X=(Min=1, Max=1)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter8 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter8->UseColorScale = true;
	SpriteEmitter8->FadeOut = true;
	SpriteEmitter8->RespawnDeadParticles = false;
	SpriteEmitter8->UseSizeScale = true;
	SpriteEmitter8->UseRegularSizeScale = false;
	SpriteEmitter8->UniformSize = true;
	SpriteEmitter8->AutomaticInitialSpawning = false;
	SpriteEmitter8->Acceleration = FVector(0, 0, -977);
	//SpriteEmitter8->ColorScale[0]=FParticleColorScale({0,FColor(140, 194, 255, 0)});
	//SpriteEmitter8->ColorScale[1]=FParticleColorScale({1,FColor(38, 57, 89, 0)});
	SpriteEmitter8->FadeOutStartTime = 0.5;
	SpriteEmitter8->MaxParticles = 200;
	SpriteEmitter8->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter8->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter8->SizeScale[1]=FParticleTimeScale({1,0.8});
	//SpriteEmitter8->StartSizeRange=X=(Min=5, Max=7)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter8->InitialParticlesPerSecond = 1111;
	SpriteEmitter8->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter8->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Corona/fx2_cor_05_Mat.fx2_cor_05_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter8->LifetimeRange = FRange({ 2.2, 2.7 });
	//SpriteEmitter8->StartVelocityRange=X=(Min=-1055, Max=-1855)|Y=(Min=-1022, Max=1022)|Z=(Min=-1022, Max=1022);
	//SpriteEmitter8->VelocityLossRange=X=(Min=4, Max=2)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter9 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter9->RespawnDeadParticles = false;
	SpriteEmitter9->SpinParticles = true;
	SpriteEmitter9->UseRegularSizeScale = false;
	SpriteEmitter9->UniformSize = true;
	SpriteEmitter9->AutomaticInitialSpawning = false;
	SpriteEmitter9->MaxParticles = 1;
	//SpriteEmitter9->StartSpinRange=X=(Min=32600, Max=0)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter9->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter9->SizeScale[1]=FParticleTimeScale({1,3});
	//SpriteEmitter9->StartSizeRange=X=(Min=222, Max=222)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter9->InitialParticlesPerSecond = 55;
	SpriteEmitter9->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter9->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_particle_startblast01_Mat.fx_particle_startblast01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter9->LifetimeRange = FRange({ 0.05, 0.05 });
	USpriteEmitter* SpriteEmitter10 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter10->UseColorScale = true;
	SpriteEmitter10->FadeOut = true;
	SpriteEmitter10->FadeIn = true;
	SpriteEmitter10->RespawnDeadParticles = false;
	SpriteEmitter10->SpinParticles = true;
	SpriteEmitter10->UseSizeScale = true;
	SpriteEmitter10->UseRegularSizeScale = false;
	SpriteEmitter10->UniformSize = true;
	SpriteEmitter10->Acceleration = FVector(5, 0, 0);
	//SpriteEmitter10->ColorScale[0]=FParticleColorScale({0,FColor(30, 30, 30, 255)});
	//SpriteEmitter10->ColorScale[1]=FParticleColorScale({1,FColor(226, 226, 226, 255)});
	SpriteEmitter10->FadeOutStartTime = 1;
	SpriteEmitter10->FadeInEndTime = 0.5;
	SpriteEmitter10->MaxParticles = 30;
	SpriteEmitter10->StartLocationOffset = FVector(0, 0, -30);
	//SpriteEmitter10->StartLocationRange=X=(Min=-100, Max=100)|Y=(Min=-100, Max=100)|Z=(Min=0, Max=0);
	SpriteEmitter10->SpinCCWorCW = FVector(0.25, 0.75, 0.5);
	//SpriteEmitter10->SpinsPerSecondRange=X=(Min=0.03, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->StartSpinRange=X=(Min=0, Max=32000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter10->SizeScale[1]=FParticleTimeScale({5,13});
	//SpriteEmitter10->StartSizeRange=X=(Min=115, Max=137)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter10->InitialParticlesPerSecond = 1111;
	SpriteEmitter10->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter10->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball02_Mat.fx_smk_ball02_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter10->TextureUSubdivisions = 1;
	SpriteEmitter10->TextureVSubdivisions = 1;
	SpriteEmitter10->LifetimeRange = FRange({ 5, 7 });
	//SpriteEmitter10->StartVelocityRange=X=(Min=-5, Max=5)|Y=(Min=-5, Max=5)|Z=(Min=90, Max=75);
	//SpriteEmitter10->fWindFactor = 3;
	USpriteEmitter* SpriteEmitter11 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter11->FadeOut = true;
	SpriteEmitter11->FadeIn = true;
	SpriteEmitter11->RespawnDeadParticles = false;
	SpriteEmitter11->SpinParticles = true;
	SpriteEmitter11->UseSizeScale = true;
	SpriteEmitter11->UseRegularSizeScale = false;
	SpriteEmitter11->UniformSize = true;
	SpriteEmitter11->AutomaticInitialSpawning = false;
	SpriteEmitter11->Acceleration = FVector(0, 0, -400);
	SpriteEmitter11->FadeOutStartTime = 0.5;
	SpriteEmitter11->FadeInEndTime = 0.3;
	SpriteEmitter11->MaxParticles = 3;
	//SpriteEmitter11->StartLocationRange=X=(Min=0, Max=0)|Y=(Min=0, Max=0)|Z=(Min=-20, Max=-12);
	SpriteEmitter11->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter11->SpinsPerSecondRange=X=(Min=0, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter11->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter11->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter11->SizeScale[1]=FParticleTimeScale({5,30});
	//SpriteEmitter11->StartSizeRange=X=(Min=50, Max=70)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter11->InitialParticlesPerSecond = 99;
	SpriteEmitter11->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter11->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/FX2_Parts_Dirtclumps_Large_Mat.FX2_Parts_Dirtclumps_Large_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter11->LifetimeRange = FRange({ 1, 1.5 });
	//SpriteEmitter11->StartVelocityRange=X=(Min=-300, Max=-550)|Y=(Min=500, Max=-500)|Z=(Min=500, Max=-500);
	//SpriteEmitter11->VelocityLossRange=X=(Min=7, Max=7)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter12 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter12->UseColorScale = true;
	SpriteEmitter12->FadeOut = true;
	SpriteEmitter12->RespawnDeadParticles = false;
	SpriteEmitter12->SpinParticles = true;
	SpriteEmitter12->UseSizeScale = true;
	SpriteEmitter12->UseRegularSizeScale = false;
	SpriteEmitter12->UniformSize = true;
	SpriteEmitter12->AutomaticInitialSpawning = false;
	SpriteEmitter12->Acceleration = FVector(0, 0, 100);
	//SpriteEmitter12->ColorScale[0]=FParticleColorScale({0,FColor(142, 150, 157, 175)});
	//SpriteEmitter12->ColorScale[1]=FParticleColorScale({1,FColor(142, 150, 157, 150)});
	SpriteEmitter12->FadeOutStartTime = 0.5;
	SpriteEmitter12->MaxParticles = 8;
	SpriteEmitter12->StartLocationOffset = FVector(0, 0, -30);
	//SpriteEmitter12->StartLocationRange=X=(Min=-80, Max=80)|Y=(Min=-80, Max=80)|Z=(Min=0, Max=0);
	SpriteEmitter12->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter12->SpinsPerSecondRange=X=(Min=0.1, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter12->SizeScale[1]=FParticleTimeScale({5,15});
	//SpriteEmitter12->StartSizeRange=X=(Min=65, Max=80)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter12->InitialParticlesPerSecond = 1111;
	SpriteEmitter12->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter12->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/FX_dust_hitA_Mat.FX_dust_hitA_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter12->LifetimeRange = FRange({ 1, 1.5 });
	//SpriteEmitter12->StartVelocityRange=X=(Min=-1200, Max=-600)|Y=(Min=600, Max=-600)|Z=(Min=600, Max=-600);
	//SpriteEmitter12->VelocityLossRange=X=(Min=7, Max=3)|Y=(Min=2, Max=2)|Z=(Min=2, Max=2);
	Emitters = { MeshEmitter0,SpriteEmitter1,SpriteEmitter2,SpriteEmitter3,SpriteEmitter4,SpriteEmitter5,SpriteEmitter6,SpriteEmitter7,SpriteEmitter8,SpriteEmitter9,SpriteEmitter10,SpriteEmitter11,SpriteEmitter12 };
}

void Aem_bt_BDMexplosion::PostBeginPlay()
{
	SpawnLight();
}

void Aem_bt_BDMexplosion::SpawnLight()
{
	//Spawn(class'AGP_Effects.aux_light_ExpLightB');
}

void Aem_bt_BDMexplosion::BeginPlay()
{
	//MeshEmitter(Emitters[0]).StaticMesh = StaticMesh(DynamicLoadObject("M_AA2_FX.Particles.fx_part_con_chunk1", Class'StaticMesh'));
}

