// All the original content belonged to the US Army

#pragma once

#include "CoreMinimal.h"
#include "AA29/Object/Actor/EventLab/EventLab.h"
#include "EL_ES2McKenna.generated.h"

class APickup;
class ADoorTrigger;
class AMover;
class AAGP_Character_NPC;
class ATrigger;
class ATextDisplay;
class AAGP_DumbEndPoint;

UCLASS()
class AEL_ES2McKenna : public AEventLab
{
	GENERATED_BODY()
public:
	AEL_ES2McKenna();

	UPROPERTY()   FName aarAnimName;						// var name aarAnimName;
	UPROPERTY()   int32 InstructorAnimNum;					// var int InstructorAnimNum;
	UPROPERTY()   bool bRestartls6;							// var bool bRestartls6;
	UPROPERTY()   bool bDonels6;							// var bool bDonels6;
	UPROPERTY()   bool bHaveNotMoved;						// var bool bHaveNotMoved;
	UPROPERTY()   bool bWarnedPlay;							// var bool bWarnedPlay;
	UPROPERTY()   bool bLastViolation;						// var bool bLastViolation;
	UPROPERTY()   bool bWarned;								// var bool bWarned;
	UPROPERTY()   FRotator PlayerRotation;					// var Object.Rotator PlayerRotation;
	UPROPERTY()   FVector PlayerLocation;					// var FVector PlayerLocation;
	UPROPERTY()   AAGP_DumbEndPoint* aarLocation;			// var AGP_Gameplay.AGP_DumbEndPoint aarLocation;
	UPROPERTY()   bool bbuilding6Flipped;					// var bool bbuilding6Flipped;
	UPROPERTY()   bool bbuilding5Flipped;					// var bool bbuilding5Flipped;
	UPROPERTY()   bool bbuilding4DoorFlipped;				// var bool bbuilding4DoorFlipped;
	UPROPERTY()   bool bbuilding3Door3Flipped;				// var bool bbuilding3Door3Flipped;
	UPROPERTY()   bool bbuilding2Door2Flipped;				// var bool bbuilding2Door2Flipped;
	UPROPERTY()   bool bbuilding2Door1Flipped;				// var bool bbuilding2Door1Flipped;
	UPROPERTY()   bool bbuilding1Door2Flipped;				// var bool bbuilding1Door2Flipped;
	UPROPERTY()   bool bbuilding1Door1Flipped;				// var bool bbuilding1Door1Flipped;
	UPROPERTY()   bool building6MTTriggerCaptured;			// var bool building6MTTriggerCaptured;
	UPROPERTY()   bool building5MTTriggerCaptured;			// var bool building5MTTriggerCaptured;
	UPROPERTY()   bool building4MTTriggerCaptured;			// var bool building4MTTriggerCaptured;
	UPROPERTY()   bool building3MTTriggerCaptured;			// var bool building3MTTriggerCaptured;
	UPROPERTY()   bool building2MTTriggerCaptured;			// var bool building2MTTriggerCaptured;
	UPROPERTY()   bool building1MTTriggerCaptured;			// var bool building1MTTriggerCaptured;
	UPROPERTY()   int32 ES2ObjectsPassed;					// var int ES2ObjectsPassed;
	UPROPERTY()   int32 TotalES2ObjectinLevel;				// var int TotalES2ObjectinLevel;
	UPROPERTY()   int32 ES2Score;							// var int ES2Score;
	UPROPERTY()   int32 ES2objectsFound;					// var int ES2objectsFound;
	UPROPERTY()   bool bAllMTTriggersDisabled;				// var bool bAllMTTriggersDisabled;
	UPROPERTY()   bool bOutdoorIEDTriggered;				// var bool bOutdoorIEDTriggered;
	UPROPERTY()   bool bIndoorIEDTriggered;					// var bool bIndoorIEDTriggered;
	UPROPERTY()   bool bSecondFriendlyHit;					// var bool bSecondFriendlyHit;
	UPROPERTY()   bool courseEntered;						// var bool courseEntered;
	UPROPERTY()   float keepMovingIdleTime;					// var float keepMovingIdleTime;
	UPROPERTY()   float preTimerPause;						// var float preTimerPause;
	UPROPERTY()   bool bPlayedEntranceVO;					// var bool bPlayedEntranceVO;
	UPROPERTY()   bool bPlayedNoWeapVO;						// var bool bPlayedNoWeapVO;
	UPROPERTY()   float TargetFlipModifier;					// var float TargetFlipModifier;
	UPROPERTY()   float FlashTimerDelay;					// var float FlashTimerDelay;
	UPROPERTY()   float Accuracy;							// var float Accuracy;
	UPROPERTY()   bool bNoSecurityViolation;				// var bool bNoSecurityViolation;
	UPROPERTY()   bool bCanRunOutOfAmmo;					// var bool bCanRunOutOfAmmo;
	UPROPERTY()   bool bFlashed;							// var bool bFlashed;
	UPROPERTY()   int32 AmmoFadeTime;						// var int AmmoFadeTime;
	UPROPERTY()   FString sWeaponAtCompletion;				// var string sWeaponAtCompletion;
	UPROPERTY()   float aarReportDelay;						// var float aarReportDelay;
	UPROPERTY()   FString dataUrl;							// var string dataUrl;
	UPROPERTY()   FString newTimer;							// var string newTimer;
	UPROPERTY()   FString UserName;							// var string UserName;
	UPROPERTY()   FString dateToday;						// var string dateToday;
	UPROPERTY()   int32 goNoGo;								// var int goNoGo;
	UPROPERTY()   FString finalNoGo;						// var string finalNoGo;
	UPROPERTY()   FString finalGo;							// var string finalGo;
	UPROPERTY()   int32 opforRunningCount;					// var int opforRunningCount;
	UPROPERTY()   int32 targetC;							// var int targetC;
	UPROPERTY()   int32 targetB;							// var int targetB;
	UPROPERTY()   int32 targetA;							// var int targetA;
	UPROPERTY()   float timeKeeper;							// var float timeKeeper;
	UPROPERTY()   float TimeRemaining;						// var float TimeRemaining;
	UPROPERTY()   int32 timeOverallScore;					// var int timeOverallScore;
	UPROPERTY()   FString timeOverall;						// var string timeOverall;
	UPROPERTY()   int32 TotalScore;							// var int TotalScore;
	UPROPERTY()   int32 friendlyHitScore;					// var int friendlyHitScore;
	UPROPERTY()   int32 friendlyHit;						// var int friendlyHit;
	UPROPERTY()   bool bopforScoreDoubled;					// var bool bopforScoreDoubled;
	UPROPERTY()   int32 opforHitScore;						// var int opforHitScore;
	UPROPERTY()   int32 opforHit;							// var int opforHit;
	UPROPERTY()   int32 roundsRemaining;					// var int roundsRemaining;
	UPROPERTY()   int32 accuracyScore;						// var int accuracyScore;
	UPROPERTY()   int32 roundsFired;						// var int roundsFired;
	UPROPERTY()   bool bIntroed;							// var bool bIntroed;
	UPROPERTY()   bool interrupt2;							// var bool interrupt2;
	UPROPERTY()   bool door4Entered;						// var bool door4Entered;
	UPROPERTY()   bool door3Entered;						// var bool door3Entered;
	UPROPERTY()   bool door2Entered;						// var bool door2Entered;
	UPROPERTY()   bool door1Entered;						// var bool door1Entered;
	UPROPERTY()   AMarksmanTarget* building6M14Target2;		// var AGP_Gameplay.MarksmanTarget building6M14Target2;
	UPROPERTY()   AMarksmanTarget* building6M14Target1;		// var AGP_Gameplay.MarksmanTarget building6M14Target1;
	UPROPERTY()   AMarksmanTarget* building6M13Target6;		// var AGP_Gameplay.MarksmanTarget building6M13Target6;
	UPROPERTY()   AMarksmanTarget* building6M13Target5;		// var AGP_Gameplay.MarksmanTarget building6M13Target5;
	UPROPERTY()   AMarksmanTarget* building6M13Target4;		// var AGP_Gameplay.MarksmanTarget building6M13Target4;
	UPROPERTY()   AMarksmanTarget* building6M13Target3;		// var AGP_Gameplay.MarksmanTarget building6M13Target3;
	UPROPERTY()   AMarksmanTarget* building6M13Target2;		// var AGP_Gameplay.MarksmanTarget building6M13Target2;
	UPROPERTY()   AMarksmanTarget* building6M13Target1;		// var AGP_Gameplay.MarksmanTarget building6M13Target1;
	UPROPERTY()   AMarksmanTarget* building6M12Target2;		// var AGP_Gameplay.MarksmanTarget building6M12Target2;
	UPROPERTY()   AMarksmanTarget* building6M12Target1;		// var AGP_Gameplay.MarksmanTarget building6M12Target1;
	UPROPERTY()   AMarksmanTarget* building6M11Target2;		// var AGP_Gameplay.MarksmanTarget building6M11Target2;
	UPROPERTY()   AMarksmanTarget* building6M11Target1;		// var AGP_Gameplay.MarksmanTarget building6M11Target1;
	UPROPERTY()   AMarksmanTarget* building6M10Target2;		// var AGP_Gameplay.MarksmanTarget building6M10Target2;
	UPROPERTY()   AMarksmanTarget* building6M10Target1;		// var AGP_Gameplay.MarksmanTarget building6M10Target1;
	UPROPERTY()   AMarksmanTarget* building6M09Target5;		// var AGP_Gameplay.MarksmanTarget building6M09Target5;
	UPROPERTY()   AMarksmanTarget* building6M09Target4;		// var AGP_Gameplay.MarksmanTarget building6M09Target4;
	UPROPERTY()   AMarksmanTarget* building6M09Target3;		// var AGP_Gameplay.MarksmanTarget building6M09Target3;
	UPROPERTY()   AMarksmanTarget* building6M09Target2;		// var AGP_Gameplay.MarksmanTarget building6M09Target2;
	UPROPERTY()   AMarksmanTarget* building6M09Target1;		// var AGP_Gameplay.MarksmanTarget building6M09Target1;
	UPROPERTY()   AMarksmanTarget* building6M08Target3;		// var AGP_Gameplay.MarksmanTarget building6M08Target3;
	UPROPERTY()   AMarksmanTarget* building6M08Target2;		// var AGP_Gameplay.MarksmanTarget building6M08Target2;
	UPROPERTY()   AMarksmanTarget* building6M08Target1;		// var AGP_Gameplay.MarksmanTarget building6M08Target1;
	UPROPERTY()   AMarksmanTarget* building6M07Target3;		// var AGP_Gameplay.MarksmanTarget building6M07Target3;
	UPROPERTY()   AMarksmanTarget* building6M07Target2;		// var AGP_Gameplay.MarksmanTarget building6M07Target2;
	UPROPERTY()   AMarksmanTarget* building6M07Target1;		// var AGP_Gameplay.MarksmanTarget building6M07Target1;
	UPROPERTY()   AMarksmanTarget* building6M06Target2;		// var AGP_Gameplay.MarksmanTarget building6M06Target2;
	UPROPERTY()   AMarksmanTarget* building6M06Target1;		// var AGP_Gameplay.MarksmanTarget building6M06Target1;
	UPROPERTY()   AMarksmanTarget* building6M05Target3;		// var AGP_Gameplay.MarksmanTarget building6M05Target3;
	UPROPERTY()   AMarksmanTarget* building6M05Target2;		// var AGP_Gameplay.MarksmanTarget building6M05Target2;
	UPROPERTY()   AMarksmanTarget* building6M05Target1;		// var AGP_Gameplay.MarksmanTarget building6M05Target1;
	UPROPERTY()   AMarksmanTarget* building6M04Target3;		// var AGP_Gameplay.MarksmanTarget building6M04Target3;
	UPROPERTY()   AMarksmanTarget* building6M04Target2;		// var AGP_Gameplay.MarksmanTarget building6M04Target2;
	UPROPERTY()   AMarksmanTarget* building6M04Target1;		// var AGP_Gameplay.MarksmanTarget building6M04Target1;
	UPROPERTY()   AMarksmanTarget* building6M03Target7;		// var AGP_Gameplay.MarksmanTarget building6M03Target7;
	UPROPERTY()   AMarksmanTarget* building6M03Target6;		// var AGP_Gameplay.MarksmanTarget building6M03Target6;
	UPROPERTY()   AMarksmanTarget* building6M03Target5;		// var AGP_Gameplay.MarksmanTarget building6M03Target5;
	UPROPERTY()   AMarksmanTarget* building6M03Target4;		// var AGP_Gameplay.MarksmanTarget building6M03Target4;
	UPROPERTY()   AMarksmanTarget* building6M03Target3;		// var AGP_Gameplay.MarksmanTarget building6M03Target3;
	UPROPERTY()   AMarksmanTarget* building6M03Target2;		// var AGP_Gameplay.MarksmanTarget building6M03Target2;
	UPROPERTY()   AMarksmanTarget* building6M03Target1;		// var AGP_Gameplay.MarksmanTarget building6M03Target1;
	UPROPERTY()   AMarksmanTarget* building6M02Target3;		// var AGP_Gameplay.MarksmanTarget building6M02Target3;
	UPROPERTY()   AMarksmanTarget* building6M02Target2;		// var AGP_Gameplay.MarksmanTarget building6M02Target2;
	UPROPERTY()   AMarksmanTarget* building6M02Target1;		// var AGP_Gameplay.MarksmanTarget building6M02Target1;
	UPROPERTY()   AMarksmanTarget* building6M01Target3;		// var AGP_Gameplay.MarksmanTarget building6M01Target3;
	UPROPERTY()   AMarksmanTarget* building6M01Target2;		// var AGP_Gameplay.MarksmanTarget building6M01Target2;
	UPROPERTY()   AMarksmanTarget* building6M01Target1;		// var AGP_Gameplay.MarksmanTarget building6M01Target1;
	UPROPERTY()   AMarksmanTarget* building5M27Target3;		// var AGP_Gameplay.MarksmanTarget building5M27Target3;
	UPROPERTY()   AMarksmanTarget* building5M27Target2;		// var AGP_Gameplay.MarksmanTarget building5M27Target2;
	UPROPERTY()   AMarksmanTarget* building5M27Target1;		// var AGP_Gameplay.MarksmanTarget building5M27Target1;
	UPROPERTY()   AMarksmanTarget* building5M26Target3;		// var AGP_Gameplay.MarksmanTarget building5M26Target3;
	UPROPERTY()   AMarksmanTarget* building5M26Target2;		// var AGP_Gameplay.MarksmanTarget building5M26Target2;
	UPROPERTY()   AMarksmanTarget* building5M26Target1;		// var AGP_Gameplay.MarksmanTarget building5M26Target1;
	UPROPERTY()   AMarksmanTarget* building5M25Target3;		// var AGP_Gameplay.MarksmanTarget building5M25Target3;
	UPROPERTY()   AMarksmanTarget* building5M25Target2;		// var AGP_Gameplay.MarksmanTarget building5M25Target2;
	UPROPERTY()   AMarksmanTarget* building5M25Target1;		// var AGP_Gameplay.MarksmanTarget building5M25Target1;
	UPROPERTY()   AMarksmanTarget* building5M24Target3;		// var AGP_Gameplay.MarksmanTarget building5M24Target3;
	UPROPERTY()   AMarksmanTarget* building5M24Target2;		// var AGP_Gameplay.MarksmanTarget building5M24Target2;
	UPROPERTY()   AMarksmanTarget* building5M24Target1;		// var AGP_Gameplay.MarksmanTarget building5M24Target1;
	UPROPERTY()   AMarksmanTarget* building5M23Target5;		// var AGP_Gameplay.MarksmanTarget building5M23Target5;
	UPROPERTY()   AMarksmanTarget* building5M23Target4;		// var AGP_Gameplay.MarksmanTarget building5M23Target4;
	UPROPERTY()   AMarksmanTarget* building5M23Target3;		// var AGP_Gameplay.MarksmanTarget building5M23Target3;
	UPROPERTY()   AMarksmanTarget* building5M23Target2;		// var AGP_Gameplay.MarksmanTarget building5M23Target2;
	UPROPERTY()   AMarksmanTarget* building5M23Target1;		// var AGP_Gameplay.MarksmanTarget building5M23Target1;
	UPROPERTY()   AMarksmanTarget* building5M22Target3;		// var AGP_Gameplay.MarksmanTarget building5M22Target3;
	UPROPERTY()   AMarksmanTarget* building5M22Target2;		// var AGP_Gameplay.MarksmanTarget building5M22Target2;
	UPROPERTY()   AMarksmanTarget* building5M22Target1;		// var AGP_Gameplay.MarksmanTarget building5M22Target1;
	UPROPERTY()   AMarksmanTarget* building5M21Target3;		// var AGP_Gameplay.MarksmanTarget building5M21Target3;
	UPROPERTY()   AMarksmanTarget* building5M21Target2;		// var AGP_Gameplay.MarksmanTarget building5M21Target2;
	UPROPERTY()   AMarksmanTarget* building5M21Target1;		// var AGP_Gameplay.MarksmanTarget building5M21Target1;
	UPROPERTY()   AMarksmanTarget* building5M20Target3;		// var AGP_Gameplay.MarksmanTarget building5M20Target3;
	UPROPERTY()   AMarksmanTarget* building5M20Target2;		// var AGP_Gameplay.MarksmanTarget building5M20Target2;
	UPROPERTY()   AMarksmanTarget* building5M20Target1;		// var AGP_Gameplay.MarksmanTarget building5M20Target1;
	UPROPERTY()   AMarksmanTarget* building5M19Target3;		// var AGP_Gameplay.MarksmanTarget building5M19Target3;
	UPROPERTY()   AMarksmanTarget* building5M19Target2;		// var AGP_Gameplay.MarksmanTarget building5M19Target2;
	UPROPERTY()   AMarksmanTarget* building5M19Target1;		// var AGP_Gameplay.MarksmanTarget building5M19Target1;
	UPROPERTY()   AMarksmanTarget* building5M18Target5;		// var AGP_Gameplay.MarksmanTarget building5M18Target5;
	UPROPERTY()   AMarksmanTarget* building5M18Target4;		// var AGP_Gameplay.MarksmanTarget building5M18Target4;
	UPROPERTY()   AMarksmanTarget* building5M18Target3;		// var AGP_Gameplay.MarksmanTarget building5M18Target3;
	UPROPERTY()   AMarksmanTarget* building5M18Target2;		// var AGP_Gameplay.MarksmanTarget building5M18Target2;
	UPROPERTY()   AMarksmanTarget* building5M18Target1;		// var AGP_Gameplay.MarksmanTarget building5M18Target1;
	UPROPERTY()   AMarksmanTarget* building5M17Target2;		// var AGP_Gameplay.MarksmanTarget building5M17Target2;
	UPROPERTY()   AMarksmanTarget* building5M17Target1;		// var AGP_Gameplay.MarksmanTarget building5M17Target1;
	UPROPERTY()   AMarksmanTarget* building5M16Target6;		// var AGP_Gameplay.MarksmanTarget building5M16Target6;
	UPROPERTY()   AMarksmanTarget* building5M16Target5;		// var AGP_Gameplay.MarksmanTarget building5M16Target5;
	UPROPERTY()   AMarksmanTarget* building5M16Target4;		// var AGP_Gameplay.MarksmanTarget building5M16Target4;
	UPROPERTY()   AMarksmanTarget* building5M16Target3;		// var AGP_Gameplay.MarksmanTarget building5M16Target3;
	UPROPERTY()   AMarksmanTarget* building5M16Target2;		// var AGP_Gameplay.MarksmanTarget building5M16Target2;
	UPROPERTY()   AMarksmanTarget* building5M16Target1;		// var AGP_Gameplay.MarksmanTarget building5M16Target1;
	UPROPERTY()   AMarksmanTarget* building5M15Target5;		// var AGP_Gameplay.MarksmanTarget building5M15Target5;
	UPROPERTY()   AMarksmanTarget* building5M15Target4;		// var AGP_Gameplay.MarksmanTarget building5M15Target4;
	UPROPERTY()   AMarksmanTarget* building5M15Target3;		// var AGP_Gameplay.MarksmanTarget building5M15Target3;
	UPROPERTY()   AMarksmanTarget* building5M15Target2;		// var AGP_Gameplay.MarksmanTarget building5M15Target2;
	UPROPERTY()   AMarksmanTarget* building5M15Target1;		// var AGP_Gameplay.MarksmanTarget building5M15Target1;
	UPROPERTY()   AMarksmanTarget* building5M14Target8;		// var AGP_Gameplay.MarksmanTarget building5M14Target8;
	UPROPERTY()   AMarksmanTarget* building5M14Target7;		// var AGP_Gameplay.MarksmanTarget building5M14Target7;
	UPROPERTY()   AMarksmanTarget* building5M14Target6;		// var AGP_Gameplay.MarksmanTarget building5M14Target6;
	UPROPERTY()   AMarksmanTarget* building5M14Target5;		// var AGP_Gameplay.MarksmanTarget building5M14Target5;
	UPROPERTY()   AMarksmanTarget* building5M14Target4;		// var AGP_Gameplay.MarksmanTarget building5M14Target4;
	UPROPERTY()   AMarksmanTarget* building5M14Target3;		// var AGP_Gameplay.MarksmanTarget building5M14Target3;
	UPROPERTY()   AMarksmanTarget* building5M14Target2;		// var AGP_Gameplay.MarksmanTarget building5M14Target2;
	UPROPERTY()   AMarksmanTarget* building5M14Target1;		// var AGP_Gameplay.MarksmanTarget building5M14Target1;
	UPROPERTY()   AMarksmanTarget* building5M13Target4;		// var AGP_Gameplay.MarksmanTarget building5M13Target4;
	UPROPERTY()   AMarksmanTarget* building5M13Target3;		// var AGP_Gameplay.MarksmanTarget building5M13Target3;
	UPROPERTY()   AMarksmanTarget* building5M13Target2;		// var AGP_Gameplay.MarksmanTarget building5M13Target2;
	UPROPERTY()   AMarksmanTarget* building5M13Target1;		// var AGP_Gameplay.MarksmanTarget building5M13Target1;
	UPROPERTY()   AMarksmanTarget* building5M12Target2;		// var AGP_Gameplay.MarksmanTarget building5M12Target2;
	UPROPERTY()   AMarksmanTarget* building5M12Target1;		// var AGP_Gameplay.MarksmanTarget building5M12Target1;
	UPROPERTY()   AMarksmanTarget* building5M11Target3;		// var AGP_Gameplay.MarksmanTarget building5M11Target3;
	UPROPERTY()   AMarksmanTarget* building5M11Target2;		// var AGP_Gameplay.MarksmanTarget building5M11Target2;
	UPROPERTY()   AMarksmanTarget* building5M11Target1;		// var AGP_Gameplay.MarksmanTarget building5M11Target1;
	UPROPERTY()   AMarksmanTarget* building5M10Target4;		// var AGP_Gameplay.MarksmanTarget building5M10Target4;
	UPROPERTY()   AMarksmanTarget* building5M10Target3;		// var AGP_Gameplay.MarksmanTarget building5M10Target3;
	UPROPERTY()   AMarksmanTarget* building5M10Target2;		// var AGP_Gameplay.MarksmanTarget building5M10Target2;
	UPROPERTY()   AMarksmanTarget* building5M10Target1;		// var AGP_Gameplay.MarksmanTarget building5M10Target1;
	UPROPERTY()   AMarksmanTarget* building5M09Target3;		// var AGP_Gameplay.MarksmanTarget building5M09Target3;
	UPROPERTY()   AMarksmanTarget* building5M09Target2;		// var AGP_Gameplay.MarksmanTarget building5M09Target2;
	UPROPERTY()   AMarksmanTarget* building5M09Target1;		// var AGP_Gameplay.MarksmanTarget building5M09Target1;
	UPROPERTY()   AMarksmanTarget* building5M08Target3;		// var AGP_Gameplay.MarksmanTarget building5M08Target3;
	UPROPERTY()   AMarksmanTarget* building5M08Target2;		// var AGP_Gameplay.MarksmanTarget building5M08Target2;
	UPROPERTY()   AMarksmanTarget* building5M08Target1;		// var AGP_Gameplay.MarksmanTarget building5M08Target1;
	UPROPERTY()   AMarksmanTarget* building5M07Target4;		// var AGP_Gameplay.MarksmanTarget building5M07Target4;
	UPROPERTY()   AMarksmanTarget* building5M07Target3;		// var AGP_Gameplay.MarksmanTarget building5M07Target3;
	UPROPERTY()   AMarksmanTarget* building5M07Target2;		// var AGP_Gameplay.MarksmanTarget building5M07Target2;
	UPROPERTY()   AMarksmanTarget* building5M07Target1;		// var AGP_Gameplay.MarksmanTarget building5M07Target1;
	UPROPERTY()   AMarksmanTarget* building5M06Target5;		// var AGP_Gameplay.MarksmanTarget building5M06Target5;
	UPROPERTY()   AMarksmanTarget* building5M06Target4;		// var AGP_Gameplay.MarksmanTarget building5M06Target4;
	UPROPERTY()   AMarksmanTarget* building5M06Target3;		// var AGP_Gameplay.MarksmanTarget building5M06Target3;
	UPROPERTY()   AMarksmanTarget* building5M06Target2;		// var AGP_Gameplay.MarksmanTarget building5M06Target2;
	UPROPERTY()   AMarksmanTarget* building5M06Target1;		// var AGP_Gameplay.MarksmanTarget building5M06Target1;
	UPROPERTY()   AMarksmanTarget* building5M05Target7;		// var AGP_Gameplay.MarksmanTarget building5M05Target7;
	UPROPERTY()   AMarksmanTarget* building5M05Target6;		// var AGP_Gameplay.MarksmanTarget building5M05Target6;
	UPROPERTY()   AMarksmanTarget* building5M05Target5;		// var AGP_Gameplay.MarksmanTarget building5M05Target5;
	UPROPERTY()   AMarksmanTarget* building5M05Target4;		// var AGP_Gameplay.MarksmanTarget building5M05Target4;
	UPROPERTY()   AMarksmanTarget* building5M05Target3;		// var AGP_Gameplay.MarksmanTarget building5M05Target3;
	UPROPERTY()   AMarksmanTarget* building5M05Target2;		// var AGP_Gameplay.MarksmanTarget building5M05Target2;
	UPROPERTY()   AMarksmanTarget* building5M05Target1;		// var AGP_Gameplay.MarksmanTarget building5M05Target1;
	UPROPERTY()   AMarksmanTarget* building5M04Target4;		// var AGP_Gameplay.MarksmanTarget building5M04Target4;
	UPROPERTY()   AMarksmanTarget* building5M04Target3;		// var AGP_Gameplay.MarksmanTarget building5M04Target3;
	UPROPERTY()   AMarksmanTarget* building5M04Target2;		// var AGP_Gameplay.MarksmanTarget building5M04Target2;
	UPROPERTY()   AMarksmanTarget* building5M04Target1;		// var AGP_Gameplay.MarksmanTarget building5M04Target1;
	UPROPERTY()   AMarksmanTarget* building5M03Target6;		// var AGP_Gameplay.MarksmanTarget building5M03Target6;
	UPROPERTY()   AMarksmanTarget* building5M03Target5;		// var AGP_Gameplay.MarksmanTarget building5M03Target5;
	UPROPERTY()   AMarksmanTarget* building5M03Target4;		// var AGP_Gameplay.MarksmanTarget building5M03Target4;
	UPROPERTY()   AMarksmanTarget* building5M03Target3;		// var AGP_Gameplay.MarksmanTarget building5M03Target3;
	UPROPERTY()   AMarksmanTarget* building5M03Target2;		// var AGP_Gameplay.MarksmanTarget building5M03Target2;
	UPROPERTY()   AMarksmanTarget* building5M03Target1;		// var AGP_Gameplay.MarksmanTarget building5M03Target1;
	UPROPERTY()   AMarksmanTarget* building5M02Target6;		// var AGP_Gameplay.MarksmanTarget building5M02Target6;
	UPROPERTY()   AMarksmanTarget* building5M02Target5;		// var AGP_Gameplay.MarksmanTarget building5M02Target5;
	UPROPERTY()   AMarksmanTarget* building5M02Target4;		// var AGP_Gameplay.MarksmanTarget building5M02Target4;
	UPROPERTY()   AMarksmanTarget* building5M02Target3;		// var AGP_Gameplay.MarksmanTarget building5M02Target3;
	UPROPERTY()   AMarksmanTarget* building5M02Target2;		// var AGP_Gameplay.MarksmanTarget building5M02Target2;
	UPROPERTY()   AMarksmanTarget* building5M02Target1;		// var AGP_Gameplay.MarksmanTarget building5M02Target1;
	UPROPERTY()   AMarksmanTarget* building5M01Target2;		// var AGP_Gameplay.MarksmanTarget building5M01Target2;
	UPROPERTY()   AMarksmanTarget* building5M01Target1;		// var AGP_Gameplay.MarksmanTarget building5M01Target1;
	UPROPERTY()   AMarksmanTarget* building4M04Target5;		// var AGP_Gameplay.MarksmanTarget building4M04Target5;
	UPROPERTY()   AMarksmanTarget* building4M04Target4;		// var AGP_Gameplay.MarksmanTarget building4M04Target4;
	UPROPERTY()   AMarksmanTarget* building4M04Target3;		// var AGP_Gameplay.MarksmanTarget building4M04Target3;
	UPROPERTY()   AMarksmanTarget* building4M04Target2;		// var AGP_Gameplay.MarksmanTarget building4M04Target2;
	UPROPERTY()   AMarksmanTarget* building4M04Target1;		// var AGP_Gameplay.MarksmanTarget building4M04Target1;
	UPROPERTY()   AMarksmanTarget* building4M03Target4;		// var AGP_Gameplay.MarksmanTarget building4M03Target4;
	UPROPERTY()   AMarksmanTarget* building4M03Target3;		// var AGP_Gameplay.MarksmanTarget building4M03Target3;
	UPROPERTY()   AMarksmanTarget* building4M03Target2;		// var AGP_Gameplay.MarksmanTarget building4M03Target2;
	UPROPERTY()   AMarksmanTarget* building4M03Target1;		// var AGP_Gameplay.MarksmanTarget building4M03Target1;
	UPROPERTY()   AMarksmanTarget* building4M02Target5;		// var AGP_Gameplay.MarksmanTarget building4M02Target5;
	UPROPERTY()   AMarksmanTarget* building4M02Target4;		// var AGP_Gameplay.MarksmanTarget building4M02Target4;
	UPROPERTY()   AMarksmanTarget* building4M02Target3;		// var AGP_Gameplay.MarksmanTarget building4M02Target3;
	UPROPERTY()   AMarksmanTarget* building4M02Target2;		// var AGP_Gameplay.MarksmanTarget building4M02Target2;
	UPROPERTY()   AMarksmanTarget* building4M02Target1;		// var AGP_Gameplay.MarksmanTarget building4M02Target1;
	UPROPERTY()   AMarksmanTarget* building4M01Target6;		// var AGP_Gameplay.MarksmanTarget building4M01Target6;
	UPROPERTY()   AMarksmanTarget* building4M01Target5;		// var AGP_Gameplay.MarksmanTarget building4M01Target5;
	UPROPERTY()   AMarksmanTarget* building4M01Target4;		// var AGP_Gameplay.MarksmanTarget building4M01Target4;
	UPROPERTY()   AMarksmanTarget* building4M01Target3;		// var AGP_Gameplay.MarksmanTarget building4M01Target3;
	UPROPERTY()   AMarksmanTarget* building4M01Target2;		// var AGP_Gameplay.MarksmanTarget building4M01Target2;
	UPROPERTY()   AMarksmanTarget* building4M01Target1;		// var AGP_Gameplay.MarksmanTarget building4M01Target1;
	UPROPERTY()   AMarksmanTarget* building3M10Target1;		// var AGP_Gameplay.MarksmanTarget building3M10Target1;
	UPROPERTY()   AMarksmanTarget* building3M09Target1;		// var AGP_Gameplay.MarksmanTarget building3M09Target1;
	UPROPERTY()   AMarksmanTarget* building3M08Target7;		// var AGP_Gameplay.MarksmanTarget building3M08Target7;
	UPROPERTY()   AMarksmanTarget* building3M08Target6;		// var AGP_Gameplay.MarksmanTarget building3M08Target6;
	UPROPERTY()   AMarksmanTarget* building3M08Target5;		// var AGP_Gameplay.MarksmanTarget building3M08Target5;
	UPROPERTY()   AMarksmanTarget* building3M08Target4;		// var AGP_Gameplay.MarksmanTarget building3M08Target4;
	UPROPERTY()   AMarksmanTarget* building3M08Target3;		// var AGP_Gameplay.MarksmanTarget building3M08Target3;
	UPROPERTY()   AMarksmanTarget* building3M08Target2;		// var AGP_Gameplay.MarksmanTarget building3M08Target2;
	UPROPERTY()   AMarksmanTarget* building3M08Target1;		// var AGP_Gameplay.MarksmanTarget building3M08Target1;
	UPROPERTY()   AMarksmanTarget* building3M07Target7;		// var AGP_Gameplay.MarksmanTarget building3M07Target7;
	UPROPERTY()   AMarksmanTarget* building3M07Target6;		// var AGP_Gameplay.MarksmanTarget building3M07Target6;
	UPROPERTY()   AMarksmanTarget* building3M07Target5;		// var AGP_Gameplay.MarksmanTarget building3M07Target5;
	UPROPERTY()   AMarksmanTarget* building3M07Target4;		// var AGP_Gameplay.MarksmanTarget building3M07Target4;
	UPROPERTY()   AMarksmanTarget* building3M07Target3;		// var AGP_Gameplay.MarksmanTarget building3M07Target3;
	UPROPERTY()   AMarksmanTarget* building3M07Target2;		// var AGP_Gameplay.MarksmanTarget building3M07Target2;
	UPROPERTY()   AMarksmanTarget* building3M07Target1;		// var AGP_Gameplay.MarksmanTarget building3M07Target1;
	UPROPERTY()   AMarksmanTarget* building3M06Target1;		// var AGP_Gameplay.MarksmanTarget building3M06Target1;
	UPROPERTY()   AMarksmanTarget* building3M05Target2;		// var AGP_Gameplay.MarksmanTarget building3M05Target2;
	UPROPERTY()   AMarksmanTarget* building3M05Target1;		// var AGP_Gameplay.MarksmanTarget building3M05Target1;
	UPROPERTY()   AMarksmanTarget* building3M04Target3;		// var AGP_Gameplay.MarksmanTarget building3M04Target3;
	UPROPERTY()   AMarksmanTarget* building3M04Target2;		// var AGP_Gameplay.MarksmanTarget building3M04Target2;
	UPROPERTY()   AMarksmanTarget* building3M04Target1;		// var AGP_Gameplay.MarksmanTarget building3M04Target1;
	UPROPERTY()   AMarksmanTarget* building3M03Target5;		// var AGP_Gameplay.MarksmanTarget building3M03Target5;
	UPROPERTY()   AMarksmanTarget* building3M03Target4;		// var AGP_Gameplay.MarksmanTarget building3M03Target4;
	UPROPERTY()   AMarksmanTarget* building3M03Target3;		// var AGP_Gameplay.MarksmanTarget building3M03Target3;
	UPROPERTY()   AMarksmanTarget* building3M03Target2;		// var AGP_Gameplay.MarksmanTarget building3M03Target2;
	UPROPERTY()   AMarksmanTarget* building3M03Target1;		// var AGP_Gameplay.MarksmanTarget building3M03Target1;
	UPROPERTY()   AMarksmanTarget* building3M02Target3;		// var AGP_Gameplay.MarksmanTarget building3M02Target3;
	UPROPERTY()   AMarksmanTarget* building3M02Target2;		// var AGP_Gameplay.MarksmanTarget building3M02Target2;
	UPROPERTY()   AMarksmanTarget* building3M02Target1;		// var AGP_Gameplay.MarksmanTarget building3M02Target1;
	UPROPERTY()   AMarksmanTarget* building3M01Target5;		// var AGP_Gameplay.MarksmanTarget building3M01Target5;
	UPROPERTY()   AMarksmanTarget* building3M01Target4;		// var AGP_Gameplay.MarksmanTarget building3M01Target4;
	UPROPERTY()   AMarksmanTarget* building3M01Target3;		// var AGP_Gameplay.MarksmanTarget building3M01Target3;
	UPROPERTY()   AMarksmanTarget* building3M01Target2;		// var AGP_Gameplay.MarksmanTarget building3M01Target2;
	UPROPERTY()   AMarksmanTarget* building3M01Target1;		// var AGP_Gameplay.MarksmanTarget building3M01Target1;
	UPROPERTY()   AMarksmanTarget* building2M18Target3;		// var AGP_Gameplay.MarksmanTarget building2M18Target3;
	UPROPERTY()   AMarksmanTarget* building2M18Target2;		// var AGP_Gameplay.MarksmanTarget building2M18Target2;
	UPROPERTY()   AMarksmanTarget* building2M18Target1;		// var AGP_Gameplay.MarksmanTarget building2M18Target1;
	UPROPERTY()   AMarksmanTarget* building2M17Target2;		// var AGP_Gameplay.MarksmanTarget building2M17Target2;
	UPROPERTY()   AMarksmanTarget* building2M17Target1;		// var AGP_Gameplay.MarksmanTarget building2M17Target1;
	UPROPERTY()   AMarksmanTarget* building2M16Target3;		// var AGP_Gameplay.MarksmanTarget building2M16Target3;
	UPROPERTY()   AMarksmanTarget* building2M16Target2;		// var AGP_Gameplay.MarksmanTarget building2M16Target2;
	UPROPERTY()   AMarksmanTarget* building2M16Target1;		// var AGP_Gameplay.MarksmanTarget building2M16Target1;
	UPROPERTY()   AMarksmanTarget* building2M15Target1;		// var AGP_Gameplay.MarksmanTarget building2M15Target1;
	UPROPERTY()   AMarksmanTarget* building2M14Target5;		// var AGP_Gameplay.MarksmanTarget building2M14Target5;
	UPROPERTY()   AMarksmanTarget* building2M14Target4;		// var AGP_Gameplay.MarksmanTarget building2M14Target4;
	UPROPERTY()   AMarksmanTarget* building2M14Target3;		// var AGP_Gameplay.MarksmanTarget building2M14Target3;
	UPROPERTY()   AMarksmanTarget* building2M14Target2;		// var AGP_Gameplay.MarksmanTarget building2M14Target2;
	UPROPERTY()   AMarksmanTarget* building2M14Target1;		// var AGP_Gameplay.MarksmanTarget building2M14Target1;
	UPROPERTY()   AMarksmanTarget* building2M13Target3;		// var AGP_Gameplay.MarksmanTarget building2M13Target3;
	UPROPERTY()   AMarksmanTarget* building2M13Target2;		// var AGP_Gameplay.MarksmanTarget building2M13Target2;
	UPROPERTY()   AMarksmanTarget* building2M13Target1;		// var AGP_Gameplay.MarksmanTarget building2M13Target1;
	UPROPERTY()   AMarksmanTarget* building2M12Target3;		// var AGP_Gameplay.MarksmanTarget building2M12Target3;
	UPROPERTY()   AMarksmanTarget* building2M12Target2;		// var AGP_Gameplay.MarksmanTarget building2M12Target2;
	UPROPERTY()   AMarksmanTarget* building2M12Target1;		// var AGP_Gameplay.MarksmanTarget building2M12Target1;
	UPROPERTY()   AMarksmanTarget* building2M11Target5;		// var AGP_Gameplay.MarksmanTarget building2M11Target5;
	UPROPERTY()   AMarksmanTarget* building2M11Target4;		// var AGP_Gameplay.MarksmanTarget building2M11Target4;
	UPROPERTY()   AMarksmanTarget* building2M11Target3;		// var AGP_Gameplay.MarksmanTarget building2M11Target3;
	UPROPERTY()   AMarksmanTarget* building2M11Target2;		// var AGP_Gameplay.MarksmanTarget building2M11Target2;
	UPROPERTY()   AMarksmanTarget* building2M11Target1;		// var AGP_Gameplay.MarksmanTarget building2M11Target1;
	UPROPERTY()   AMarksmanTarget* building2M10Target6;		// var AGP_Gameplay.MarksmanTarget building2M10Target6;
	UPROPERTY()   AMarksmanTarget* building2M10Target5;		// var AGP_Gameplay.MarksmanTarget building2M10Target5;
	UPROPERTY()   AMarksmanTarget* building2M10Target4;		// var AGP_Gameplay.MarksmanTarget building2M10Target4;
	UPROPERTY()   AMarksmanTarget* building2M10Target3;		// var AGP_Gameplay.MarksmanTarget building2M10Target3;
	UPROPERTY()   AMarksmanTarget* building2M10Target2;		// var AGP_Gameplay.MarksmanTarget building2M10Target2;
	UPROPERTY()   AMarksmanTarget* building2M10Target1;		// var AGP_Gameplay.MarksmanTarget building2M10Target1;
	UPROPERTY()   AMarksmanTarget* building2M09Target4;		// var AGP_Gameplay.MarksmanTarget building2M09Target4;
	UPROPERTY()   AMarksmanTarget* building2M09Target3;		// var AGP_Gameplay.MarksmanTarget building2M09Target3;
	UPROPERTY()   AMarksmanTarget* building2M09Target2;		// var AGP_Gameplay.MarksmanTarget building2M09Target2;
	UPROPERTY()   AMarksmanTarget* building2M09Target1;		// var AGP_Gameplay.MarksmanTarget building2M09Target1;
	UPROPERTY()   AMarksmanTarget* building2M08Target2;		// var AGP_Gameplay.MarksmanTarget building2M08Target2;
	UPROPERTY()   AMarksmanTarget* building2M08Target1;		// var AGP_Gameplay.MarksmanTarget building2M08Target1;
	UPROPERTY()   AMarksmanTarget* building2M07Target3;		// var AGP_Gameplay.MarksmanTarget building2M07Target3;
	UPROPERTY()   AMarksmanTarget* building2M07Target2;		// var AGP_Gameplay.MarksmanTarget building2M07Target2;
	UPROPERTY()   AMarksmanTarget* building2M07Target1;		// var AGP_Gameplay.MarksmanTarget building2M07Target1;
	UPROPERTY()   AMarksmanTarget* building2M06Target3;		// var AGP_Gameplay.MarksmanTarget building2M06Target3;
	UPROPERTY()   AMarksmanTarget* building2M06Target2;		// var AGP_Gameplay.MarksmanTarget building2M06Target2;
	UPROPERTY()   AMarksmanTarget* building2M06Target1;		// var AGP_Gameplay.MarksmanTarget building2M06Target1;
	UPROPERTY()   AMarksmanTarget* building2M05Target3;		// var AGP_Gameplay.MarksmanTarget building2M05Target3;
	UPROPERTY()   AMarksmanTarget* building2M05Target2;		// var AGP_Gameplay.MarksmanTarget building2M05Target2;
	UPROPERTY()   AMarksmanTarget* building2M05Target1;		// var AGP_Gameplay.MarksmanTarget building2M05Target1;
	UPROPERTY()   AMarksmanTarget* building2M04Target5;		// var AGP_Gameplay.MarksmanTarget building2M04Target5;
	UPROPERTY()   AMarksmanTarget* building2M04Target4;		// var AGP_Gameplay.MarksmanTarget building2M04Target4;
	UPROPERTY()   AMarksmanTarget* building2M04Target3;		// var AGP_Gameplay.MarksmanTarget building2M04Target3;
	UPROPERTY()   AMarksmanTarget* building2M04Target2;		// var AGP_Gameplay.MarksmanTarget building2M04Target2;
	UPROPERTY()   AMarksmanTarget* building2M04Target1;		// var AGP_Gameplay.MarksmanTarget building2M04Target1;
	UPROPERTY()   AMarksmanTarget* building2M03Target3;		// var AGP_Gameplay.MarksmanTarget building2M03Target3;
	UPROPERTY()   AMarksmanTarget* building2M03Target2;		// var AGP_Gameplay.MarksmanTarget building2M03Target2;
	UPROPERTY()   AMarksmanTarget* building2M03Target1;		// var AGP_Gameplay.MarksmanTarget building2M03Target1;
	UPROPERTY()   AMarksmanTarget* building2M02Target2;		// var AGP_Gameplay.MarksmanTarget building2M02Target2;
	UPROPERTY()   AMarksmanTarget* building2M02Target1;		// var AGP_Gameplay.MarksmanTarget building2M02Target1;
	UPROPERTY()   AMarksmanTarget* building2M01Target1;		// var AGP_Gameplay.MarksmanTarget building2M01Target1;
	UPROPERTY()   AMarksmanTarget* building1M08Target6;		// var AGP_Gameplay.MarksmanTarget building1M08Target6;
	UPROPERTY()   AMarksmanTarget* building1M08Target5;		// var AGP_Gameplay.MarksmanTarget building1M08Target5;
	UPROPERTY()   AMarksmanTarget* building1M08Target4;		// var AGP_Gameplay.MarksmanTarget building1M08Target4;
	UPROPERTY()   AMarksmanTarget* building1M08Target3;		// var AGP_Gameplay.MarksmanTarget building1M08Target3;
	UPROPERTY()   AMarksmanTarget* building1M08Target2;		// var AGP_Gameplay.MarksmanTarget building1M08Target2;
	UPROPERTY()   AMarksmanTarget* building1M08Target1;		// var AGP_Gameplay.MarksmanTarget building1M08Target1;
	UPROPERTY()   AMarksmanTarget* building1M07Target6;		// var AGP_Gameplay.MarksmanTarget building1M07Target6;
	UPROPERTY()   AMarksmanTarget* building1M07Target5;		// var AGP_Gameplay.MarksmanTarget building1M07Target5;
	UPROPERTY()   AMarksmanTarget* building1M07Target4;		// var AGP_Gameplay.MarksmanTarget building1M07Target4;
	UPROPERTY()   AMarksmanTarget* building1M07Target3;		// var AGP_Gameplay.MarksmanTarget building1M07Target3;
	UPROPERTY()   AMarksmanTarget* building1M07Target2;		// var AGP_Gameplay.MarksmanTarget building1M07Target2;
	UPROPERTY()   AMarksmanTarget* building1M07Target1;		// var AGP_Gameplay.MarksmanTarget building1M07Target1;
	UPROPERTY()   AMarksmanTarget* building1M06Target2;		// var AGP_Gameplay.MarksmanTarget building1M06Target2;
	UPROPERTY()   AMarksmanTarget* building1M06Target1;		// var AGP_Gameplay.MarksmanTarget building1M06Target1;
	UPROPERTY()   AMarksmanTarget* building1M05Target2;		// var AGP_Gameplay.MarksmanTarget building1M05Target2;
	UPROPERTY()   AMarksmanTarget* building1M05Target1;		// var AGP_Gameplay.MarksmanTarget building1M05Target1;
	UPROPERTY()   AMarksmanTarget* building1M04Target3;		// var AGP_Gameplay.MarksmanTarget building1M04Target3;
	UPROPERTY()   AMarksmanTarget* building1M04Target2;		// var AGP_Gameplay.MarksmanTarget building1M04Target2;
	UPROPERTY()   AMarksmanTarget* building1M04Target1;		// var AGP_Gameplay.MarksmanTarget building1M04Target1;
	UPROPERTY()   AMarksmanTarget* building1M03Target1;		// var AGP_Gameplay.MarksmanTarget building1M03Target1;
	UPROPERTY()   AMarksmanTarget* building1M02Target2;		// var AGP_Gameplay.MarksmanTarget building1M02Target2;
	UPROPERTY()   AMarksmanTarget* building1M02Target1;		// var AGP_Gameplay.MarksmanTarget building1M02Target1;
	UPROPERTY()   AMarksmanTarget* building1M01Target3;		// var AGP_Gameplay.MarksmanTarget building1M01Target3;
	UPROPERTY()   AMarksmanTarget* building1M01Target2;		// var AGP_Gameplay.MarksmanTarget building1M01Target2;
	UPROPERTY()   AMarksmanTarget* building1M01Target1;		// var AGP_Gameplay.MarksmanTarget building1M01Target1;
	UPROPERTY()   ATrigger* OutdoorIED03b_lethal;			// var Trigger OutdoorIED03b_lethal;
	UPROPERTY()   ATrigger* OutdoorIED02b_lethal;			// var Trigger OutdoorIED02b_lethal;
	UPROPERTY()   ATrigger* OutdoorIED01b_lethal;			// var Trigger OutdoorIED01b_lethal;
	UPROPERTY()   ATrigger* Objective12_lethal;				// var Trigger Objective12_lethal;
	UPROPERTY()   ATrigger* Objective11_lethal;				// var Trigger Objective11_lethal;
	UPROPERTY()   ATrigger* Objective10_lethal;				// var Trigger Objective10_lethal;
	UPROPERTY()   ATrigger* Objective09_lethal;				// var Trigger Objective09_lethal;
	UPROPERTY()   ATrigger* Objective08_lethal;				// var Trigger Objective08_lethal;
	UPROPERTY()   ATrigger* Objective07_lethal;				// var Trigger Objective07_lethal;
	UPROPERTY()   ATrigger* Objective06_lethal;				// var Trigger Objective06_lethal;
	UPROPERTY()   ATrigger* Objective05_lethal;				// var Trigger Objective05_lethal;
	UPROPERTY()   ATrigger* Objective04_lethal;				// var Trigger Objective04_lethal;
	UPROPERTY()   ATrigger* Objective02_lethal;				// var Trigger Objective02_lethal;
	UPROPERTY()   ATrigger* Objective01_lethal;				// var Trigger Objective01_lethal;
	UPROPERTY()   ATriggerVolume* StartGateVO;				// var AGP_Gameplay.TriggerVolume StartGateVO;
	UPROPERTY()   ATriggerVolume* triggerAARUpdate;			// var AGP_Gameplay.TriggerVolume triggerAARUpdate;
	UPROPERTY()   ATriggerVolume* triggerES2Objects;		// var AGP_Gameplay.TriggerVolume triggerES2Objects;
	UPROPERTY()   ATriggerVolume* WeaponClearVolumeTrigger;	// var AGP_Gameplay.TriggerVolume WeaponClearVolumeTrigger;
	UPROPERTY()   ATriggerVolume* holsterTrigger;			// var AGP_Gameplay.TriggerVolume holsterTrigger;
	UPROPERTY()   ATriggerVolume* authTrigger;				// var AGP_Gameplay.TriggerVolume authTrigger;
	UPROPERTY()   ATriggerVolume* building6MTTrigger07;		// var AGP_Gameplay.TriggerVolume building6MTTrigger07;
	UPROPERTY()   ATriggerVolume* building6MTTrigger06;		// var AGP_Gameplay.TriggerVolume building6MTTrigger06;
	UPROPERTY()   ATriggerVolume* building6MTTrigger05;		// var AGP_Gameplay.TriggerVolume building6MTTrigger05;
	UPROPERTY()   ATriggerVolume* building6MTTrigger04;		// var AGP_Gameplay.TriggerVolume building6MTTrigger04;
	UPROPERTY()   ATriggerVolume* building6MTTrigger03;		// var AGP_Gameplay.TriggerVolume building6MTTrigger03;
	UPROPERTY()   ATriggerVolume* building6MTTrigger02;		// var AGP_Gameplay.TriggerVolume building6MTTrigger02;
	UPROPERTY()   ATriggerVolume* building6MTTrigger01;		// var AGP_Gameplay.TriggerVolume building6MTTrigger01;
	UPROPERTY()   ATriggerVolume* building5MTTrigger28;		// var AGP_Gameplay.TriggerVolume building5MTTrigger28;
	UPROPERTY()   ATriggerVolume* building5MTTrigger27;		// var AGP_Gameplay.TriggerVolume building5MTTrigger27;
	UPROPERTY()   ATriggerVolume* building5MTTrigger26;		// var AGP_Gameplay.TriggerVolume building5MTTrigger26;
	UPROPERTY()   ATriggerVolume* building5MTTrigger25;		// var AGP_Gameplay.TriggerVolume building5MTTrigger25;
	UPROPERTY()   ATriggerVolume* building5MTTrigger24;		// var AGP_Gameplay.TriggerVolume building5MTTrigger24;
	UPROPERTY()   ATriggerVolume* building5MTTrigger23;		// var AGP_Gameplay.TriggerVolume building5MTTrigger23;
	UPROPERTY()   ATriggerVolume* building5MTTrigger22;		// var AGP_Gameplay.TriggerVolume building5MTTrigger22;
	UPROPERTY()   ATriggerVolume* building5MTTrigger21;		// var AGP_Gameplay.TriggerVolume building5MTTrigger21;
	UPROPERTY()   ATriggerVolume* building5MTTrigger20;		// var AGP_Gameplay.TriggerVolume building5MTTrigger20;
	UPROPERTY()   ATriggerVolume* building5MTTrigger19;		// var AGP_Gameplay.TriggerVolume building5MTTrigger19;
	UPROPERTY()   ATriggerVolume* building5MTTrigger18;		// var AGP_Gameplay.TriggerVolume building5MTTrigger18;
	UPROPERTY()   ATriggerVolume* building5MTTrigger17;		// var AGP_Gameplay.TriggerVolume building5MTTrigger17;
	UPROPERTY()   ATriggerVolume* building5MTTrigger16;		// var AGP_Gameplay.TriggerVolume building5MTTrigger16;
	UPROPERTY()   ATriggerVolume* building5MTTrigger15;		// var AGP_Gameplay.TriggerVolume building5MTTrigger15;
	UPROPERTY()   ATriggerVolume* building5MTTrigger14;		// var AGP_Gameplay.TriggerVolume building5MTTrigger14;
	UPROPERTY()   ATriggerVolume* building5MTTrigger13;		// var AGP_Gameplay.TriggerVolume building5MTTrigger13;
	UPROPERTY()   ATriggerVolume* building5MTTrigger12;		// var AGP_Gameplay.TriggerVolume building5MTTrigger12;
	UPROPERTY()   ATriggerVolume* building5MTTrigger11;		// var AGP_Gameplay.TriggerVolume building5MTTrigger11;
	UPROPERTY()   ATriggerVolume* building5MTTrigger10;		// var AGP_Gameplay.TriggerVolume building5MTTrigger10;
	UPROPERTY()   ATriggerVolume* building5MTTrigger09;		// var AGP_Gameplay.TriggerVolume building5MTTrigger09;
	UPROPERTY()   ATriggerVolume* building5MTTrigger08;		// var AGP_Gameplay.TriggerVolume building5MTTrigger08;
	UPROPERTY()   ATriggerVolume* building5MTTrigger07;		// var AGP_Gameplay.TriggerVolume building5MTTrigger07;
	UPROPERTY()   ATriggerVolume* building5MTTrigger06;		// var AGP_Gameplay.TriggerVolume building5MTTrigger06;
	UPROPERTY()   ATriggerVolume* building5MTTrigger05;		// var AGP_Gameplay.TriggerVolume building5MTTrigger05;
	UPROPERTY()   ATriggerVolume* building5MTTrigger04;		// var AGP_Gameplay.TriggerVolume building5MTTrigger04;
	UPROPERTY()   ATriggerVolume* building5MTTrigger03;		// var AGP_Gameplay.TriggerVolume building5MTTrigger03;
	UPROPERTY()   ATriggerVolume* building5MTTrigger02;		// var AGP_Gameplay.TriggerVolume building5MTTrigger02;
	UPROPERTY()   ATriggerVolume* building5MTTrigger01;		// var AGP_Gameplay.TriggerVolume building5MTTrigger01;
	UPROPERTY()   ATriggerVolume* building4MTTrigger04;		// var AGP_Gameplay.TriggerVolume building4MTTrigger04;
	UPROPERTY()   ATriggerVolume* building4MTTrigger03;		// var AGP_Gameplay.TriggerVolume building4MTTrigger03;
	UPROPERTY()   ATriggerVolume* building4MTTrigger02;		// var AGP_Gameplay.TriggerVolume building4MTTrigger02;
	UPROPERTY()   ATriggerVolume* building3MTTrigger08;		// var AGP_Gameplay.TriggerVolume building3MTTrigger08;
	UPROPERTY()   ATriggerVolume* building3MTTrigger07;		// var AGP_Gameplay.TriggerVolume building3MTTrigger07;
	UPROPERTY()   ATriggerVolume* building3MTTrigger06;		// var AGP_Gameplay.TriggerVolume building3MTTrigger06;
	UPROPERTY()   ATriggerVolume* building3MTTrigger05;		// var AGP_Gameplay.TriggerVolume building3MTTrigger05;
	UPROPERTY()   ATriggerVolume* building3MTTrigger04;		// var AGP_Gameplay.TriggerVolume building3MTTrigger04;
	UPROPERTY()   ATriggerVolume* building3MTTrigger03;		// var AGP_Gameplay.TriggerVolume building3MTTrigger03;
	UPROPERTY()   ATriggerVolume* building3MTTrigger02;		// var AGP_Gameplay.TriggerVolume building3MTTrigger02;
	UPROPERTY()   ATriggerVolume* building3MTTrigger01;		// var AGP_Gameplay.TriggerVolume building3MTTrigger01;
	UPROPERTY()   ATriggerVolume* building2MTTrigger10;		// var AGP_Gameplay.TriggerVolume building2MTTrigger10;
	UPROPERTY()   ATriggerVolume* building2MTTrigger09;		// var AGP_Gameplay.TriggerVolume building2MTTrigger09;
	UPROPERTY()   ATriggerVolume* building2MTTrigger08;		// var AGP_Gameplay.TriggerVolume building2MTTrigger08;
	UPROPERTY()   ATriggerVolume* building2MTTrigger07;		// var AGP_Gameplay.TriggerVolume building2MTTrigger07;
	UPROPERTY()   ATriggerVolume* building2MTTrigger06;		// var AGP_Gameplay.TriggerVolume building2MTTrigger06;
	UPROPERTY()   ATriggerVolume* building2MTTrigger05;		// var AGP_Gameplay.TriggerVolume building2MTTrigger05;
	UPROPERTY()   ATriggerVolume* building2MTTrigger04;		// var AGP_Gameplay.TriggerVolume building2MTTrigger04;
	UPROPERTY()   ATriggerVolume* building2MTTrigger03;		// var AGP_Gameplay.TriggerVolume building2MTTrigger03;
	UPROPERTY()   ATriggerVolume* building2MTTrigger02;		// var AGP_Gameplay.TriggerVolume building2MTTrigger02;
	UPROPERTY()   ATriggerVolume* building2MTTrigger01;		// var AGP_Gameplay.TriggerVolume building2MTTrigger01;
	UPROPERTY()   ATriggerVolume* building1MTTrigger03;		// var AGP_Gameplay.TriggerVolume building1MTTrigger03;
	UPROPERTY()   ATriggerVolume* building1MTTrigger02;		// var AGP_Gameplay.TriggerVolume building1MTTrigger02;
	UPROPERTY()   ATriggerVolume* building1MTTrigger01;		// var AGP_Gameplay.TriggerVolume building1MTTrigger01;
	UPROPERTY()   ATriggerVolume* building6Trigger6;		// var AGP_Gameplay.TriggerVolume building6Trigger6;
	UPROPERTY()   ATriggerVolume* building6Trigger5;		// var AGP_Gameplay.TriggerVolume building6Trigger5;
	UPROPERTY()   ATriggerVolume* building6Trigger4;		// var AGP_Gameplay.TriggerVolume building6Trigger4;
	UPROPERTY()   ATriggerVolume* building6Trigger3;		// var AGP_Gameplay.TriggerVolume building6Trigger3;
	UPROPERTY()   ATriggerVolume* building5Trigger8;		// var AGP_Gameplay.TriggerVolume building5Trigger8;
	UPROPERTY()   ATriggerVolume* building5Trigger7;		// var AGP_Gameplay.TriggerVolume building5Trigger7;
	UPROPERTY()   ATriggerVolume* building5Trigger6;		// var AGP_Gameplay.TriggerVolume building5Trigger6;
	UPROPERTY()   ATriggerVolume* building5Trigger5;		// var AGP_Gameplay.TriggerVolume building5Trigger5;
	UPROPERTY()   ATriggerVolume* building5Trigger4;		// var AGP_Gameplay.TriggerVolume building5Trigger4;
	UPROPERTY()   ATriggerVolume* building5Trigger3;		// var AGP_Gameplay.TriggerVolume building5Trigger3;
	UPROPERTY()   ATriggerVolume* building5Trigger2;		// var AGP_Gameplay.TriggerVolume building5Trigger2;
	UPROPERTY()   ATriggerVolume* building5Trigger1;		// var AGP_Gameplay.TriggerVolume building5Trigger1;
	UPROPERTY()   ATriggerVolume* building4Trigger6;		// var AGP_Gameplay.TriggerVolume building4Trigger6;
	UPROPERTY()   ATriggerVolume* building4Trigger5;		// var AGP_Gameplay.TriggerVolume building4Trigger5;
	UPROPERTY()   ATriggerVolume* building4Trigger4;		// var AGP_Gameplay.TriggerVolume building4Trigger4;
	UPROPERTY()   ATriggerVolume* building4Trigger3;		// var AGP_Gameplay.TriggerVolume building4Trigger3;
	UPROPERTY()   ATriggerVolume* building3Trigger6;		// var AGP_Gameplay.TriggerVolume building3Trigger6;
	UPROPERTY()   ATriggerVolume* building3Trigger5;		// var AGP_Gameplay.TriggerVolume building3Trigger5;
	UPROPERTY()   ATriggerVolume* building3Trigger4;		// var AGP_Gameplay.TriggerVolume building3Trigger4;
	UPROPERTY()   ATriggerVolume* building3Trigger3;		// var AGP_Gameplay.TriggerVolume building3Trigger3;
	UPROPERTY()   ATriggerVolume* building3Trigger2;		// var AGP_Gameplay.TriggerVolume building3Trigger2;
	UPROPERTY()   ATriggerVolume* building3Trigger1;		// var AGP_Gameplay.TriggerVolume building3Trigger1;
	UPROPERTY()   ATriggerVolume* building2Trigger4;		// var AGP_Gameplay.TriggerVolume building2Trigger4;
	UPROPERTY()   ATriggerVolume* building2Trigger3;		// var AGP_Gameplay.TriggerVolume building2Trigger3;
	UPROPERTY()   ATriggerVolume* building2Trigger2;		// var AGP_Gameplay.TriggerVolume building2Trigger2;
	UPROPERTY()   ATriggerVolume* building2Trigger1;		// var AGP_Gameplay.TriggerVolume building2Trigger1;
	UPROPERTY()   ATriggerVolume* building1Trigger4;		// var AGP_Gameplay.TriggerVolume building1Trigger4;
	UPROPERTY()   ATriggerVolume* building1Trigger3;		// var AGP_Gameplay.TriggerVolume building1Trigger3;
	UPROPERTY()   ATriggerVolume* building1Trigger2;		// var AGP_Gameplay.TriggerVolume building1Trigger2;
	UPROPERTY()   ATriggerVolume* building1Trigger1;		// var AGP_Gameplay.TriggerVolume building1Trigger1;
	UPROPERTY()   FString inspectUseTip;					// var string inspectUseTip;
	UPROPERTY()   FString cadreUseTipAAR;					// var string cadreUseTipAAR;
	UPROPERTY()   FString cadreUseTip2;						// var string cadreUseTip2;
	UPROPERTY()   FString cadreUseTip1;						// var string cadreUseTip1;
	UPROPERTY()   AAGP_Character_NPC* cadreAAR;				// var AGP_Characters.AGP_Character_NPC cadreAAR;
	UPROPERTY()   AAGP_Character_NPC* cadreInstructor;		// var AGP_Characters.AGP_Character_NPC cadreInstructor;
	UPROPERTY()   ADoorTrigger* doorTrigger1;				// var AGP_Gameplay.DoorTrigger doorTrigger1;
	UPROPERTY()   AMover* startGate1;						// var Mover startGate1;
	UPROPERTY()   AAGP_Objective* IEDObjective12;			// var AGP.AGP_Objective IEDObjective12;
	UPROPERTY()   AAGP_Objective* IEDObjective11;			// var AGP.AGP_Objective IEDObjective11;
	UPROPERTY()   AAGP_Objective* IEDObjective10;			// var AGP.AGP_Objective IEDObjective10;
	UPROPERTY()   AAGP_Objective* IEDObjective09;			// var AGP.AGP_Objective IEDObjective09;
	UPROPERTY()   AAGP_Objective* IEDObjective08;			// var AGP.AGP_Objective IEDObjective08;
	UPROPERTY()   AAGP_Objective* IEDObjective07;			// var AGP.AGP_Objective IEDObjective07;
	UPROPERTY()   AAGP_Objective* IEDObjective06;			// var AGP.AGP_Objective IEDObjective06;
	UPROPERTY()   AAGP_Objective* IEDObjective05;			// var AGP.AGP_Objective IEDObjective05;
	UPROPERTY()   AAGP_Objective* IEDObjective04;			// var AGP.AGP_Objective IEDObjective04;
	UPROPERTY()   AAGP_Objective* IEDObjective03;			// var AGP.AGP_Objective IEDObjective03;
	UPROPERTY()   AAGP_Objective* IEDObjective02;			// var AGP.AGP_Objective IEDObjective02;
	UPROPERTY()   AAGP_Objective* IEDObjective01;			// var AGP.AGP_Objective IEDObjective01;
	UPROPERTY()   AAGP_UseTrigger* sbUseTrigger;			// var AGP.AGP_UseTrigger sbUseTrigger;
	UPROPERTY()   AAGP_UseTrigger* inspectUseTrigger;		// var AGP.AGP_UseTrigger inspectUseTrigger;
	UPROPERTY()   AAGP_UseTrigger* skipVOTrigger;			// var AGP.AGP_UseTrigger skipVOTrigger;
	UPROPERTY()   AAGP_UseTrigger* cadreUseTrigger2;		// var AGP.AGP_UseTrigger cadreUseTrigger2;
	UPROPERTY()   AAGP_UseTrigger* cadreUseTrigger1;		// var AGP.AGP_UseTrigger cadreUseTrigger1;
	UPROPERTY()   ATextDisplay* aarDisplay;					// var AGP_Gameplay.TextDisplay aarDisplay;
	UPROPERTY()   ATextDisplay* TextDisplay;				// var AGP_Gameplay.TextDisplay TextDisplay;
	UPROPERTY()   APickup* w_m9;							// var Pickup w_m9;
	UPROPERTY()   APickup* w_m4a1;							// var Pickup w_m4a1;

	bool DecoMesh_Damaged(ADecoMesh* NotifyActor, AActor* aInstigator, FString Parms);
	bool Pawn_Custom(APawn* NotifyActor, AActor* aInstigator, FString Parms);
	bool AGP_Pawn_Custom(AAGP_Pawn* NotifyActor, AActor* aInstigator, FString Parms);
	bool AGP_Character_Custom(AAGP_Character* NotifyActor, AActor* aInstigator, FString Parms);
	bool AGP_Weapon_Throw(AAGP_Weapon* NotifyActor, AActor* aInstigator, FString Parms);
	bool Pickup_PickedUp(APickup* NotifyActor, AActor* aInstigator, FString Parms);
	bool AGP_Weapon_Fire(AAGP_Weapon* NotifyActor, AActor* aInstigator, FString Parms);
	void doCantDrop();
	bool AGP_Character_Died(AAGP_Character* NotifyActor, AController* aInstigator);
	void Leavenworth();
	bool Pawn_Damaged(APawn* NotifyActor, AController* aInstigator);
	void SecurityViolation();
	void SecurityViolationPart2();
	void JumpToAAR();
	void JumpToAARFadeIn();
	void OutOfAmmoFadeIn();
	void OutOfTime();
	void PlayKeepMoving();
	void CheckPlayerMove();
	void PlayIEDDialog();
	void RestartLevel();
	void PreInit();
	void flipDoor1Targets();
	void flipDoor2Targets();
	void PostPostInit();
	void doCantTouch();
	void RemoveWeapons();
	bool AGP_UseTrigger_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	bool inspectUseTrigger_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	bool DoorTrigger_UsedBy(ADoorTrigger* Trigger, AActor* aInstigator);
	bool triggerES2Objects_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool triggerAARUpdate_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool StartGateVO_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool PlayerHasWeapon(APawn* Player);
	bool doorTrigger1_UsedBy(ADoorTrigger* Trigger, AActor* aInstigator);
	bool cadreUseTrigger1_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	bool cadreUseTrigger2_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	bool sbUseTrigger_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	void holsterweapon();
	bool Timer_Timer(FName Name);
	bool Timer_Sound(FName Name);
	bool aarScoreboard();
	bool Trigger_Entered(ATrigger* Trigger, AActor* aInstigator);
	bool TriggerVolume_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building1Trigger1_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building1Trigger2_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building1Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building1Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger1_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger2_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger5_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building2Trigger6_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger1_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger2_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger5_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building3Trigger6_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building4Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building4Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building4Trigger5_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building4Trigger6_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger1_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger2_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger5_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger6_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger7_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building5Trigger8_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger3_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger4_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger5_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger6_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger7_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool building6Trigger8_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building1MT_Trigger02AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building1MT_Trigger06AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building1MT_Trigger02B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger07B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger08A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger09A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger10A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger11A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger12A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger05B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger04B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger03B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building2MT_Trigger02B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger02ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger03B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger03ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger04B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger05B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger06B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger07AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building3MT_Trigger08AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building4MT_Trigger02AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building4MT_Trigger03AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building4MT_Trigger04AB_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger01A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger02ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger03ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger04ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger05ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger06ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger07ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger08ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger09ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger10ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger11ABC_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger12ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger13ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger14ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger15ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger16ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger17ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger18ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger19ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger20ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger21ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger22ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger23ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger24ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger25ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger26ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger27ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building5MT_Trigger28ABCD_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger01B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger02B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger03B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger04B_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger05A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger06A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool Building6MT_Trigger07A_Enter(ATriggerVolume* Trigger, AActor* aInstigator);
	bool skipVOTrigger_UsedBy(AAGP_UseTrigger* Trigger, AActor* aInstigator);
	bool Objective01_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective02_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective04_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective05_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective06_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective07_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective08_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective09_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective10_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective11_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool Objective12_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool OutdoorIED01b_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool OutdoorIED02b_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool OutdoorIED03b_lethal_Enter(ATrigger* Trigger, AActor* aInstigator);
	bool AGP_Objective_Trigger(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective01_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective02_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective04_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective05_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective06_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective07_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective08_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective09_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective10_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective11_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	bool IEDObjective12_Triggered(AAGP_Objective* NotifyActor, AActor* aInstigator);
	void DisableAllMTTriggers();
	bool MarksmanTarget_Damaged(AMarksmanTarget* NotifyActor, AActor* aInstigator, FString Parms);
	bool uploadStats();
	void EL_ES2ObjectFound(int32 Score);
};
