// All the original content belonged to the US Army


#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_Javelinexplosion/em_bt_Javelinexplosion.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/MeshEmitter/MeshEmitter.h"

Aem_bt_Javelinexplosion::Aem_bt_Javelinexplosion()
{
	UMeshEmitter* MeshEmitter11 = NewObject<UMeshEmitter>(UMeshEmitter::StaticClass());
	MeshEmitter11->StaticMesh = LoadObject<UStaticMesh>(NULL, TEXT("StaticMesh'/Game/AmericasArmy/Meshes/M_AA2_FX/Particles/fx_part_con_chunk1.fx_part_con_chunk1'"), NULL, LOAD_None, NULL);
	MeshEmitter11->UseCollision = true;
	MeshEmitter11->UseMaxCollisions = true;
	MeshEmitter11->FadeOut = true;
	MeshEmitter11->RespawnDeadParticles = false;
	MeshEmitter11->AutoDestroy = true;
	MeshEmitter11->SpinParticles = true;
	MeshEmitter11->UseSizeScale = true;
	MeshEmitter11->UseRegularSizeScale = false;
	MeshEmitter11->AutomaticInitialSpawning = false;
	MeshEmitter11->Acceleration = FVector(0, 0, -700);
	//MeshEmitter11->DampingFactorRange=X=(Min=0.6, Max=0.6)|Y=(Min=0.6, Max=0.6)|Z=(Min=0.2, Max=0.2);
	MeshEmitter11->MaxCollisions = FRange({ 3, 4 });
	//MeshEmitter11->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 255)});
	//MeshEmitter11->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 255)});
	MeshEmitter11->FadeOutStartTime = 0.5;
	MeshEmitter11->MaxParticles = 30;
	//MeshEmitter11->StartLocationRange=X=(Min=-100, Max=100)|Y=(Min=-100, Max=100)|Z=(Min=-100, Max=100);
	MeshEmitter11->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//MeshEmitter11->SpinsPerSecondRange=X=(Min=0.5, Max=1)|Y=(Min=0.5, Max=1)|Z=(Min=0.5, Max=1);
	//MeshEmitter11->StartSpinRange=X=(Min=-1, Max=1)|Y=(Min=-1, Max=1)|Z=(Min=-1, Max=1);
	//MeshEmitter11->StartSizeRange=X=(Min=0, Max=2)|Y=(Min=0, Max=2)|Z=(Min=0, Max=2);
	MeshEmitter11->InitialParticlesPerSecond = 2000;
	MeshEmitter11->SecondsBeforeInactive = 0;
	MeshEmitter11->LifetimeRange = FRange({ 1, 8 });
	//MeshEmitter11->StartVelocityRange=X=(Min=-1900, Max=1900)|Y=(Min=-1900, Max=1900)|Z=(Min=-1000, Max=1000);
	USpriteEmitter* SpriteEmitter0 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter0->FadeOut = true;
	SpriteEmitter0->RespawnDeadParticles = false;
	SpriteEmitter0->SpinParticles = true;
	SpriteEmitter0->UseSizeScale = true;
	SpriteEmitter0->UseRegularSizeScale = false;
	SpriteEmitter0->UniformSize = true;
	SpriteEmitter0->AutomaticInitialSpawning = false;
	SpriteEmitter0->BlendBetweenSubdivisions = true;
	//SpriteEmitter0->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 255)});
	//SpriteEmitter0->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 255)});
	SpriteEmitter0->FadeOutStartTime = 0.4;
	SpriteEmitter0->FadeInEndTime = 0.2;
	SpriteEmitter0->MaxParticles = 4000;
	SpriteEmitter0->AddLocationFromOtherEmitter = 0;
	SpriteEmitter0->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter0->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter0->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter0->SizeScale[0]=FParticleTimeScale({0,2});
	//SpriteEmitter0->SizeScale[1]=FParticleTimeScale({1,2.5});
	//SpriteEmitter0->StartSizeRange=X=(Min=25, Max=40)|Y=(Min=25, Max=40)|Z=(Min=25, Max=40);
	SpriteEmitter0->InitialParticlesPerSecond = 1500;
	SpriteEmitter0->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter0->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_explosion01_Mat.fx_part_explosion01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter0->TextureUSubdivisions = 4;
	SpriteEmitter0->TextureVSubdivisions = 2;
	SpriteEmitter0->LifetimeRange = FRange({ 0.504, 1.5 });
	//SpriteEmitter0->StartVelocityRange=X=(Min=-250, Max=250)|Y=(Min=-250, Max=250)|Z=(Min=1.25, Max=500);
	SpriteEmitter0->MaxAbsVelocity = FVector(0, 0, 0);
	//SpriteEmitter0->VelocityLossRange=X=(Min=4, Max=4)|Y=(Min=4, Max=4)|Z=(Min=4, Max=4);
	USpriteEmitter* SpriteEmitter1 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter1->UseColorScale = true;
	SpriteEmitter1->FadeOut = true;
	SpriteEmitter1->FadeIn = true;
	SpriteEmitter1->RespawnDeadParticles = false;
	SpriteEmitter1->SpinParticles = true;
	SpriteEmitter1->UseSizeScale = true;
	SpriteEmitter1->UseRegularSizeScale = false;
	SpriteEmitter1->UniformSize = true;
	SpriteEmitter1->AutomaticInitialSpawning = false;
	SpriteEmitter1->Acceleration = FVector(3.75, 0, 0);
	//SpriteEmitter1->ColorScale[0]=FParticleColorScale({0,FColor(30, 30, 30, 255)});
	//SpriteEmitter1->ColorScale[1]=FParticleColorScale({1,FColor(226, 226, 226, 255)});
	//SpriteEmitter1->ColorScale[2]=FParticleColorScale({1,FColor(255, 255, 255, 255)});
	SpriteEmitter1->FadeOutStartTime = 1.65;
	SpriteEmitter1->FadeInEndTime = 0.9;
	SpriteEmitter1->MaxParticles = 4000;
	//SpriteEmitter1->StartLocationRange=X=(Min=-75, Max=75)|Y=(Min=-75, Max=75)|Z=(Min=0, Max=0);
	SpriteEmitter1->AddLocationFromOtherEmitter = 0;
	SpriteEmitter1->SpinCCWorCW = FVector(0.25, 0.75, 0.5);
	//SpriteEmitter1->SpinsPerSecondRange=X=(Min=0.03, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter1->StartSpinRange=X=(Min=0, Max=32000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter1->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter1->SizeScale[1]=FParticleTimeScale({1,2});
	//SpriteEmitter1->StartSizeRange=X=(Min=1, Max=100)|Y=(Min=1, Max=100)|Z=(Min=1, Max=100);
	SpriteEmitter1->InitialParticlesPerSecond = 1500;
	SpriteEmitter1->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter1->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball01_Mat.fx_smk_ball01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter1->TextureUSubdivisions = 1;
	SpriteEmitter1->TextureVSubdivisions = 1;
	SpriteEmitter1->LifetimeRange = FRange({ 2, 3 });
	//SpriteEmitter1->StartVelocityRange=X=(Min=-7.5, Max=7.5)|Y=(Min=-7.5, Max=7.5)|Z=(Min=1, Max=133);
	SpriteEmitter1->fWindFactor = 3;
	USpriteEmitter* SpriteEmitter2 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter2->FadeOut = true;
	SpriteEmitter2->RespawnDeadParticles = false;
	SpriteEmitter2->SpinParticles = true;
	SpriteEmitter2->UseSizeScale = true;
	SpriteEmitter2->UseRegularSizeScale = false;
	SpriteEmitter2->UniformSize = true;
	SpriteEmitter2->AutomaticInitialSpawning = false;
	SpriteEmitter2->BlendBetweenSubdivisions = true;
	//SpriteEmitter2->ColorScale[0]=FParticleColorScale({0,FColor(255, 255, 255, 255)});
	//SpriteEmitter2->ColorScale[1]=FParticleColorScale({1,FColor(255, 255, 255, 255)});
	SpriteEmitter2->FadeOutStartTime = 0.4;
	SpriteEmitter2->FadeInEndTime = 0.2;
	SpriteEmitter2->MaxParticles = 50;
	SpriteEmitter2->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter2->SpinsPerSecondRange=X=(Min=0.05, Max=0.1)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter2->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter2->SizeScale[0]=FParticleTimeScale({0,2});
	//SpriteEmitter2->SizeScale[1]=FParticleTimeScale({1,2.5});
	//SpriteEmitter2->StartSizeRange=X=(Min=70, Max=80)|Y=(Min=70, Max=80)|Z=(Min=70, Max=80);
	SpriteEmitter2->InitialParticlesPerSecond = 5000;
	SpriteEmitter2->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter2->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_explosion01_Mat.fx_part_explosion01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter2->TextureUSubdivisions = 4;
	SpriteEmitter2->TextureVSubdivisions = 2;
	SpriteEmitter2->LifetimeRange = FRange({ 0.499, 1 });
	//SpriteEmitter2->StartVelocityRange=X=(Min=-1750, Max=1750)|Y=(Min=-1750, Max=1750)|Z=(Min=1, Max=3500);
	SpriteEmitter2->MaxAbsVelocity = FVector(0, 0, 0);
	//SpriteEmitter2->VelocityLossRange=X=(Min=4, Max=4)|Y=(Min=4, Max=4)|Z=(Min=4, Max=4);
	USpriteEmitter* SpriteEmitter3 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter3->UseColorScale = true;
	SpriteEmitter3->FadeOut = true;
	SpriteEmitter3->RespawnDeadParticles = false;
	SpriteEmitter3->SpinParticles = true;
	SpriteEmitter3->DampRotation = true;
	SpriteEmitter3->UseSizeScale = true;
	SpriteEmitter3->UseRegularSizeScale = false;
	SpriteEmitter3->UniformSize = true;
	SpriteEmitter3->AutomaticInitialSpawning = false;
	SpriteEmitter3->Acceleration = FVector(0, 0, 500);
	//SpriteEmitter3->ColorScale[0]=FParticleColorScale({0,FColor(64, 128, 255, 255)});
	//SpriteEmitter3->ColorScale[1]=FParticleColorScale({0.142857,FColor(94, 158, 255, 255)});
	//SpriteEmitter3->ColorScale[2]=FParticleColorScale({0.375,FColor(87, 105, 125, 255)});
	//SpriteEmitter3->ColorScale[3]=FParticleColorScale({1,FColor(52, 61, 73, 255)});
	SpriteEmitter3->FadeOutStartTime = 4.06;
	SpriteEmitter3->MaxParticles = 25;
	SpriteEmitter3->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter3->SpinsPerSecondRange=X=(Min=0, Max=0.25)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter3->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter3->SizeScale[1]=FParticleTimeScale({0.17,4});
	//SpriteEmitter3->SizeScale[2]=FParticleTimeScale({1,8});
	//SpriteEmitter3->StartSizeRange=X=(Min=4, Max=40)|Y=(Min=4, Max=40)|Z=(Min=4, Max=40);
	SpriteEmitter3->InitialParticlesPerSecond = 50;
	SpriteEmitter3->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter3->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball02_Mat.fx_smk_ball02_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter3->LifetimeRange = FRange({ 4, 7 });
	//SpriteEmitter3->StartVelocityRange=X=(Min=-5000, Max=5000)|Y=(Min=-5000, Max=5000)|Z=(Min=1000, Max=1000);
	//SpriteEmitter3->VelocityLossRange=X=(Min=8, Max=8)|Y=(Min=8, Max=8)|Z=(Min=8, Max=8);
	USpriteEmitter* SpriteEmitter4 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter4->UseColorScale = true;
	SpriteEmitter4->FadeOut = true;
	SpriteEmitter4->FadeIn = true;
	SpriteEmitter4->RespawnDeadParticles = false;
	SpriteEmitter4->SpinParticles = true;
	SpriteEmitter4->UseSizeScale = true;
	SpriteEmitter4->UseRegularSizeScale = false;
	SpriteEmitter4->UniformSize = true;
	SpriteEmitter4->Acceleration = FVector(5, 0, 0);
	//SpriteEmitter4->ColorScale[0]=FParticleColorScale({0,FColor(30, 30, 30, 255)});
	//SpriteEmitter4->ColorScale[1]=FParticleColorScale({1,FColor(226, 226, 226, 255)});
	//SpriteEmitter4->ColorScale[2]=FParticleColorScale({1,FColor(255, 255, 255, 255)});
	SpriteEmitter4->FadeOutStartTime = 7;
	SpriteEmitter4->FadeInEndTime = 1;
	SpriteEmitter4->MaxParticles = 100;
	//SpriteEmitter4->StartLocationRange=X=(Min=-100, Max=100)|Y=(Min=-100, Max=100)|Z=(Min=0, Max=0);
	SpriteEmitter4->SpinCCWorCW = FVector(0.25, 0.75, 0.5);
	//SpriteEmitter4->SpinsPerSecondRange=X=(Min=0.03, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->StartSpinRange=X=(Min=0, Max=32000)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter4->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter4->SizeScale[1]=FParticleTimeScale({1,8});
	//SpriteEmitter4->StartSizeRange=X=(Min=44, Max=44)|Y=(Min=100, Max=100)|Z=(Min=133, Max=133);
	SpriteEmitter4->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter4->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball01_Mat.fx_smk_ball01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter4->TextureUSubdivisions = 1;
	SpriteEmitter4->TextureVSubdivisions = 1;
	SpriteEmitter4->LifetimeRange = FRange({ 15, 15 });
	//SpriteEmitter4->StartVelocityRange=X=(Min=-10, Max=10)|Y=(Min=-10, Max=10)|Z=(Min=50, Max=25);
	SpriteEmitter4->fWindFactor = 3;
	USpriteEmitter* SpriteEmitter5 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter5->UseColorScale = true;
	SpriteEmitter5->FadeOut = true;
	SpriteEmitter5->RespawnDeadParticles = false;
	SpriteEmitter5->SpinParticles = true;
	SpriteEmitter5->UseSizeScale = true;
	SpriteEmitter5->UseRegularSizeScale = false;
	SpriteEmitter5->UniformSize = true;
	SpriteEmitter5->AutomaticInitialSpawning = false;
	//SpriteEmitter5->ColorScale[0]=FParticleColorScale({0,FColor(55, 85, 255, 255)});
	//SpriteEmitter5->ColorScale[1]=FParticleColorScale({0.064286,FColor(92, 92, 92, 255)});
	//SpriteEmitter5->ColorScale[2]=FParticleColorScale({1,FColor(0, 0, 0, 177)});
	SpriteEmitter5->FadeOutStartTime = 4;
	SpriteEmitter5->FadeInEndTime = 0.5;
	SpriteEmitter5->MaxParticles = 20;
	//SpriteEmitter5->StartLocationRange=X=(Min=-175, Max=175)|Y=(Min=-175, Max=175)|Z=(Min=-10, Max=-30);
	//SpriteEmitter5->SpinsPerSecondRange=X=(Min=0.01, Max=0.02)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter5->SizeScale[0]=FParticleTimeScale({0,2});
	//SpriteEmitter5->SizeScale[1]=FParticleTimeScale({1,6});
	//SpriteEmitter5->StartSizeRange=X=(Min=111, Max=111)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter5->InitialParticlesPerSecond = 15;
	SpriteEmitter5->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter5->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball01_Mat.fx_smk_ball01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter5->TextureUSubdivisions = 1;
	SpriteEmitter5->TextureVSubdivisions = 1;
	SpriteEmitter5->LifetimeRange = FRange({ 11, 11 });
	//SpriteEmitter5->StartVelocityRange=X=(Min=-100, Max=100)|Y=(Min=-100, Max=100)|Z=(Min=66, Max=66);
	SpriteEmitter5->fWindFactor = 3;
	Emitters = { MeshEmitter11,SpriteEmitter0,SpriteEmitter1,SpriteEmitter2,SpriteEmitter3,SpriteEmitter4,SpriteEmitter5 };
}

void Aem_bt_Javelinexplosion::PostBeginPlay()
{
	SpawnLight();
}

void Aem_bt_Javelinexplosion::SpawnLight()
{
	//Spawn(Class'AGP_Effects.aux_light_ExpLightB');
}

void Aem_bt_Javelinexplosion::BeginPlay()
{
	Cast<UMeshEmitter>(Emitters[0])->StaticMesh = LoadObject<UStaticMesh>(NULL, TEXT("StaticMesh'/Game/AmericasArmy/Meshes/M_AA2_FX/Particles/fx_part_con_chunk1.fx_part_con_chunk1'"), NULL, LOAD_None, NULL);
}
