// All the original content belonged to the US Army

#include "AA29/Object/Actor/Emitter/BaseContactEmitter/em_bt_mk19grenexplosion/em_bt_mk19grenexplosion.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/SpriteEmitter/SpriteEmitter.h"
#include "AA29/Object/BaseEmitter/ParticleEmitter/MeshEmitter/MeshEmitter.h"

Aem_bt_mk19grenexplosion::Aem_bt_mk19grenexplosion()
{
	UMeshEmitter* MeshEmitter11 = NewObject<UMeshEmitter>(UMeshEmitter::StaticClass());
	MeshEmitter11->StaticMesh = LoadObject<UStaticMesh>(NULL, TEXT("StaticMesh'/Game/AmericasArmy/Meshes/M_AA2_FX/Particles/fx_part_con_chunk1.fx_part_con_chunk1'"), NULL, LOAD_None, NULL);
	MeshEmitter11->UseCollision = true;
	MeshEmitter11->UseMaxCollisions = true;
	MeshEmitter11->RespawnDeadParticles = false;
	MeshEmitter11->AutoDestroy = true;
	MeshEmitter11->AutomaticInitialSpawning = false;
	MeshEmitter11->Acceleration = FVector(0, 0, -440);
	//MeshEmitter11->DampingFactorRange=X=(Min=0.6, Max=0.6)|Y=(Min=0.6, Max=0.6)|Z=(Min=0.2, Max=0.2);
	MeshEmitter11->MaxCollisions = FRange({ 2, 2 });
	MeshEmitter11->MaxParticles = 4;
	MeshEmitter11->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//MeshEmitter11->StartSizeRange=X=(Min=0.25, Max=0.25)|Y=(Min=0.25, Max=0.25)|Z=(Min=0.25, Max=0.25);
	MeshEmitter11->InitialParticlesPerSecond = 500;
	MeshEmitter11->SecondsBeforeInactive = 0;
	MeshEmitter11->LifetimeRange = FRange({ 3, 3 });
	//MeshEmitter11->StartVelocityRange=X=(Min=-300, Max=-400)|Y=(Min=-200, Max=200)|Z=(Min=-200, Max=200);
	USpriteEmitter* SpriteEmitter12 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter12->UseColorScale = true;
	SpriteEmitter12->FadeOut = true;
	SpriteEmitter12->RespawnDeadParticles = false;
	SpriteEmitter12->SpinParticles = true;
	SpriteEmitter12->UseSizeScale = true;
	SpriteEmitter12->UseRegularSizeScale = false;
	SpriteEmitter12->UniformSize = true;
	SpriteEmitter12->AutomaticInitialSpawning = false;
	SpriteEmitter12->Acceleration = FVector(0, 0, -111);
	//SpriteEmitter12->ColorScale[0]=FParticleColorScale({0,FColor(56, 69, 80, 255)});
	//SpriteEmitter12->ColorScale[1]=FParticleColorScale({0.5,FColor(0, 0, 0, 177)});
	//SpriteEmitter12->ColorScale[2]=FParticleColorScale({1,FColor(0, 0, 0, 177)});
	SpriteEmitter12->FadeOutStartTime = 0.05;
	SpriteEmitter12->MaxParticles = 120;
	SpriteEmitter12->AddLocationFromOtherEmitter = 0;
	//SpriteEmitter12->SpinsPerSecondRange=X=(Min=0.2, Max=0.4)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->StartSpinRange=X=(Min=300, Max=-300)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter12->SizeScale[0]=FParticleTimeScale({1,6});
	//SpriteEmitter12->StartSizeRange=X=(Min=20, Max=20)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter12->InitialParticlesPerSecond = 110;
	SpriteEmitter12->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter12->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball04_Mat.fx_smk_ball04_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter12->SecondsBeforeInactive = 0;
	SpriteEmitter12->LifetimeRange = FRange({ 1, 1 });
	SpriteEmitter12->InitialDelayRange = FRange({ 0.1, 0.1 });
	USpriteEmitter* SpriteEmitter17 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter17->UseColorScale = true;
	SpriteEmitter17->FadeOut = true;
	SpriteEmitter17->FadeIn = true;
	SpriteEmitter17->RespawnDeadParticles = false;
	SpriteEmitter17->SpinParticles = true;
	SpriteEmitter17->DampRotation = true;
	SpriteEmitter17->UseSizeScale = true;
	SpriteEmitter17->UseRegularSizeScale = false;
	SpriteEmitter17->UniformSize = true;
	SpriteEmitter17->AutomaticInitialSpawning = false;
	//SpriteEmitter17->ColorScale[0]=FParticleColorScale({0,FColor(179, 206, 247, 255)});
	//SpriteEmitter17->ColorScale[1]=FParticleColorScale({0.1,FColor(94, 158, 255, 255)});
	//SpriteEmitter17->ColorScale[2]=FParticleColorScale({0.3,FColor(87, 105, 125, 255)});
	//SpriteEmitter17->ColorScale[3]=FParticleColorScale({1,FColor(52, 61, 73, 255)});
	SpriteEmitter17->FadeOutStartTime = 0.5;
	SpriteEmitter17->FadeInEndTime = 0.3;
	SpriteEmitter17->MaxParticles = 4;
	//SpriteEmitter17->StartLocationRange=X=(Min=0, Max=222)|Y=(Min=-33, Max=33)|Z=(Min=-33, Max=33);
	SpriteEmitter17->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter17->SpinsPerSecondRange=X=(Min=0.2, Max=0.4)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter17->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter17->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter17->SizeScale[1]=FParticleTimeScale({0.2,4});
	//SpriteEmitter17->SizeScale[2]=FParticleTimeScale({1,8});
	//SpriteEmitter17->StartSizeRange=X=(Min=14, Max=16)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter17->InitialParticlesPerSecond = 999;
	SpriteEmitter17->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter17->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_smk_ball02_Mat.fx_smk_ball02_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter17->LifetimeRange = FRange({ 1, 1.2 });
	//SpriteEmitter17->StartVelocityRange=X=(Min=-1111, Max=-1111)|Y=(Min=-99, Max=99)|Z=(Min=-99, Max=99);
	//SpriteEmitter17->VelocityLossRange=X=(Min=4, Max=4)|Y=(Min=4, Max=4)|Z=(Min=4, Max=4);
	USpriteEmitter* SpriteEmitter14 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter14->FadeOut = true;
	SpriteEmitter14->FadeIn = true;
	SpriteEmitter14->RespawnDeadParticles = false;
	SpriteEmitter14->SpinParticles = true;
	SpriteEmitter14->UseSizeScale = true;
	SpriteEmitter14->UseRegularSizeScale = false;
	SpriteEmitter14->UniformSize = true;
	SpriteEmitter14->AutomaticInitialSpawning = false;
	SpriteEmitter14->Acceleration = FVector(0, 0, -999);
	SpriteEmitter14->FadeOutStartTime = 0.8;
	SpriteEmitter14->FadeInEndTime = 0.3;
	SpriteEmitter14->MaxParticles = 4;
	//SpriteEmitter14->StartLocationRange=X=(Min=0, Max=0)|Y=(Min=0, Max=0)|Z=(Min=-88, Max=-66);
	SpriteEmitter14->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter14->SpinsPerSecondRange=X=(Min=0, Max=0.05)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter14->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter14->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter14->SizeScale[1]=FParticleTimeScale({1,3});
	//SpriteEmitter14->StartSizeRange=X=(Min=77, Max=77)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter14->InitialParticlesPerSecond = 99;
	SpriteEmitter14->DrawStyle = EParticleDrawStyle::PTDS_AlphaBlend;
	SpriteEmitter14->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particle/fx2_part_dirtclumps_Mat.fx2_part_dirtclumps_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter14->LifetimeRange = FRange({ 1, 1 });
	//SpriteEmitter14->StartVelocityRange=X=(Min=-666, Max=-777)|Y=(Min=-222, Max=222)|Z=(Min=222, Max=222);
	//SpriteEmitter14->VelocityLossRange=X=(Min=1, Max=1)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter8 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter8->FadeOut = true;
	SpriteEmitter8->RespawnDeadParticles = false;
	SpriteEmitter8->SpinParticles = true;
	SpriteEmitter8->UseSizeScale = true;
	SpriteEmitter8->UseRegularSizeScale = false;
	SpriteEmitter8->UniformSize = true;
	SpriteEmitter8->AutomaticInitialSpawning = false;
	SpriteEmitter8->BlendBetweenSubdivisions = true;
	SpriteEmitter8->FadeOutStartTime = 0.1;
	SpriteEmitter8->FadeInEndTime = 0.2;
	SpriteEmitter8->MaxParticles = 3;
	//SpriteEmitter8->StartLocationRange=X=(Min=-11, Max=-22)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	SpriteEmitter8->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter8->SpinsPerSecondRange=X=(Min=0.2, Max=0.21)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->StartSpinRange=X=(Min=0, Max=32600)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter8->SizeScale[1]=FParticleTimeScale({1,2.5});
	//SpriteEmitter8->StartSizeRange=X=(Min=55, Max=60)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter8->InitialParticlesPerSecond = 33;
	SpriteEmitter8->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter8->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_part_flash01_Mat.fx_part_flash01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter8->TextureUSubdivisions = 2;
	SpriteEmitter8->TextureVSubdivisions = 2;
	SpriteEmitter8->LifetimeRange = FRange({ 0.25, 0.25 });
	//SpriteEmitter8->StartVelocityRange=X=(Min=-155, Max=-133)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter8->VelocityLossRange=X=(Min=2, Max=2)|Y=(Min=2, Max=2)|Z=(Min=2, Max=2);
	USpriteEmitter* SpriteEmitter13 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter13->UseColorScale = true;
	SpriteEmitter13->FadeOut = true;
	SpriteEmitter13->RespawnDeadParticles = false;
	SpriteEmitter13->UseSizeScale = true;
	SpriteEmitter13->UseRegularSizeScale = false;
	SpriteEmitter13->UniformSize = true;
	SpriteEmitter13->AutomaticInitialSpawning = false;
	SpriteEmitter13->Acceleration = FVector(0, 0, -777);
	//SpriteEmitter13->ColorScale[0]=FParticleColorScale({0,FColor(140, 194, 255, 0)});
	//SpriteEmitter13->ColorScale[1]=FParticleColorScale({1,FColor(38, 57, 89, 0)});
	SpriteEmitter13->FadeOutStartTime = 0.5;
	SpriteEmitter13->MaxParticles = 11;
	SpriteEmitter13->UseRotationFrom = EParticleRotationSource::PTRS_Actor;
	//SpriteEmitter13->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter13->SizeScale[1]=FParticleTimeScale({1,0.8});
	//SpriteEmitter13->StartSizeRange=X=(Min=5, Max=7)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter13->InitialParticlesPerSecond = 1111;
	SpriteEmitter13->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter13->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Corona/fx2_cor_05_Mat.fx2_cor_05_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter13->LifetimeRange = FRange({ 1.5, 1.7 });
	//SpriteEmitter13->StartVelocityRange=X=(Min=-555, Max=-1555)|Y=(Min=-222, Max=222)|Z=(Min=-222, Max=222);
	//SpriteEmitter13->VelocityLossRange=X=(Min=1, Max=1)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter9 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter9->UseCollision = true;
	SpriteEmitter9->UseMaxCollisions = true;
	SpriteEmitter9->UseColorScale = true;
	SpriteEmitter9->FadeOut = true;
	SpriteEmitter9->RespawnDeadParticles = false;
	SpriteEmitter9->UseSizeScale = true;
	SpriteEmitter9->UseRegularSizeScale = false;
	SpriteEmitter9->UniformSize = true;
	SpriteEmitter9->AutomaticInitialSpawning = false;
	SpriteEmitter9->Acceleration = FVector(0, 0, -1111);
	//SpriteEmitter9->DampingFactorRange=X=(Min=0.6, Max=0.6)|Y=(Min=0.6, Max=0.6)|Z=(Min=0.2, Max=0.2);
	SpriteEmitter9->MaxCollisions = FRange({ 1, 3 });
	//SpriteEmitter9->ColorScale[0]=FParticleColorScale({0,FColor(140, 194, 255, 0)});
	//SpriteEmitter9->ColorScale[1]=FParticleColorScale({1,FColor(38, 57, 89, 0)});
	SpriteEmitter9->FadeOutStartTime = 0.5;
	SpriteEmitter9->MaxParticles = 12;
	//SpriteEmitter9->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter9->SizeScale[1]=FParticleTimeScale({1,0.8});
	//SpriteEmitter9->StartSizeRange=X=(Min=3, Max=4)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter9->InitialParticlesPerSecond = 1111;
	SpriteEmitter9->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter9->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Corona/fx2_cor_05_Mat.fx2_cor_05_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter9->LifetimeRange = FRange({ 2.2, 2.7 });
	//SpriteEmitter9->StartVelocityRange=X=(Min=-1111, Max=1111)|Y=(Min=-1111, Max=1111)|Z=(Min=-222, Max=1111);
	//SpriteEmitter9->VelocityLossRange=X=(Min=1, Max=1)|Y=(Min=1, Max=1)|Z=(Min=1, Max=1);
	USpriteEmitter* SpriteEmitter10 = NewObject<USpriteEmitter>(USpriteEmitter::StaticClass());
	SpriteEmitter10->RespawnDeadParticles = false;
	SpriteEmitter10->SpinParticles = true;
	SpriteEmitter10->UseSizeScale = true;
	SpriteEmitter10->UseRegularSizeScale = false;
	SpriteEmitter10->UniformSize = true;
	SpriteEmitter10->AutomaticInitialSpawning = false;
	SpriteEmitter10->MaxParticles = 1;
	//SpriteEmitter10->StartSpinRange=X=(Min=32600, Max=0)|Y=(Min=0, Max=0)|Z=(Min=0, Max=0);
	//SpriteEmitter10->SizeScale[0]=FParticleTimeScale({0,1});
	//SpriteEmitter10->SizeScale[1]=FParticleTimeScale({1,3});
	//SpriteEmitter10->StartSizeRange=X=(Min=77, Max=77)|Y=(Min=100, Max=100)|Z=(Min=100, Max=100);
	SpriteEmitter10->InitialParticlesPerSecond = 55;
	SpriteEmitter10->DrawStyle = EParticleDrawStyle::PTDS_Brighten;
	SpriteEmitter10->Texture = LoadObject<UMaterialInstance>(NULL, TEXT("MaterialInstanceConstant'/Game/AmericasArmy/Textures/T_AA2_FX/Particles/fx_particle_startblast01_Mat.fx_particle_startblast01_Mat'"), NULL, LOAD_None, NULL);
	SpriteEmitter10->LifetimeRange = FRange({ 0.05, 0.05 });
	Emitters = { MeshEmitter11,SpriteEmitter12,SpriteEmitter17,SpriteEmitter14,SpriteEmitter8,SpriteEmitter13,SpriteEmitter9,SpriteEmitter10 };
}

void Aem_bt_mk19grenexplosion::BeginPlay()
{
	//MeshEmitter(Emitters[0]).StaticMesh = StaticMesh(DynamicLoadObject("M_AA2_FX.Particles.fx_part_con_chunk1", Class'StaticMesh'));
	Cast<UMeshEmitter>(Emitters[0])->StaticMesh = LoadObject<UStaticMesh>(NULL, TEXT("StaticMesh'/Game/AmericasArmy/Meshes/M_AA2_FX/Particles/fx_part_con_chunk1.fx_part_con_chunk1'"), NULL, LOAD_None, NULL);
}

