// All the original content belonged to the US Army

#pragma once

#include "CoreMinimal.h"
#include "AA29/Object/UIBase/UIFrame/UIFrame.h"
#include "MainMenuFrame.generated.h"

/**
 * 
 */
UCLASS()
class AA29_API UMainMenuFrame : public UUIFrame
{
	GENERATED_BODY()
public:
	UMainMenuFrame();

	/*
	const UIE_None = 0;
	const UIE_Training = 1;
	const UIE_MPMain = 2;
	const UIE_QuickMP = 3;
	const UIE_Settings = 4;
	const UIE_Credits = 5;
	const UIE_Quit = 6;
	const UIE_MainMenu = 7;
	const UIE_ConfirmQuit = 8;
	const UIE_GoArmy = 9;
	const UIE_ArmyOps = 10;
	const UIE_ParentalLink = 11;
	const UIE_OnlineHelp = 13;
	const UIE_Resume = 14;
	const UIE_CreditsArmy = 15;
	const UIE_Disconnect = 16;
	const UIE_ParentalControl = 17;
	const UIE_Maximize = 21;
	const UIE_Close = 22;
	const UIE_GettingStarted = 30;
	const UIE_GettingStartedPrev = 31;
	const UIE_GettingStartedNext = 32;
	const UIE_MissionSelect = 100;
	const UIE_TourPrev = 104;
	const UIE_TourNext = 105;
	const UIE_MissionPrev = 106;
	const UIE_MissionNext = 107;
	const UIE_TourBriefSelect = 110;
	const UIE_TourBriefBack = 113;
	const UIE_TourBriefPrevPage = 111;
	const UIE_TourBriefNextPage = 112;
	const UIE_HistoryBrief = 120;
	const UIE_HistoryBriefPrevPage = 121;
	const UIE_HistoryBriefNextPage = 122;
	const UIE_MissionBrief = 130;
	const UIE_MissionBriefPrevPage = 131;
	const UIE_MissionBriefNextPage = 132;
	const UIE_PlayMission = 140;
	const UIE_CreateAccount = 200;
	const UIE_Login = 201;
	const UIE_ServerBrowser = 202;
	const UIE_LoginExit = 203;
	const UIE_GameSpyArcade = 204;
	const UIE_TestAccount = 205;
	const UIE_ServerBrowserSCI = 206;
	const UIE_ParentAccept = 325;
	const UIE_SettingsControls = 400;
	const UIE_ControlsViewSettings = 410;
	const UIE_ControlsMovement = 411;
	const UIE_ControlsCombat = 412;
	const UIE_ControlsComm = 413;
	const UIE_ControlsMisc = 414;
	const UIE_SettingsVideo = 420;
	const UIE_SettingsVideoAdvanced = 421;
	const UIE_SettingsVideoDecals = 422;
	const UIE_SettingsAudio = 430;
	const UIE_SettingsHUD = 440;
	const UIE_SettingsWeaponMod = 450;
	const UIE_RefreshWeaponMod = 451;
	const UIE_ResetDefaultsAll = 550;
	const UIE_ResetDefaultsView = 551;
	const UIE_ResetDefaultsMovement = 552;
	const UIE_ResetDefaultsCombat = 553;
	const UIE_ResetDefaultsMisc = 554;
	const UIE_AcceptSkinTone = 555;
	const UIE_ResetDefaultsComm = 556;
	const UIE_ResetDefaultVideo = 560;
	const UIE_AcceptNewVideo = 561;
	const UIE_ResetDefaultVideoAdvanced = 562;
	const UIE_AcceptNewVideoAdvanced = 563;
	const UIE_ResetDefaultVideoDecals = 564;
	const UIE_AcceptNewVideoDecals = 565;
	const UIE_ResetDefaultAudio = 570;
	const UIE_AcceptNewAudio = 571;
	const UIE_ResetDefaultHUD = 580;
	const UIE_UpdateServerList = 800;
	const UIE_RefreshServerList = 801;
	const UIE_EditFilters = 802;
	const UIE_RefreshSelected = 803;
	const UIE_PrevPlayerList = 804;
	const UIE_NextPlayerList = 805;
	const UIE_SortOfficial = 810;
	const UIE_SortMiles = 811;
	const UIE_SortPassword = 812;
	const UIE_SortFavorite = 813;
	const UIE_SortServerName = 814;
	const UIE_SortPlayers = 815;
	const UIE_SortPing = 816;
	const UIE_SortTour = 817;
	const UIE_SortMapName = 818;
	const UIE_JoinServer = 850;
	const UIE_HomeLANLeasing = 851;
	const UIE_SCILeasing = 852;
	const UIE_MsgBoxYes = 1000;
	const UIE_MsgBoxNo = 1001;
	const SID_Main = 0;
	const SID_Training = 1;
	const SID_MPMain = 2;
	const SID_QuickMP = 3;
	const SID_Settings = 4;
	const SID_Credits = 5;
	const SID_CreditsArmy = 6;
	const SID_ParentalControl = 7;
	const SID_Obstacle = 10;
	const SID_RifleRange = 11;
	const SID_GettingStarted = 30;
	const SID_Obs1 = 31;
	const SID_Obs2 = 32;
	const SID_Obs3 = 33;
	const SID_Obs4 = 34;
	const SID_Obs5 = 35;
	const SID_RR1 = 41;
	const SID_RR2 = 42;
	const SID_RR3 = 43;
	const SID_RR4 = 44;
	const SID_RR5 = 45;
	const SID_MissionSelect = 100;
	const SID_TourBrief = 101;
	const SID_HistoryBrief = 102;
	const SID_MissionBriefSP = 103;
	const SID_MissionBriefMP = 104;
	const SID_Login = 201;
	const SID_ServerBrowser = 202;
	const SID_FilterEditor = 203;
	const SID_SettingsControls = 400;
	const SID_ControlsViewSettings = 410;
	const SID_ControlsMovement = 411;
	const SID_ControlsCombat = 412;
	const SID_ControlsComm = 413;
	const SID_ControlsMisc = 414;
	const SID_SettingsVideo = 420;
	const SID_SettingsVideoAdvanced = 421;
	const SID_SettingsVideoDecals = 422;
	const SID_SettingsAudio = 430;
	const SID_SettingsHUD = 440;
	const SID_SettingsWeaponMod = 450;
	const SID_StaticMainMenu = 666;
	const SID_TitleMainMenu = 700;
	const SID_TitleSettings = 701;
	const SID_TitleTraining = 702;
	const SID_TitleObstacle = 703;
	const SID_TitleRifleRange = 704;
	const SID_SubMainMenu = 800;
	const SID_SubSettings = 801;
	const SID_SubTraining = 802;
	const SID_SubObstacle = 803;
	const SID_SubRifleRange = 804;
	const ID_None = 0;
	const ID_Training = 1;
	const ID_MPMain = 2;
	const ID_QuickMP = 3;
	const ID_Settings = 4;
	const ID_Credits = 5;
	const ID_Quit = 6;
	const ID_Resume = 7;
	const ID_CreditsArmy = 8;
	const ID_ParentalControl = 9;
	const ID_Controls = 10;
	const ID_Video = 11;
	const ID_Audio = 12;
	const ID_MainMenu = 14;
	const ID_GoArmy = 15;
	const ID_ArmyOps = 16;
	const ID_Disconnect = 17;
	const ID_GettingStartedText = 20;
	const ID_GettingStartedPrev = 21;
	const ID_GettingStartedNext = 22;
	const ID_SettingsControls = 400;
	const ID_ControlsViewSettings = 410;
	const ID_ControlsMovement = 411;
	const ID_ControlsCombat = 412;
	const ID_ControlsMisc = 413;
	const ID_SettingsVideo = 420;
	const ID_SettingsVideoAdvanced = 421;
	const ID_SettingsVideoDecals = 422;
	const ID_SettingsAudio = 430;
	const ID_SettingsHUD = 440;
	const ID_SettingsWeaponMod = 450;
	const ID_ScrollingCredits = 600;
	const ID_Obstacle = 20;
	const ID_RifleRange = 21;
	const ID_RecruiterChat = 108;
	const ID_GoArmyWebsite = 109;
	const ID_EmailRecruiter = 110;
	const ID_ArmyGameWebsite = 111;
	const ID_Back = 98;
	const ID_Border = 99;
	const ID_MainBackground = 100;
	const ID_MissionSelect = 100;
	const ID_ILDTours = 102;
	const ID_ILDMissions = 103;
	const ID_TourPrev = 104;
	const ID_TourNext = 105;
	const ID_MissionPrev = 106;
	const ID_MissionNext = 107;
	const ID_TourBrief = 110;
	const ID_TourBriefPrevPage = 111;
	const ID_TourBriefNextPage = 112;
	const ID_HistoryBrief = 120;
	const ID_HistoryBriefPrevPage = 121;
	const ID_HistoryBriefNextPage = 122;
	const ID_MissionBriefSP = 130;
	const ID_MissionBriefPrevPage = 131;
	const ID_MissionBriefNextPage = 132;
	const ID_MissionBriefTeam0 = 150;
	const ID_MissionBriefTeam1 = 160;
	const ID_TourPage = 161;
	const ID_CreateAccount = 200;
	const ID_Login = 201;
	const ID_ServerBrowser = 202;
	const ID_MapName = 203;
	const ID_Status = 204;
	const ID_TestAccount = 205;
	const ID_UserName = 300;
	const ID_Password = 301;
	const ID_News1 = 302;
	const ID_News2 = 303;
	const ID_News3 = 304;
	const ID_News4 = 305;
	const ID_ParentPassword = 320;
	const ID_LanguageFilter = 321;
	const ID_NoBlood = 322;
	const ID_MilesOnly = 323;
	const ID_NoSniper = 324;
	const ID_ParentAccept = 325;
	const ID_ParentStatus1 = 326;
	const ID_ParentStatus2 = 327;
	const ID_ParentPassword2 = 328;
	const ID_RunWalk = 500;
	const ID_MoveForward = 501;
	const ID_MoveBackward = 502;
	const ID_StepLeft = 503;
	const ID_StepRight = 504;
	const ID_Jump = 505;
	const ID_Crouch = 506;
	const ID_Prone = 507;
	const ID_TurnLeft = 508;
	const ID_TurnRight = 509;
	const ID_SideStepTurn = 510;
	const ID_MantleActivate = 511;
	const ID_MouseLook = 512;
	const ID_LookUp = 513;
	const ID_LookDown = 514;
	const ID_CenterView = 515;
	const ID_MouseSensitivity = 516;
	const ID_Fire = 517;
	const ID_ChangeFireMode = 518;
	const ID_SupportedFire = 519;
	const ID_ZoomWeapon = 520;
	const ID_ReloadWeapon = 521;
	const ID_ClearJam = 522;
	const ID_SwapHands = 523;
	const ID_DropWeapon = 524;
	const ID_SwapAltShoulder = 525;
	const ID_SetSquadTarget = 526;
	const ID_GrenadeFrag = 527;
	const ID_GrenadeSmoke = 528;
	const ID_GrenadeFlash = 529;
	const ID_GrenadeInc = 905;
	const ID_Communication = 530;
	const ID_NightVision = 531;
	const ID_Binoculars = 900;
	const ID_Chat = 532;
	const ID_ChatTeam = 533;
	const ID_ReportIn = 901;
	const ID_VoteKick = 902;
	const ID_CallMedic = 903;
	const ID_Pause = 534;
	const ID_Screenshot = 535;
	const ID_InvertMouse = 536;
	const ID_LeanLeft = 537;
	const ID_LeanRight = 538;
	const ID_CommoRadio = 539;
	const ID_CommoSquadRadio = 540;
	const ID_CommoGlobal = 541;
	const ID_CommoHand = 542;
	const ID_CommoWhisper = 543;
	const ID_CommoShout = 544;
	const ID_LeanToggle = 545;
	const ID_AutoSwapFromGrenade = 546;
	const ID_Sprint = 547;
	const ID_ResetDefaultsAll = 550;
	const ID_ResetDefaultsView = 551;
	const ID_ResetDefaultsMovement = 552;
	const ID_ResetDefaultsCombat = 553;
	const ID_ResetDefaultsMisc = 554;
	const ID_ResetDefaultsComm = 555;
	const ID_ResetDefaultVideo = 560;
	const ID_AcceptNewVideo = 561;
	const ID_ResetDefaultVideoAdvanced = 562;
	const ID_AcceptNewVideoAdvanced = 563;
	const ID_ResetDefaultVideoDecals = 564;
	const ID_AcceptNewVideoDecals = 565;
	const ID_ResetDefaultAudio = 570;
	const ID_AcceptNewAudio = 571;
	const ID_ResetDefaultHUD = 580;
	const ID_ReduceMouseLag = 600;
	const ID_UsePrecaching = 601;
	const ID_UseTrilinear = 602;
	const ID_UseTripleBuffering = 603;
	const ID_UseCubemaps = 604;
	const ID_UseCompressedLightmaps = 605;
	const ID_VideoGamma = 610;
	const ID_VideoContrast = 611;
	const ID_VideoBrightness = 612;
	const ID_VideoMode = 613;
	const ID_VideoHUDColor = 615;
	const ID_VideoHUDAlpha = 616;
	const ID_VideoHUDCrosshair = 617;
	const ID_VideoStartFullScreen = 618;
	const ID_AudioSoundVolume = 620;
	const ID_AudioUseEAX = 622;
	const ID_AudioReverseStereo = 623;
	const ID_NoClientSideEffects = 624;
	const ID_HUDHideAmmoCount = 630;
	const ID_HUDHideWeaponStatus = 631;
	const ID_HUDHideWeapon = 632;
	const ID_HUDHideGrenades = 633;
	const ID_HUDHideHealth = 634;
	const ID_HUDHideCombatEffect = 635;
	const ID_HUDHideOptics = 636;
	const ID_HUDHideCompass = 637;
	const ID_HUDHideTimer = 638;
	const ID_TextureDetailInterface = 640;
	const ID_TextureDetailTerrain = 641;
	const ID_TextureDetailWeaponSkin = 642;
	const ID_TextureDetailPlayerSkin = 643;
	const ID_TextureDetailWorld = 644;
	const ID_TextureDetailRenderMap = 645;
	const ID_TextureDetailLightmap = 646;
	const ID_KeepDecals = 650;
	const ID_KeepDecoDecals = 651;
	const ID_FadeDecoDecals = 652;
	const ID_WM_MainRail = 680;
	const ID_WM_TopRail = 681;
	const ID_WM_LeftRail = 682;
	const ID_WM_RightRail = 683;
	const ID_WM_Bottom = 684;
	const ID_WM_Barrel = 685;
	const ID_WM_Index = 686;
	const ID_SkinToneNone = 700;
	const ID_SkinToneLight = 701;
	const ID_SkinToneMed = 702;
	const ID_SkinToneDark = 703;
	const ID_UpdateServerList = 800;
	const ID_RefreshServerList = 801;
	const ID_EditFilters = 802;
	const ID_RefreshSelected = 803;
	const ID_ServerScrollbar = 804;
	const ID_ServerPassword = 805;
	const ID_GameSpyLogo = 806;
	const ID_AndromedaLogo = 807;
	const ID_SortOfficial = 810;
	const ID_SortMiles = 811;
	const ID_SortPassword = 812;
	const ID_SortFavorite = 813;
	const ID_SortServerName = 814;
	const ID_SortPlayers = 815;
	const ID_SortPing = 816;
	const ID_SortTour = 817;
	const ID_SortMapName = 818;
	const ID_CBOfficial = 820;
	const ID_CBFavorites = 821;
	const ID_CBMiles = 822;
	const ID_CBPassword = 823;
	const ID_CBTour = 824;
	const ID_CBMission = 825;
	const ID_CBROELimit = 826;
	const ID_CBServerPing = 827;
	const ID_CBPlayerPing = 828;
	const ID_CBAutoSort = 829;
	const ID_EBFilterName = 830;
	const ID_ServerListDisplay = 850;
	const ID_MsgBoxText = 1000;
	const ID_MsgBoxYes = 1001;
	const ID_MsgBoxNo = 1002;
	const GID_SoundQuality = 1;
	const GID_ColorDepth = 2;
	const GID_TextureDetail = 3;
	const GID_SkinTone = 4;
	const kSortNone = 0;
	const kSortServer = 1;
	const kSortPlayers = 2;
	const kSortPing = 3;
	const kSortTour = 4;
	const kSortMapName = 5;
	const kBrowser_None = 0;
	const kBrowser_GameSpy = 1;
	const kBrowser_SCI = 2;
	*/

	UPROPERTY()										bool bMenuRestricted;						//var bool bMenuRestricted;
	UPROPERTY()										int32 _iLoginStatus;						//var int _iLoginStatus;
	UPROPERTY()										bool bSortAscending;						//var bool bSortAscending;
	UPROPERTY()										int32 iSortField;							//var int iSortField;
	UPROPERTY()										float _fGameSpyPos;							//var float _fGameSpyPos;
	UPROPERTY()										bool _bNoTourText;							//var bool _bNoTourText;
	UPROPERTY()										FString sBriefingsDir;						//var string sBriefingsDir;
	UPROPERTY()										int32 iDelayedFrame;						//var int iDelayedFrame;
	UPROPERTY()										int32 iDelayedEvent;						//var int iDelayedEvent;
	UPROPERTY()										bool bMissionMP;							//var bool bMissionMP;
	UPROPERTY()										FString sTeam1;								//var string sTeam1;
	UPROPERTY()										FString sTeam0;								//var string sTeam0;
	UPROPERTY()										FString sMission;							//var string sMission;
	UPROPERTY()										FString sTour;								//var string sTour;
	UPROPERTY()										FString sTourIni;							//var string sTourIni;
	UPROPERTY()										int32 iMsgBoxYesOverride;					//var int iMsgBoxYesOverride;
	UPROPERTY()										FPosition dLogInButton;						//var UIBase.Position dLogInButton;
	UPROPERTY()										FPosition dKeyMap;							//var UIBase.Position dKeyMap;
	UPROPERTY()										FPosition dNextButton;						//var UIBase.Position dNextButton;
	UPROPERTY()										FPosition dBackButton;						//var UIBase.Position dBackButton;
	UPROPERTY()										FPosition dSliderThumb;						//var UIBase.Position dSliderThumb;
	UPROPERTY()										FPosition dSliderBack;						//var UIBase.Position dSliderBack;
	UPROPERTY()										FPosition dCheckBox;						//var UIBase.Position dCheckBox;
	UPROPERTY()										UMaterialInstance* _tBackground;			//var Texture _tBackground;
	UPROPERTY()										int32 temp_id;								//var int temp_id;


	void Destroyed();
	void Notify(int32 pUIEvent);
	void DelayEvent(int32 iEvent);
	void MessageBox(FString szMessage, int32 acceptevent, FString acceptstring, FString cancelstring);
	void MessageBoxWorking();
	void MessageBoxLoading();
	void CloseMessageBox();
	void CheckFullScreen();
	void Draw(UCanvas* Canvas);
	void Create(AHUD* pHUD);
	void InitTextureDimensions();
	void CreateScreens();
	void CreateMainMenuScreens();
	void CreateGettingStartedScreen();
	void CreateTrainingScreens();
	void CreateMPMainScreens();
	void CreateParentalControlScreen();
	void RefreshParentalControlScreen();
	void ParentAccept();
	void CreateSettingsScreens();
	void CreateCreditsScreens(FString credits, int32 creditnum);
	void CreateMessageBox();
	void PlayMenuSoundSpecific(USoundBase* Sound);
	void GetCurrentServerBrowser();
	void GetClientBeacon();
	void RunConsoleCommand(FString comm);
	void SetDefaultKeyMaps();
	void SetDefaultCommKeys();
	void SetDefaultMovementKeys();
	void SetDefaultViewKeys();
	void RefreshViewSettings();
	void RefreshMovementSettings();
	void RefreshCombatSettings();
	void RefreshServerBrowser();
	void SetDefaultCombatKeys();
	void SetDefaultMiscKeys();
	void SetDefaultKey(int32 key0, int32 key1, int32 screen_id, int32 control_id);
	void InitKeyMap();
	void SetKeyMap(int32 screen_id, int32 control_id);
	void OpenQuickLan(FString serveraddr);
	void UnbindKey(int32 Key, FString Command);
	void UnbindSpecificKey(int32 Key, FString Command, int32 screen_id, int32 control_id);
	void RefreshVideoSettings();
	void RefreshVideoAdvancedSettings();
	void RefreshVideoDecalsSettings();
	void RefreshAudioSettings();
	void RefreshHUDSettings();
	void RefreshWeaponModSettings();
	void RefreshCheckBox(int32 screen_id, int32 control_id);
	void RefreshCheckBoxB(int32 screen_id, int32 control_id);
	void RefreshCheckBoxFn(int32 screen_id, int32 control_id);
	void RefreshCheckBoxC(int32 screen_id, int32 control_id);
	void RefreshSliderSeg(int32 screen_id, int32 control_id);
	void SetCheckBox(int32 screen_id, int32 control_id, bool Status);
	void SetCheckBoxB(int32 screen_id, int32 control_id, bool Status);
	void SetCheckBoxFn(int32 screen_id, int32 control_id, bool Status);
	void SetCheckBoxC(int32 screen_id, int32 control_id, bool Status);
	void SetSliderSeg(int32 screen_id, int32 control_id, int32 Status);
	void AcceptCheckBox(int32 screen_id, int32 control_id);
	void AcceptCheckBoxB(int32 screen_id, int32 control_id);
	void AcceptCheckBoxC(int32 screen_id, int32 control_id);
	void AcceptSliderSeg(int32 screen_id, int32 control_id);
	void AcceptVideoSettings();
	void AcceptVideoAdvancedSettings();
	void AcceptVideoDecalsSettings();
	void AcceptAudioSettings();
	void ResetVideoDefault();
	void ResetVideoAdvancedDefault();
	void ResetVideoDecalsDefault();
	void ResetAudioDefault();
	void ResetHUDDefault();
	void RefreshSliders();
	void RefreshControlsMisc();
	void AcceptSkinTone();
	void RefreshSlider(int32 screen_id, int32 control_id);
	void SetSlider(int32 screen_id, int32 control_id, float Value);
	void AcceptSlider(int32 screen_id, int32 control_id);
	void RefreshLoginScreen();
	void UpdateLoginInfo();
	void SetResolution(int32 X, int32 Y);
	void GetDesiredX();
	void GetDesiredY();
	void RefreshToursDisplay();
	void RefreshTourMissionDisplays();
	void SetNoTourText(bool bNoTourText);
	void UpdateResumeGame();
	void SetSkinTone();
	void SetGameSpyPos(int32 pos);
	void GetGameSpyPos();
	void UpdateGameSpyPos(int32 pos);
	void ConnectToGameSpyServer(int32 Index);
	void JoinSelectedServer();
	void ServerBrowserSort(int32 Index);
	void SetServerBrowserFilter(FString sFilter);
	void RefreshSelectedServer();
	void SelectLogin();
	void SetLoginStatus(int32 iStatus, FString sStatus, FString sNavMsg);
	void NavigatePlayerList(int32 Direction);
	void SetNewsLine(int32 Index, FString Text);
	void GetServerPassword();

};
