// All the original content belonged to the US Army


#include "AA29/Object/GUI/GUIComponent/GUIMultiComponent/GUIPanel/GUIContentPanel/AAGUIBadgeDescription/AAGUIBadgeDescription.h"

UAAGUIBadgeDescription::UAAGUIBadgeDescription()
{
	InitialBadgeIndex = -1;
	CurrentBadgeIndex = -1;
	//__OnPreDraw__Delegate = "AAGUIBadgeDescription.MyPreDraw";


	//Badges[0] = ("Ribbons|(Tommy Rieman);", "(CLICK FOR DETAILS);|This is the soldier's ribbon rack for the Class-A uniform. Each award a Soldier earns during his military career is represented by a series of colored ribbons, some of which have special designations like oak clusters and clasps to signify multiple awardings of a given award.",			LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/t_ui_uniform_ribbons_all_Rieman_Mat.t_ui_uniform_ribbons_all_Rieman_Mat'"), NULL, LOAD_None, NULL), "AGP_Interface.AARealHeroRibbonDisplay", "AGP_Interface.AARealHeroStats_TommyRieman", "");
	//Badges[1] = ("Ribbons|(Jason Amerine);", "(CLICK FOR DETAILS);|This is the soldier's ribbon rack for the Class-A uniform. Each award a Soldier earns during his military career is represented by a series of colored ribbons, some of which have special designations like oak clusters and clasps to signify multiple awardings of a given award.",			LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/t_ui_uniform_ribbons_all_Amerine_Mat.t_ui_uniform_ribbons_all_Amerine_Mat'"), NULL, LOAD_None, NULL), "AGP_Interface.AARealHeroRibbonDisplay", "AGP_Interface.AARealHeroStats_JasonAmerine", "");
	//Badges[2] = ("Ribbons|(Gerald Wolford);", "(CLICK FOR DETAILS);|This is the soldier's ribbon rack for the Class-A uniform. Each award a Soldier earns during his military career is represented by a series of colored ribbons, some of which have special designations like oak clusters and clasps to signify multiple awardings of a given award.",			LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/t_ui_uniform_ribbons_all_Wolford', "AGP_Interface.AARealHeroRibbonDisplay", "AGP_Interface.AARealHeroStats_GeraldWolford", "");
	//Badges[3] = ("Ribbons|(Matthew Zedwick);", "(CLICK FOR DETAILS);|This is the soldier's ribbon rack for the Class-A uniform. Each award a Soldier earns during his military career is represented by a series of colored ribbons, some of which have special designations like oak clusters and clasps to signify multiple awardings of a given award.",			LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/t_ui_uniform_ribbons_all_Zedwick', "AGP_Interface.AARealHeroRibbonDisplay", "AGP_Interface.AARealHeroStats_MatthewZedwick", "");
	//Badges[4] = ("Combat Infantry Badge", "This coveted badge is awarded to a Soldier who meets three requirements. The Soldier must be an Infantryman or a Special Forces Soldier, must be assigned to an Infantry or Special Forces unit during such time as the unit is engaged in active ground combat with the enemy, and must actively participate in such ground combat. The bar is blue, the color associated with the Infantry branch. The musket is adapted from the Infantry insignia of branch and represents the first official U.S. shoulder arm, the 1795 model Springfield Arsenal musket. The musket was adopted as the official Infantry branch insignia in 1924. The oak leaf wreath symbolizes steadfastness, strength and loyalty.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_cib_ClassA', "", "", "");
	//Badges[5] = ("Combat Infantry Badge<ACU>", "This coveted badge is awarded to a Soldier who meets three requirements.  The Soldier must be an Infantryman or a Special Forces Soldier, must be assigned to an Infantry or Special Forces unit during such time as the unit is engaged in active ground combat with the enemy, and must actively participate in such ground combat. The musket is adapted from the Infantry insignia of branch and represents the first official U.S. shoulder arm, the 1795 model Springfield Arsenal musket. The musket was adopted as the official Infantry branch insignia in 1924. The oak leaf wreath symbolizes steadfastness, strength and loyalty. The badge color is subdued (black); when worn on the Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_cib_acu', "", "", "");
	//Badges[6] = ("Expert Infantry Badge", "This badge is awarded to Infantrymen and Special Forces Soldiers who demonstrate expertise in 30 different infantry tasks over a three-day period.  Tasks include marksmanship, physical training, day and night land navigation, a 12 mile forced march as well as mastery of Infantry weaponry and equipment. The Expert Infantry Badge is similar to the Combat Infantry Badge, but lacks the oak leaf wreath. The bar is blue, the color associated with the Infantry branch. The musket is adapted from the Infantry insignia of branch and represents the first official U.S. shoulder arm, 1795 model Springfield Arsenal musket. The musket was adopted as the official Infantry branch insignia in 1924.", nullptr, "", "", "");
	//Badges[7] = ("Expert Infantry Badge<ACU>", "This badge is awarded to Infantrymen and Special Forces Soldiers who demonstrate expertise in 30 different infantry tasks over a three-day period.  Tasks include marksmanship, physical training, day and night land navigation, a 12 mile forced march as well as mastery of Infantry weaponry and equipment.  The Expert Infantry Badge is similar to the Combat Infantry Badge, but lacks the oak leaf wreath. The musket is adapted from the Infantry insignia of branch and represents the first official U.S. shoulder arm, 1795 model Springfield Arsenal musket. The musket was adopted as the official Infantry branch insignia in 1924. The badge color is subdued (black); when worn on the Army Combat Uniform.", nullptr, "", "", "");
	//Badges[8] = ("Air Assault Badge", "This badge is awarded to Soldiers who graduate from the 10 day air assault training course. The wings suggest flight and together with the helicopter symbolize individual skills and qualifications in assault landings from helicopters.",																					LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_AirAssault_ClassA', "", "", "");
	//Badges[9] = ("Air Assault Badge<ACU>", "This badge is awarded to Soldiers who graduate from the 10 day air assault training course. The wings suggest flight and together with the helicopter symbolize individual skills and qualifications in assault landings from helicopters. The badge color is subdued (black); when worn on the Army Combat Uniform.",	LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_AirAssault_ACU', "", "", "");
	//Badges[10] = ("Military Freefall Parachutist Badge", "This badge is awarded to Special Operations Forces Soldiers who graduate from the Military Free Fall course for HALO(High Altitude Low Opening); and HAHO(High Altitude High Opening);.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_MFF_ClassA', "", "", "");
	//Badges[11] = ("Military Freefall Parachutist Badge<ACU>", "This badge is awarded to Special Operations Forces Soldiers who graduate from the Military Free Fall course for HALO(High Altitude Low Opening); and HAHO(High Altitude High Opening);. The badge color is subdued (black); when worn on the Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_MFF_ACU', "", "", "");
	//Badges[12] = ("Parachutist- Basic Badge", "This badge is awarded to any Soldier who has graduated from Airborne School at Fort Benning Georgia. Airborne School is a rigorous three week course divided into three separate weeks of paratrooper training. The first week is ground week.  During ground week students learn how to properly exist an aircraft in flight, how to steer a parachute during decent, and how to properly execute a parachute landing. The second week is tower week.  During tower week students continue to develop their aircraft exit and parachute landing technique.  They also demonstrate their ability to control a parachute during decent and execute a proper landing during drops from a 250 foot tower. The third week is jump week.  During jump week students conduct five parachute jumps during daylight and at night.  Upon graduation, students earn the coveted silver wings. A Soldier who participates in at least one combat parachute jump may be awarded the parachutist badge as well.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_para_ClassA', "", "", "");
	//Badges[13] = ("Parachutist- Basic Badge<ACU>", "This badge is awarded to any Soldier who has graduated from Airborne School at Fort Benning Georgia. Airborne School is a rigorous three week course divided into three separate weeks of paratrooper training. The first week is ground week.  During ground week students learn how to properly exist an aircraft in flight, how to steer a parachute during decent, and how to properly execute a parachute landing. The second week is tower week.  During tower week students continue to develop their aircraft exit and parachute landing technique.  They also demonstrate their ability to control a parachute during decent and execute a proper landing during drops from a 250 foot tower. The third week is jump week.  During jump week students conduct five parachute jumps during daylight and at night.  Upon graduation, students earn the coveted silver wings. A Soldier who participates in at least one combat parachute jump may be awarded the parachutist badge as well. The badge color is subdued (black); when worn on the Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_para_acu', "", "", "");
	//Badges[14] = ("Parachutist- Senior Badge", "This badge is awarded to a basic parachutist who has graduated from the Jumpmaster Course; participated in a minimum of 30 jumps to include 15 jumps with combat equipment; two night jumps, one of which is as jumpmaster; two mass tactical jumps which culminate in an airborne assault exercise; and served on jump status with an airborne unit or other organization authorized parachutists for a total of at least 24 months.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_ParaSenior__ClassA', "", "", "");
	//Badges[15] = ("Parachutist- Senior Badge<ACU>", "This badge is awarded to a basic parachutist who has graduated from the Jumpmaster Course; participated in a minimum of 30 jumps to include 15 jumps with combat equipment; two night jumps, one of which is as jumpmaster; two mass tactical jumps which culminate in an airborne assault exercise; and served on jump status with an airborne unit or other organization authorized parachutists for a total of at least 24 months. The badge color is subdued (black); when worn on the Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_ParaSenior_ACU', "", "", "");
	//Badges[16] = ("Parachutist- Senior Badge<325th Airborne>", "This badge is awarded to a basic parachutist who has graduated from the Jumpmaster Course; participated in a minimum of 30 jumps to include 15 jumps with combat equipment; two night jumps, one of which is as jumpmaster; two mass tactical jumps which culminate in an airborne assault exercise; and served on jump status with an airborne unit or other organization authorized parachutists for a total of at least 24 months. Backed with the colors of the 325th Airborne unit.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_ParaSenior_Flash325th_ClassA', "", "", "");
	//Badges[17] = ("Pathfinder Badge", "The Commandant of the U.S. Army Infantry School at Fort Benning Georgia may award the Pathfinder Badge to any Soldier who successfully completes the three week Pathfinder Course. The Pathfinder Course teaches an Airborne qualified Soldier how to infiltrate a potential area of operation for a large Airborne force, seek out, prepare and mark appropriate drop zones for that force. The wing suggests flight and airborne capabilities; the torch symbolizes leadership and guidance implying pathfinder combat skills.", nullptr, "", "", "");
	//Badges[18] = ("Pathfinder Badge<ACU>", "The Commandant of the U.S. Army Infantry School at Fort Benning Georgia may award the Pathfinder Badge to any Soldier who successfully completes the three week Pathfinder Course. The Pathfinder Course teaches an Airborne qualified Soldier how to infiltrate a potential area of operation for a large Airborne force, seek out, prepare and mark appropriate drop zones for that force. The wing suggests flight and airborne capabilities; the torch symbolizes leadership and guidance implying pathfinder combat skills. The badge color is subdued (black); when worn on the Army Combat Uniform.", nullptr, "", "", "");
	//Badges[19] = ("Expert Marksman Badge", "Gunnery and Marksmanship Qualification Badges: Indicate degree of qualification with a weapon. More than one qualification badge can be worn if recipient has different qualifications degrees with different weapons. The three levels of qualification are Expert, Sharpshooter and Marksman.||Weapons Qualification Bars: Are attached below the qualification badge and denote specific weapon system proficiency. Additional weapon qualification bars can be attached to a single qualification badge. Examples of the weapons qualification bars are; rifle, pistol and grenade. These badges are worn by enlisted Soldiers only.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_ExpertMarksman_ClassA', "", "", "");
	//Badges[20] = ("Infantry Blue Shoulder Cord", "The Infantry Blue Shoulder Cord is the unique accoutrement of officers and enlisted Infantrymen. The cord is blue, the color associated with the Infantry branch.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Cord_Blue', "", "", "");
	//Badges[21] = ("Army Staff Badge", "This badge is awarded by officials of Headquarters, Department of the Army to military personnel serving on their staff and within their subordinate agencies.  It represents the Coat of Arms of the United States. The badge is based on the General Staff insignia with a black star in lieu of the Silver Star.  The addition of the laurel leaves indicates achievement.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_ArmyStaff', "", "", "");
	//Badges[22] = ("Special Forces Officer Insignia", "The Special Forces branch insignia was authorized in 1987 for wear by personnel in the Special Forces branch. Originally (from 1890 to 1926);, crossed arrows were prescribed for wear by Indian Scouts. During World War II, the crossed arrows were worn as collar insignia by officers and enlisted personnel assigned to the First Special Service Force.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_branch_SF_Officer', "", "", "");
	//Badges[23] = ("", "", nullptr, "", "", "");
	//Badges[24] = ("Enlisted Branch Insignia", "The Infantry crossed muskets were first introduced into the Army as the insignia of officers and enlisted men of the Infantry on 19 November 1875. Early on, the Army modified the insignia to keep pace with the fielding of new rifles. However, in 1924 the Army selected crossed 1795 Springfield Arsenal muskets as the standard Infantry branch insignia. This musket was the first official shoulder arm of the United States.  This .69 caliber smooth bore, flint lock, muzzle loader was made with interchangeable parts in a a government arsenal. There have been slight modifications in the size of the insignia over the years; however, the basic design has remained unchanged.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_branch_Plain', "", "", "");
	//Badges[25] = ("Infantry Branch Insignia", "The Infantry branch insignia with blue backing disk. The Infantry crossed muskets were first introduced into the Army as the insignia of officers and enlisted men of the Infantry on 19 November 1875. Early on, the Army modified the insignia to keep pace with the fielding of new rifles. However, in 1924 the Army selected crossed 1795 Springfield Arsenal muskets as the standard Infantry branch insignia. This musket was the first official shoulder arm of the United States.  This .69 caliber smooth bore, flint lock, muzzle loader was made with interchangeable parts in a a government arsenal. There have been slight modifications in the size of the insignia over the years; however, the basic design has remained unchanged.  The disc is blue, the color associated with the Infantry branch. ", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_pin_branch_Infantry', "", "", "");
	//Badges[26] = ("Australian Jump Wings", "Jump Wings: Badges awarded for foreign country parachute training.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_Jumpwings_Australian_ClassA', "", "", "");
	//Badges[27] = ("Belgian Jump Wings", "Jump Wings: Badges awarded for foreign country parachute training.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_Jumpwings_Belgian_ClassA', "", "", "");
	//Badges[28] = ("Venezuelan Jump Wings", "Jump Wings: Badges awarded for foreign country parachute training.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_jumpwings_Ven', "", "", "");
	//Badges[29] = ("<Amerine Jump Wings>", "Jump Wings: Badges awarded for foreign country parachute training.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_jumpwings_Ven', "", "", "");
	//Badges[30] = ("Rank Major", "A Gold Oak Leaf signifies the rank of Major. A Major is a Commissioned "Field Grade" Officer who has successfully led Soldiers at the Platoon and Company level.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_Rank_Major_ClassA', "", "", "");
	//Badges[31] = ("Rank Major<ACU>", "A Gold Oak Leaf signifies the rank of Major. A Major is a Commissioned "Field Grade" Officer who has successfully led Soldiers at the Platoon and Company level. Insignia colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_MAJ_ACU', "", "", "");
	//Badges[32] = ("Rank Sergeant", "Soldiers earning the rank of E-5 or Sergeant (SGT); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants perform fundamental leadership roles at fire team, squad, platoon, and company level. A Sergeant is normally a Soldier with 3-5 years of experience.  In the Infantry a Sergeant leads a fire team of four to five Soldiers.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SGT', "", "", "");
	//Badges[33] = ("Rank Sergeant<ACU>", "Soldiers earning the rank of E-5 or Sergeant (SGT); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants perform fundamental leadership roles. A Sergeant is normally a Soldier with 3-5 years of experience.  In the Infantry a Sergeant leads a fire team of four to five Soldiers.  Insignia colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SGT_ACU', "", "", "");
	//Badges[34] = ("Rank Sergeant First Class", "Soldiers earning the rank of E-7 or Sergeant First Class (SFC); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants fill fundamental leadership roles. A Sergeant First Class is a career Non-Commissioned Officer with 12 or more years of experience.  In the Infantry these NCOs lead platoons of approximately thirty Soldiers.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SFC', "", "", "");
	//Badges[35] = ("Rank Sergeant First Class<ACU>", "Soldiers earning the rank of E-7 or Sergeant First Class (SFC); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants fill fundamental leadership roles. A Sergeant First Class is a career Non-Commissioned Officer with 12 or more years of experience.  In the Infantry these NCOs lead platoons of approximately thirty Soldiers.  Insignia colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SFC_ACU', "", "", "");
	//Badges[36] = ("Rank Staff Sergeant", "Soldiers earning the rank of E-6 or Staff Sergeant (SSG); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants fill fundamental leadership roles. A Staff Sergeant is a Non-Commissioned Officer with 6-12 years of experience.  In the Infantry these NCOs lead squads of eight to nine Soldiers.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SSG', "", "", "");
	//Badges[37] = ("Rank Staff Sergeant<ACU>", "Soldiers earning the rank of E-6 or Staff Sergeant (SSG); are considered Non-Commissioned Officers or NCO's. The NCO Corps is the backbone of the Army since sergeants fill fundamental leadership roles. A Staff Sergeant is a Non-Commissioned Officer with 6-12 years of experience.  In the Infantry these NCOs lead squads of eight to nine Soldiers. Insignia colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SSG_ACU', "", "", "");
	//Badges[38] = ("Special Forces Patch", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SF_ClassA', "", "", "");
	//Badges[39] = ("Special Forces Patch<ACU>", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land. Patch colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SF_ACU', "", "", "");
	//Badges[40] = ("Special Forces Combat Patch", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SF_Airborne_ClassA', "", "", "");
	//Badges[41] = ("Special Forces Combat Patch<ACU>", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SF_Airborne_ACU', "", "", "");
	//Badges[42] = ("Special Forces with Ranger Patch", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land.||The Ranger Tab is worn by Soldiers who have graduated from the Ranger Course. The 61 day Ranger Course is designed to further develop leaders who are physically and mentally tough and self-disciplined and challenges them to think, act and react effectively in stress approaching that found in combat.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SFwRanger_ClassA', "", "", "");
	//Badges[43] = ("Special Forces with Ranger Patch<ACU>", "The arrowhead shape is suggestive of frontier warrior skills mastered by Native Americans. The dagger represents the unconventional nature of Special Forces operations, and the three lightning flashes, their ability to strike rapidly by air, water or land. Patch colors are subdued when worn on ACU.||The Ranger Tab is worn by Soldiers who have graduated from the Ranger Course. The 61 day Ranger Course is designed to further develop leaders who are physically and mentally tough and self-disciplined and challenges them to think, act and react effectively in stress approaching that found in combat.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_SF_wRangerTab_ACU', "", "", "");
	//Badges[44] = ("", "", nullptr, "", "", "");
	//Badges[45] = ("", "", nullptr, "", "", "");
	//Badges[46] = ("1st Cavalry Patch", "Yellow, the traditional cavalry color, and the horse's head refer to the division's original cavalry structure. Black, symbolic of iron, alludes to the transition to tanks and armor. The black diagonal stripe represents a sword and is a mark of military honor; it also implies movement "up the field" and thus symbolizes aggressive attack. The one diagonal slash, as well as the one horse's head, also alludes to the division's numerical designation.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_1stCav_ClassA', "", "", "");
	//Badges[47] = ("1st Cavalry Patch<ACU>", "The horse's head refer to the division's original cavalry structure. The black diagonal stripe represents a sword and is a mark of military honor; it also implies movement "up the field" and thus symbolizes aggressive attack. The one diagonal slash, as well as the one horse's head, also alludes to the division's numerical designation. Patch colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_1stCav_ACU', "", "", "");
	//Badges[48] = ("1st Cavalry Combat Patch", "Yellow, the traditional cavalry color, and the horse's head refer to the division's original cavalry structure. Black, symbolic of iron, alludes to the transition to tanks and armor. The black diagonal stripe represents a sword and is a mark of military honor; it also implies movement "up the field" and thus symbolizes aggressive attack. The one diagonal slash, as well as the one horse's head, also alludes to the division's numerical designation. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_1stCav_ClassA', "", "", "");
	//Badges[49] = ("1st Cavalry Combat Patch<ACU>", "The horse's head refer to the division's original cavalry structure. The black diagonal stripe represents a sword and is a mark of military honor; it also implies movement "up the field" and thus symbolizes aggressive attack. The one diagonal slash, as well as the one horse's head, also alludes to the division's numerical designation. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform. Patch colors are subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_1stCav_ACU', "", "", "");
	//Badges[50] = ("41st Oregon National Guard Patch", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch__41st_ClassA', "", "", "");
	//Badges[51] = ("41st Oregon National Guard Patch<ACU>", "Patch colors are subdued when worn on ACU", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_41st_ACU', "", "", "");
	//Badges[52] = ("82nd Airborne Patch", "This is the historical 82nd Airborne Division, based out of Fort Bragg, NC. The double "A" refers to the nickname "All American Division" adopted by the organization in France during World War I. The insignia was approved for the 82d Division by the Adjutant General, American Expeditionary Forces on October 21, 1918 and was confirmed by the Adjutant general, War Department on July 8, 1922. The insignia was redesignated for the 82d Airborne Division and an "Airborne" tab authorized on August 31, 1942.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_82_ClassA', "", "", "");
	//Badges[53] = ("82nd Airborne Patch<ACU>", "This is the historical 82nd Airborne Division, based out of Fort Bragg, NC. The double "A" refers to the nickname "All American Division" adopted by the organization in France during World War I. The insignia was approved for the 82d Division by the Adjutant General, American Expeditionary Forces on October 21, 1918 and was confirmed by the Adjutant general, War Department on July 8, 1922. The insignia was redesignated for the 82d Airborne Division and an "Airborne" tab authorized on August 31, 1942. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_Airborne_82nd_ACU', "", "", "");
	//Badges[54] = ("82nd Airborne Combat Patch", "This is the historical 82nd Airborne Division, based out of Fort Bragg, NC. The double "A" refers to the nickname "All American Division" adopted by the organization in France during World War I. The insignia was approved for the 82d Division by the Adjutant General, American Expeditionary Forces on October 21, 1918 and was confirmed by the Adjutant general, War Department on July 8, 1922. The insignia was redesignated for the 82d Airborne Division and an "Airborne" tab authorized on August 31, 1942. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_82_ClassA', "", "", "");
	//Badges[55] = ("82nd Airborne Combat Patch<ACU>", "This is the historical 82nd Airborne Division, based out of Fort Bragg, NC. The double "A" refers to the nickname "All American Division" adopted by the organization in France during World War I. The insignia was approved for the 82d Division by the Adjutant General, American Expeditionary Forces on October 21, 1918 and was confirmed by the Adjutant general, War Department on July 8, 1922. The insignia was redesignated for the 82d Airborne Division and an "Airborne" tab authorized on August 31, 1942. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_Airborne_82nd_ACU', "", "", "");
	//Badges[56] = ("Eco 51st Airborne Patch", "51st Long Range Surveillance Unit is assigned to the 205th Military Intelligence Battalion (Tactical Exploitation); in Darmstadt, Germany, to provide V Corps with long range surveillance capability.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_51st_classA', "", "", "");
	//Badges[57] = ("Eco 51st Airborne Patch<ACU>", "51st Long Range Surveillance Unit is assigned to the 205th Military Intelligence Battalion (Tactical Exploitation); in Darmstadt, Germany, to provide V Corps with long range surveillance capability. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_51st_acu', "", "", "");
	//Badges[58] = ("Eco 51st Airborne Combat Patch", "51st Long Range Surveillance Unit is assigned to the 205th Military Intelligence Battalion (Tactical Exploitation); in Darmstadt, Germany, to provide V Corps with long range surveillance capability. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_51st_classA', "", "", "");
	//Badges[59] = ("Eco 51st Airborne Combat Patch<ACU>", "51st Long Range Surveillance Unit is assigned to the 205th Military Intelligence Battalion (Tactical Exploitation); in Darmstadt, Germany, to provide V Corps with long range surveillance capability. A Combat Patch is authorized to a Soldier who has been in combat with a specific unit. This unit patch is worn on the Soldier’s right sleeve of his dress uniform as well as his Army Combat Uniform. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_airborne_51st_acu', "", "", "");
	//Badges[60] = ("U.S. Military Academy (West Point); Patch", "The United States Military Academy was established in 1802 to provide professional Commissioned Officers to the US Army. The Academy provides a 4 year Baccalaureate education and a Commission as a Second Lieutenant. The shoulder sleeve insignia was originally approved on 26 Nov 1941. A Greek sword, in scabbard bendwise with the helmet of Pallas. A shield displaying the device of the Military Academy in gold.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_WestPoint_ClassA', "", "", "");
	//Badges[61] = ("U.S. Military Academy (West Point); Patch<ACU>", "The United States Military Academy was established in 1802 to provide professional Commissioned Officers to the US Army. The Academy provides a 4 year Baccalaureate education and a Commission as a Second Lieutenant. The shoulder sleeve insignia was originally approved on 26 Nov 1941. A Greek sword, in scabbard bendwise with the helmet of Pallas. A shield displaying the device of the Military Academy in gold. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_WestPoint_ACU', "", "", "");
	//Badges[62] = ("Pentagon Staff Patch", "The pentagonal shape is an allusion to the Pentagon Building, site of Headquarters, Department of the Army. The United States coat of arms is in full color as on the Secretary of the Army flag and the blue of the background is from the National Flag and stands for loyalty and trust. The gold border is symbolic of the quality of leadership provided by the Army Staff.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_Pentagon_ClassA', "", "", "");
	//Badges[63] = ("Pentagon Staff Patch<ACU>", "The pentagonal shape is an allusion to the Pentagon Building, site of Headquarters, Department of the Army. The United States coat of arms is in full color as on the Secretary of the Army flag and the blue of the background is from the National Flag and stands for loyalty and trust. The gold border is symbolic of the quality of leadership provided by the Army Staff. Patch color is subdued when worn on ACU.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_Pentagon_ACU', "", "", "");
	//Badges[64] = ("5th Special Forces Flash<Green Beret>", "Green Beret: During World War II, US Army Special Forces personnel wore a variety of headgear during their operations as members of special operations units. Those who served with the Office of Strategic Services (OSS); in Europe often wore a green beret. Many of the first members of the US Army 10th Special Forces Group (Airborne);, formed at Fort Bragg, North Carolina, in June 1952, were veterans of the OSS. The first official wearing of the newly authorized Green Beret was at a Special Forces demonstration staged for President John F. Kennedy at Fort Bragg on 12 October 1961. President Kennedy was instrumental in the approval by the Department of the Army of the Green Beret for US Special Forces. Currently, all Special Forces-qualified Soldiers wear the Green Beret with the authorized flash of their Special Forces Group. The Green Beret is worn with the Army Combat Uniform as well as the Class A dress uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_5th_MAJ', "", "", "");
	//Badges[65] = ("325th Airborne Flash<Red Beret>", "Maroon Beret: This head gear is worn by airborne qualified personnel assigned to an airborne unit. The maroon beret has been the international symbol of airborne forces since its selection for use by the British Parachute Regiment in 1942. After HQDA encouraged the unofficial use of morale-enhancing headgear in 1973, airborne forces chose to wear the maroon international parachute color beret. On 28 November 1980, HQDA authorized airborne organizations to wear the maroon beret. The maroon beret is worn with the Army Combat Uniform as well as the Class A dress uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_Airborne325th', "", "", "");
	//Badges[66] = ("41st Oregon National Guard Flash<Black Beret>", "Black Beret: The official head gear of US Army Soldiers. On June 14, 2001, the first Army birthday in the new millennium, the black beret became standard wear in the Army. It had been previously worn by ranger units, who changed to the tan beret, the original World War II era colored beret of the Rangers. The black beret is worn with the Army Combat Uniform as well as the Class A dress uniform. ", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_41st', "", "", "");
	//Badges[67] = ("Eco 51st Airborne Flash<Black Beret>", "Black Beret: The official head gear of US Army Soldiers. On June 14, 2001, the first Army birthday in the new millennium, the black beret became standard wear in the Army. It had been previously worn by ranger units, who changed to the tan beret, the original World War II era colored beret of the Rangers. The black beret is worn with the Army Combat Uniform as well as the Class A dress uniform. ", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_Eco51st', "", "", "");
	//Badges[68] = ("Special Forces Unassigned Flash<Green Beret>", "Green Beret: During World War II, US Army Special Forces personnel wore a variety of headgear during their operations as members of special operations units. Those who served with the Office of Strategic Services (OSS); in Europe often wore a green beret. Many of the first members of the US Army 10th Special Forces Group (Airborne);, formed at Fort Bragg, North Carolina, in June 1952, were veterans of the OSS. The first official wearing of the newly authorized Green Beret was at a Special Forces demonstration staged for President John F. Kennedy at Fort Bragg on 12 October 1961. President Kennedy was instrumental in the approval by the Department of the Army of the Green Beret for US Special Forces. Currently, all Special Forces-qualified Soldiers wear the Green Beret with the authorized flash of their Special Forces Group. The Green Beret is worn with the Army Combat Uniform as well as the Class A dress uniform.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_SFUnAssigned_MAJ', "", "", "");
	//Badges[69] = ("Headquarters Department of the Army Flash<Black Beret>", "Black Beret: The official head gear of US Army Soldiers. On June 14, 2001, the first Army birthday in the new millennium, the black beret became standard wear in the Army. It had been previously worn by ranger units, who changed to the tan beret, the original World War II era colored beret of the Rangers. The black beret is worn with the Army Combat Uniform as well as the Class A dress uniform. ", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Flash_HQDA', "", "", "");
	//Badges[70] = ("1st Special Forces Regimental Crest", "The crest is the crossed arrow collar insignia (insignia of the Special Forces Branch); of the First Special Force, World War II. The motto is translated as "From Oppression We Will Liberate Them." The distinctive unit insignia was approved on 8 July 1960. The insignia of the 1st Special Forces was authorized to be worn by personnel of the U.S. Army Special Forces Command (Airborne); and its subordinate units on 7 March 1991.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/t_ui_uniform_pin_sf_crest_classa', "", "", "");
	//Badges[71] = ("325th Airborne Unit Crest", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_UnitCrest_325th', "", "", "");
	//Badges[72] = ("41st Oregon National Guard Crest<Green>", "The green felt backing indicates a leadership role.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_Unitcrest_41stwGreen', "", "", "");
	//Badges[73] = ("41st Oregon National Guard Crest", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_Unitcrest_41st', "", "", "");
	//Badges[74] = ("Eco 51st Airborne Unit Crest<Green>", "The green felt backing indicates a leadership role.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_UnitCrest_Eco51stwGreen', "", "", "");
	//Badges[75] = ("Eco 51st Airborne Unit Crest", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_UnitCrest_Eco51st', "", "", "");
	//Badges[76] = ("Headquarters Department of the Army Crest", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_UnitCrest_HQDA', "", "", "");
	//Badges[77] = ("U.S. Military Academy (West Point); Crest", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Pin_UnitCrest_USMA_WestPoint', "", "", "");
	//Badges[78] = ("Service Stripes (2);", "The service stripe is placed at an angle of 45 degrees with the lower end toward the inside seam of the sleeve, and it is placed 4 inches from the bottom of the sleeve. For each additional period of 3 years honorable service, another service stripe is added above and parallel to the first stripe.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_hash_two', "", "", "");
	//Badges[79] = ("Service Stripes (3);", "The service stripe is placed at an angle of 45 degrees with the lower end toward the inside seam of the sleeve, and it is placed 4 inches from the bottom of the sleeve. For each additional period of 3 years honorable service, another service stripe is added above and parallel to the first stripe.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_hash_three', "", "", "");
	//Badges[80] = ("Overseas Service Bars (2);", "The overseas service bars are authorized for each 6–month period of overseas service.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_bars_two', "", "", "");
	//Badges[81] = ("Joint Meritorious Citation<2 Oak>", "The Joint Meritorious Unit Award is awarded to Joint Activities of the Armed Forces of the United States which have subsequent to January 23, 1979 distinguished themselves by exceptionally meritorious achievement or service in pursuit of joint military missions of great significance. The two oak leaves indicate the Soldier served in units that have received this citation three times.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_JointMeritous_2oaks', "", "", "");
	//Badges[82] = ("Valorous Unit Award", "The Valorous Unit Award is awarded to units of the Armed Forces of the United States for extraordinary heroism in action against an armed enemy of the United States while engaged in military operations involving conflict with an opposing foreign force. The unit must have performed with marked distinction under difficult and hazardous conditions in accomplishing its mission so as to set it apart from the other units participating in the same conflict. The degree of heroism required is the same as that which would warrant award of the Silver Star to an individual.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Valorous', "", "", "");
	//Badges[83] = ("Army Superior Unit Award", "The Army Superior Unit Award is awarded for outstanding meritorious performance of a unit during peacetime in a difficult and challenging mission under extraordinary circumstances. The unit must display such outstanding devotion and superior performance of exceptionally difficult tasks to set it apart from and above other units with similar missions.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Superior', "", "", "");
	//Badges[84] = ("Presidential Unit Citation", "The Presidential Unit Citation is awarded to units of the Armed Forces of the United States for extraordinary heroism in action against an armed enemy occurring on or after 7 December 1941. The unit must display such gallantry, determination, and esprit de corps in accomplishing its mission under extremely difficult and hazardous conditions as to set it apart and above other units participating in the same campaign. The degree of heroism required is the same as that which would warrant award of a Distinguished Service Cross to an individual.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Presidential', "", "", "");
	//Badges[85] = ("Presidential Unit Citation<1 Oak>", "The Presidential Unit Citation is awarded to units of the Armed Forces of the United States for extraordinary heroism in action against an armed enemy occurring on or after 7 December 1941. The unit must display such gallantry, determination, and esprit de corps in accomplishing its mission under extremely difficult and hazardous conditions as to set it apart and above other units participating in the same campaign. The degree of heroism required is the same as that which would warrant award of a Distinguished Service Cross to an individual. The oak leaf indicates the Soldier served in units that have received this citation twice.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Presidential_1oak', "", "", "");
	//Badges[86] = ("Meritorious Unit Commendation", "The Meritorious Unit Commendation is awarded to units for exceptionally meritorious conduct in performance of outstanding services for at least six continuous months during the period of military operations against an armed enemy occurring on or after 1 January 1944. Service in a combat zone is not required, but must be directly related to the combat effort. The unit must display such outstanding devotion and superior performance of exceptionally difficult tasks as to set it apart and above other units with similar missions. The degree of achievement required is the same as that which would warrant award of the Legion of Merit to an individual.", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Meritorious', "", "", "");
	//Badges[87] = ("Army Superior Unit Award|(Reserves);<National Guard>", "", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Ribbon_Unit_Superior_NG', "", "", "");
	//Badges[88] = ("American Flag Patch", "The blue field always flies forward", LoadObject<UMaterialInstance>(NULL, TEXT("UMaterialInstance'/Game/AmericasArmy/Textures/T_AAO_UI/Uniform/T_UI_Uniform_Patch_USFlag_R_Color', "", "", "");

	
}

void UAAGUIBadgeDescription::InitComponent(UGUIController* MyController, UGUIComponent* MyOwner)
{
	/*
	InitComponent(MyController, MyOwner);
	i_BadgeImage = new (None) classClass'GUIImage';
	i_BadgeImage.InitComponent(MyController, Self);
	i_BadgeImage.ImageStyle = 2;
	i_BadgeImage.ImageRenderStyle = 1;
	i_BadgeImage.bAcceptsInput = True;
	i_BadgeImage.bNeverFocus = True;
	i_BadgeImage.__OnClick__Delegate = InternalOnClick;
	AppendComponent(i_BadgeImage, False);
	l_BadgeName = new (None) class'AAGUILabel';
	l_BadgeName.StyleName = "NMLMediumText";
	l_BadgeName.InitComponent(MyController, Self);
	l_BadgeName.TextAlign = 1;
	l_BadgeName.bAcceptsInput = True;
	l_BadgeName.bNeverFocus = True;
	l_BadgeName.__OnClick__Delegate = InternalOnClick;
	l_BadgeName.bMultiLine = True;
	AppendComponent(l_BadgeName, False);
	DescriptionBox = new (None) class'GUIContentBox';
	DescriptionBox.InitComponent(MyController, Self);
	DescriptionBox.SideGaps = 0;
	DescriptionBox.ItemSpacing = 0;
	AppendComponent(DescriptionBox, False);
	l_BadgeDescription = new (None) class'AAGUILabel';
	l_BadgeDescription.StyleName = "NMLSmallText";
	l_BadgeDescription.InitComponent(MyController, DescriptionBox.MyPanel);
	l_BadgeDescription.TextAlign = 0;
	l_BadgeDescription.bAcceptsInput = True;
	l_BadgeDescription.bNeverFocus = True;
	l_BadgeDescription.__OnClick__Delegate = InternalOnClick;
	l_BadgeDescription.bMultiLine = True;
	DescriptionBox.MyPanel.AppendComponent(l_BadgeDescription, False);
	DescribeBadgeByIndex(InitialBadgeIndex, True);
	*/
}

bool UAAGUIBadgeDescription::InternalOnClick(UGUIComponent* Sender)
{
	/*
	Switch(Sender)
	{
			case i_BadgeImage:
			case l_BadgeName:
			case l_BadgeDescription:
				if (MenuPath != "")
				{
					Controller.OpenMenu(MenuPath, MenuParam1, MenuParam2);
				}
				return true;
			default:
	}
	*/
	return false;    //FAKE   /ELiZ
}

void UAAGUIBadgeDescription::ShowMenu()
{
	//DescribeBadgeByIndex(CurrentBadgeIndex, True);
}

bool UAAGUIBadgeDescription::MyPreDraw(UCanvas* Canvas)
{
	/*
	local float DescHeight;
	if (ItemSpacing < 2)
	{
		ItemSpacing = ItemSpacing * Canvas.SizeY;
	}
	DescHeight = ActualHeight() - i_BadgeImage.ActualHeight() - l_BadgeName.ActualHeight() - 4 * ItemSpacing;
	DescriptionBox.WinHeight = DescHeight;
	*/
	return true;
}

int32 UAAGUIBadgeDescription::FindBadgeIndex(FString BadgeToDescribe)
{
	/*
	local int i;
	for (i = 0; i < Badges.Length; i++)
	{
		if (BadgeToDescribe == Badges[i].BadgeName)
		{
			Return i;
		}
	}
	*/
	return -1;
}

void UAAGUIBadgeDescription::DescribeBadge(FString BadgeToDescribe, bool bForceLoad)
{
	//DescribeBadgeByIndex(FindBadgeIndex(BadgeToDescribe), bForceLoad);
}

FString UAAGUIBadgeDescription::RemoveArrows(FString InputName)
{
	FString OutStr="";
	/*
	local int i;
	local string tmp;
	
	OutStr = InputName;
	i = InStr(OutStr, "<");
	if (i != -1)
	{
		tmp = Mid(OutStr, i + 1);
		OutStr = Left(OutStr, i);
		i = InStr(tmp, ">");
		if (i != -1)
		{
			tmp = Mid(tmp, i + 1);
		}
		OutStr = OutStr $ tmp;
		i = InStr(OutStr, "<");
	}
	*/
	return OutStr;
}

void UAAGUIBadgeDescription::DescribeBadgeByIndex(int32 BadgeIndex, bool bForceLoad)
{
	/*
	if (BadgeIndex >= 0)
	{
		if (!bForceLoad && CurrentBadgeIndex == BadgeIndex)
		{
			Return;
		}
		i_BadgeImage.Image = Badges[BadgeIndex].BadgeImage;
		if (i_BadgeImage.Image != None)
		{
			Log("Badge Image:" @ i_BadgeImage.Image);
			i_BadgeImage.WinWidth = 1;
			i_BadgeImage.WinHeight = i_BadgeImage.Image.MaterialVSize() / i_BadgeImage.Image.MaterialUSize() * ActualWidth();
		}
		else
		{
			i_BadgeImage.WinWidth = 0;
			i_BadgeImage.WinHeight = 0;
		}
		Log("BadgeName: " $ Badges[BadgeIndex].BadgeName);
		Log("BadgeName no arrows: " $ RemoveArrows(Badges[BadgeIndex].BadgeName));
		l_BadgeName.Caption = RemoveArrows(Badges[BadgeIndex].BadgeName);
		l_BadgeDescription.Caption = Badges[BadgeIndex].BadgeDescription;
		Log("l_BadgeName.Caption: " $ l_BadgeName.Caption);
		Log("l_BadgeDescription.Caption: " $ l_BadgeDescription.Caption);
		MenuPath = Badges[BadgeIndex].MenuPath;
		MenuParam1 = Badges[BadgeIndex].MenuParam1;
		MenuParam2 = Badges[BadgeIndex].MenuParam2;
	}
	else
	{
		i_BadgeImage.Image = None;
		i_BadgeImage.WinWidth = 0;
		i_BadgeImage.WinHeight = 0;
		l_BadgeName.Caption = "";
		l_BadgeDescription.Caption = "Click on a badge to the left to see a description of it.";
		MenuPath = "";
		MenuParam1 = "";
		MenuParam2 = "";
	}
	CurrentBadgeIndex = BadgeIndex;
	*/
}